<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** One actor shape for humans, agents, and models. */
readonly class Actor implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ActorKind $kind,
        public string $id,
        public string $displayName,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'kind',
            'id',
            'display_name',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for Actor::fromArray()");
            }
        }
        return new self(
            kind: ActorKind::from($data['kind']),
            id: $data['id'],
            displayName: $data['display_name'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'kind' => $this->kind->value,
            'id' => $this->id,
            'display_name' => $this->displayName,
        ];
    }
}
