<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class AnyItemMatchesCondition implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ExistCondition|NotExistsCondition|EqualCondition|NotEqualsCondition|NumberCompareCondition|ContainCondition|ObjectContainsCondition|ArrayContainsCondition|MatcheRegexCondition|JsonSchemaValidCondition|SimilarityGteCondition|LlmJudgedAsCondition|LlmNotJudgedAsCondition|NotContainsCondition|LengthCompareCondition|BetweenCondition|StartWithCondition|EndsWithCondition|AllItemsMatchCondition|AnyItemMatchesCondition|SplitIouCondition $condition,
        public ?string $kind = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            condition: match ($data['condition']['kind'] ?? null) { 'all_items_match' => AllItemsMatchCondition::fromArray($data['condition']), 'any_item_matches' => AnyItemMatchesCondition::fromArray($data['condition']), 'array_contains' => ArrayContainsCondition::fromArray($data['condition']), 'between' => BetweenCondition::fromArray($data['condition']), 'contains' => ContainCondition::fromArray($data['condition']), 'ends_with' => EndsWithCondition::fromArray($data['condition']), 'equals' => EqualCondition::fromArray($data['condition']), 'exists' => ExistCondition::fromArray($data['condition']), 'json_schema_valid' => JsonSchemaValidCondition::fromArray($data['condition']), 'length_compare' => LengthCompareCondition::fromArray($data['condition']), 'llm_judged_as' => LlmJudgedAsCondition::fromArray($data['condition']), 'llm_not_judged_as' => LlmNotJudgedAsCondition::fromArray($data['condition']), 'matches_regex' => MatcheRegexCondition::fromArray($data['condition']), 'not_contains' => NotContainsCondition::fromArray($data['condition']), 'not_equals' => NotEqualsCondition::fromArray($data['condition']), 'not_exists' => NotExistsCondition::fromArray($data['condition']), 'number_compare' => NumberCompareCondition::fromArray($data['condition']), 'object_contains' => ObjectContainsCondition::fromArray($data['condition']), 'similarity_gte' => SimilarityGteCondition::fromArray($data['condition']), 'split_iou_gte' => SplitIouCondition::fromArray($data['condition']), 'starts_with' => StartWithCondition::fromArray($data['condition']), default => throw new \UnexpectedValueException(sprintf('Unknown kind: %s', json_encode($data['condition']['kind'] ?? null))) },
            kind: $data['kind'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'condition' => $this->condition->toArray(),
            'kind' => $this->kind,
        ];
    }
}
