<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class ApiCallInvocation implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        public string $workflowRunId,
        public string $stepId,
        /** When this artifact was written by the orchestrator. */
        public \DateTimeImmutable $createdAt,
        /** @var array<\Retab\Resource\ApiCallAttempt>|null */
        public ?array $attempts = null,
        public ?ErrorDetails $error = null,
        /** Artifact operation that determines the backing record type */
        public string $operation = 'api_call_invocation',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'workflow_run_id',
            'step_id',
            'created_at',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ApiCallInvocation::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            workflowRunId: $data['workflow_run_id'],
            stepId: $data['step_id'],
            createdAt: new \DateTimeImmutable($data['created_at']),
            attempts: isset($data['attempts']) ? array_map(fn ($item) => ApiCallAttempt::fromArray($item), $data['attempts']) : null,
            error: isset($data['error']) ? ErrorDetails::fromArray($data['error']) : null,
            operation: $data['operation'] ?? 'api_call_invocation',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'workflow_run_id' => $this->workflowRunId,
            'step_id' => $this->stepId,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'attempts' => $this->attempts !== null ? array_map(fn ($item) => $item->toArray(), $this->attempts) : null,
            'error' => $this->error?->toArray(),
            'operation' => $this->operation,
        ];
    }
}
