<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Run started programmatically via the public API. */
readonly class ApiTrigger implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** API key id used to start the run, when known */
        public ?string $apiKeyId = null,
        public string $type = 'api',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            apiKeyId: $data['api_key_id'] ?? null,
            type: $data['type'] ?? 'api',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'api_key_id' => $this->apiKeyId,
            'type' => $this->type,
        ];
    }
}
