<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

enum AssertionOutcome: string
{
    case Passed = 'passed';
    case Failed = 'failed';
    case Blocked = 'blocked';
}
