<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Result of evaluating ONE assertion against a block's output.
 *
 * ``outcome`` is a verdict only — pass / fail / blocked. An execution
 * error (the assertion couldn't be evaluated because of a type error,
 * invalid regex, schema validation crash, block execution crash, etc.) is
 * expressed by ``outcome="blocked"`` with a populated ``failure`` whose
 * ``code`` identifies the specific failure mode (``execution_error``,
 * ``type_error``, ``invalid_regex``, ``schema_invalid``,
 * ``block_execution_failed``, ...).
 */
readonly class AssertionResult implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $assertionId,
        public string $conditionKind,
        public AssertionOutcome $outcome,
        public mixed $actualValue = null,
        public mixed $expectedValue = null,
        public ?float $score = null,
        public ?float $threshold = null,
        public ?string $metricKind = null,
        public ?string $assertionLabel = null,
        public ?AssertionFailure $failure = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'assertion_id',
            'condition_kind',
            'outcome',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for AssertionResult::fromArray()");
            }
        }
        return new self(
            assertionId: $data['assertion_id'],
            conditionKind: $data['condition_kind'],
            outcome: AssertionOutcome::from($data['outcome']),
            actualValue: $data['actual_value'] ?? null,
            expectedValue: $data['expected_value'] ?? null,
            score: $data['score'] ?? null,
            threshold: $data['threshold'] ?? null,
            metricKind: $data['metric_kind'] ?? null,
            assertionLabel: $data['assertion_label'] ?? null,
            failure: isset($data['failure']) ? AssertionFailure::fromArray($data['failure']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'assertion_id' => $this->assertionId,
            'condition_kind' => $this->conditionKind,
            'outcome' => $this->outcome->value,
            'actual_value' => $this->actualValue,
            'expected_value' => $this->expectedValue,
            'score' => $this->score,
            'threshold' => $this->threshold,
            'metric_kind' => $this->metricKind,
            'assertion_label' => $this->assertionLabel,
            'failure' => $this->failure?->toArray(),
        ];
    }
}
