<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Single-rule schema dependency for Level 2 drift detection. */
readonly class AssertionSchemaDep implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $schemaPath,
        public string $subtreeHash,
        public ?string $outputHandleId = null,
        public ?bool $dependsOnRoot = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'schema_path',
            'subtree_hash',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for AssertionSchemaDep::fromArray()");
            }
        }
        return new self(
            schemaPath: $data['schema_path'],
            subtreeHash: $data['subtree_hash'],
            outputHandleId: $data['output_handle_id'] ?? null,
            dependsOnRoot: $data['depends_on_root'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'schema_path' => $this->schemaPath,
            'subtree_hash' => $this->subtreeHash,
            'output_handle_id' => $this->outputHandleId,
            'depends_on_root' => $this->dependsOnRoot,
        ];
    }
}
