<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

enum AssertionDriftStatus: string
{
    case Valid = 'valid';
    case Drifted = 'drifted';
    case Broken = 'broken';
}
