<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class AssertionFailure implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $code,
        public string $message,
        /** @var array<string, mixed>|null */
        public ?array $details = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'code',
            'message',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for AssertionFailure::fromArray()");
            }
        }
        return new self(
            code: $data['code'],
            message: $data['message'],
            details: $data['details'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'code' => $this->code,
            'message' => $this->message,
            'details' => $this->details,
        ];
    }
}
