<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** The run is paused on at least one gated block. */
readonly class AwaitingReviewRun implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /**
         * Block IDs that are waiting for review
         * @var array<string>|null
         */
        public ?array $waitingForBlockIds = null,
        public string $status = 'awaiting_review',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            waitingForBlockIds: $data['waiting_for_block_ids'] ?? null,
            status: $data['status'] ?? 'awaiting_review',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'waiting_for_block_ids' => $this->waitingForBlockIds,
            'status' => $this->status,
        ];
    }
}
