<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class BBox implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Left coordinate of the bounding box, relative to page width (0.0 = left edge, 1.0 = right edge). */
        public float $left,
        /** Top coordinate of the bounding box, relative to page height (0.0 = top edge, 1.0 = bottom edge). */
        public float $top,
        /** Width of the bounding box, relative to page width (0.0–1.0). */
        public float $width,
        /** Height of the bounding box, relative to page height (0.0–1.0). */
        public float $height,
        /** 1-based index of the page where this field appears. */
        public int $page,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'left',
            'top',
            'width',
            'height',
            'page',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for BBox::fromArray()");
            }
        }
        return new self(
            left: $data['left'],
            top: $data['top'],
            width: $data['width'],
            height: $data['height'],
            page: $data['page'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'left' => $this->left,
            'top' => $this->top,
            'width' => $this->width,
            'height' => $this->height,
            'page' => $this->page,
        ];
    }
}
