<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Per-lifecycle counts for a batch of block-test runs. */
readonly class BlockTestLifecycleCounts implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?int $pending = null,
        public ?int $queued = null,
        public ?int $running = null,
        public ?int $completed = null,
        public ?int $error = null,
        public ?int $cancelled = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            pending: $data['pending'] ?? null,
            queued: $data['queued'] ?? null,
            running: $data['running'] ?? null,
            completed: $data['completed'] ?? null,
            error: $data['error'] ?? null,
            cancelled: $data['cancelled'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'pending' => $this->pending,
            'queued' => $this->queued,
            'running' => $this->running,
            'completed' => $this->completed,
            'error' => $this->error,
            'cancelled' => $this->cancelled,
        ];
    }
}
