<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Optional request payload for cancel workflow command idempotency. */
readonly class CancelWorkflowRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Optional idempotency key for deduplicating cancel commands */
        public ?string $commandId = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            commandId: $data['command_id'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'command_id' => $this->commandId,
        ];
    }
}
