<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Response for cancel workflow endpoint. */
readonly class CancelWorkflowResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public WorkflowRun $run,
        /** Whether immediate cancellation signaling was available */
        public ?bool $redisAvailable = null,
        /** Cancellation delivery state from this request */
        public ?CancelWorkflowResponseCancellationStatus $cancellationStatus = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'run',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for CancelWorkflowResponse::fromArray()");
            }
        }
        return new self(
            run: WorkflowRun::fromArray($data['run']),
            redisAvailable: $data['redis_available'] ?? null,
            cancellationStatus: isset($data['cancellation_status']) ? CancelWorkflowResponseCancellationStatus::from($data['cancellation_status']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'run' => $this->run->toArray(),
            'redis_available' => $this->redisAvailable,
            'cancellation_status' => $this->cancellationStatus?->value,
        ];
    }
}
