<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class ClassificationDecision implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The reasoning for the classification decision */
        public string $reasoning,
        /** The category name that the document belongs to */
        public string $category,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'reasoning',
            'category',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ClassificationDecision::fromArray()");
            }
        }
        return new self(
            reasoning: $data['reasoning'],
            category: $data['category'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'reasoning' => $this->reasoning,
            'category' => $this->category,
        ];
    }
}
