<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class Classification implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Unique identifier of the classification */
        public string $id,
        /** Information about the classified file */
        public FileRef $file,
        /** Model used for classification */
        public string $model,
        /**
         * Categories the document was classified against
         * @var array<\Retab\Resource\Category>
         */
        public array $categories,
        /** The classification result with reasoning */
        public ClassificationDecision $output,
        /** Number of consensus votes used */
        public ?int $nConsensus = null,
        /** Free-form instructions supplied with the classification request. */
        public ?string $instructions = null,
        /** Consensus metadata for multi-vote classification runs */
        public ?ClassificationConsensus $consensus = null,
        /** Usage information for the classification */
        public ?RetabUsage $usage = null,
        public ?\DateTimeImmutable $createdAt = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            file: FileRef::fromArray($data['file']),
            model: $data['model'],
            categories: array_map(fn ($item) => Category::fromArray($item), $data['categories']),
            output: ClassificationDecision::fromArray($data['output']),
            nConsensus: $data['n_consensus'] ?? null,
            instructions: $data['instructions'] ?? null,
            consensus: isset($data['consensus']) ? ClassificationConsensus::fromArray($data['consensus']) : null,
            usage: isset($data['usage']) ? RetabUsage::fromArray($data['usage']) : null,
            createdAt: isset($data['created_at']) ? new \DateTimeImmutable($data['created_at']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'file' => $this->file->toArray(),
            'model' => $this->model,
            'categories' => array_map(fn ($item) => $item->toArray(), $this->categories),
            'output' => $this->output->toArray(),
            'n_consensus' => $this->nConsensus,
            'instructions' => $this->instructions,
            'consensus' => $this->consensus?->toArray(),
            'usage' => $this->usage?->toArray(),
            'created_at' => $this->createdAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
