<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Public create-classification request body. */
readonly class ClassificationRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The document to classify */
        public MimeData|FileRef $document,
        /**
         * The categories to classify the document into
         * @var array<\Retab\Resource\Category>
         */
        public array $categories,
        /** The model to use for classification */
        public ?string $model = null,
        /** Only use the first N pages of the document for classification. Useful for large documents where classification can be determined from early pages. */
        public ?int $firstNPages = null,
        /** Free-form instructions appended to the system prompt to steer the classification. */
        public ?string $instructions = null,
        /** Number of classification runs to use for consensus voting. Uses deterministic single-pass when set to 1. */
        public ?int $nConsensus = null,
        /** If true, skip the LLM cache and force a fresh completion */
        public ?bool $bustCache = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            document: $data['document'],
            categories: array_map(fn ($item) => Category::fromArray($item), $data['categories']),
            model: $data['model'] ?? null,
            firstNPages: $data['first_n_pages'] ?? null,
            instructions: $data['instructions'] ?? null,
            nConsensus: $data['n_consensus'] ?? null,
            bustCache: $data['bust_cache'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'document' => $this->document->toArray(),
            'categories' => array_map(fn ($item) => $item->toArray(), $this->categories),
            'model' => $this->model,
            'first_n_pages' => $this->firstNPages,
            'instructions' => $this->instructions,
            'n_consensus' => $this->nConsensus,
            'bust_cache' => $this->bustCache,
        ];
    }
}
