<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class ClassificationConsensus implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /**
         * Alternative classification vote outputs used to build the consolidated result.
         * @var array<\Retab\Resource\ClassificationDecision>|null
         */
        public ?array $choices = null,
        /** Consensus likelihood score (0.0-1.0) of the winning classification. */
        public ?float $likelihoods = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            choices: isset($data['choices']) ? array_map(fn ($item) => ClassificationDecision::fromArray($item), $data['choices']) : null,
            likelihoods: $data['likelihoods'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'choices' => $this->choices !== null ? array_map(fn ($item) => $item->toArray(), $this->choices) : null,
            'likelihoods' => $this->likelihoods,
        ];
    }
}
