<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Per-item evaluation result for wildcard array conditions.
 *
 * When a condition path contains .*, each array element is evaluated
 * individually with implicit AND logic (all must match).
 */
readonly class ConditionEvaluationPerItem implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Index of this item in the array */
        public int $index,
        /**
         * Hierarchical indices for nested arrays (e.g., [0, 2, 1] for items[0].subitems[2].field[1])
         * @var array<int>|null
         */
        public ?array $indices = null,
        /** Actual value at this index */
        public mixed $actual = null,
        /** Whether this item matched the condition */
        public ?bool $matched = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'index',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ConditionEvaluationPerItem::fromArray()");
            }
        }
        return new self(
            index: $data['index'],
            indices: $data['indices'] ?? null,
            actual: $data['actual'] ?? null,
            matched: $data['matched'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'index' => $this->index,
            'indices' => $this->indices,
            'actual' => $this->actual,
            'matched' => $this->matched,
        ];
    }
}
