<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Evaluation result for a sub-condition in a compound condition.
 *
 * Used when multiple conditions are combined with AND/OR operators.
 */
readonly class ConditionEvaluationSubCondition implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Identifier for this sub-condition */
        public ?string $subConditionId = null,
        /** JSON path that was evaluated */
        public ?string $path = null,
        /** Comparison operator used */
        public ?string $operator = null,
        /** Expected value */
        public mixed $expected = null,
        /** Actual value found */
        public mixed $actual = null,
        /** Whether this sub-condition matched */
        public ?bool $matched = null,
        /**
         * Per-item breakdown if this sub-condition used a wildcard path
         * @var array<\Retab\Resource\ConditionEvaluationPerItem>|null
         */
        public ?array $perItem = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            subConditionId: $data['sub_condition_id'] ?? null,
            path: $data['path'] ?? null,
            operator: $data['operator'] ?? null,
            expected: $data['expected'] ?? null,
            actual: $data['actual'] ?? null,
            matched: $data['matched'] ?? null,
            perItem: isset($data['per_item']) ? array_map(fn ($item) => ConditionEvaluationPerItem::fromArray($item), $data['per_item']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'sub_condition_id' => $this->subConditionId,
            'path' => $this->path,
            'operator' => $this->operator,
            'expected' => $this->expected,
            'actual' => $this->actual,
            'matched' => $this->matched,
            'per_item' => $this->perItem !== null ? array_map(fn ($item) => $item->toArray(), $this->perItem) : null,
        ];
    }
}
