<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class ConditionalEvaluation implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        public string $workflowRunId,
        public string $stepId,
        /** When this artifact was written by the orchestrator. */
        public \DateTimeImmutable $createdAt,
        /** Artifact operation that determines the backing record type */
        public ?string $operation = null,
        /** @var array<\Retab\Resource\ConditionEvaluationResult>|null */
        public ?array $evaluations = null,
        /** @var array<string>|null */
        public ?array $selectedHandles = null,
        public ?string $matchedBranchId = null,
        /** @var array<string>|null */
        public ?array $matchedConditionIds = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            workflowRunId: $data['workflow_run_id'],
            stepId: $data['step_id'],
            createdAt: new \DateTimeImmutable($data['created_at']),
            operation: $data['operation'] ?? null,
            evaluations: isset($data['evaluations']) ? array_map(fn ($item) => ConditionEvaluationResult::fromArray($item), $data['evaluations']) : null,
            selectedHandles: $data['selected_handles'] ?? null,
            matchedBranchId: $data['matched_branch_id'] ?? null,
            matchedConditionIds: $data['matched_condition_ids'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'workflow_run_id' => $this->workflowRunId,
            'step_id' => $this->stepId,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'operation' => $this->operation,
            'evaluations' => $this->evaluations !== null ? array_map(fn ($item) => $item->toArray(), $this->evaluations) : null,
            'selected_handles' => $this->selectedHandles,
            'matched_branch_id' => $this->matchedBranchId,
            'matched_condition_ids' => $this->matchedConditionIds,
        ];
    }
}
