<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class ContainCondition implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public mixed $expected,
        public string $kind = 'contains',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'expected',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ContainCondition::fromArray()");
            }
        }
        return new self(
            expected: $data['expected'],
            kind: $data['kind'] ?? 'contains',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'expected' => $this->expected,
            'kind' => $this->kind,
        ];
    }
}
