<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Create a fresh workflow run from a workflow id, optional draft/version selector, and optional inputs. */
readonly class CreateFreshWorkflowRunRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Workflow id for the fresh run. */
        public string $workflowId,
        /**
         * Mapping of start_document block IDs to their input documents. Only valid for fresh-run creation (``restart_of`` is None).
         * @var array<string, \Retab\Resource\FileRef|\Retab\Resource\MimeDataInput>|null
         */
        public ?array $documents = null,
        /**
         * Mapping of start-json block IDs to their input JSON data. Only valid for fresh-run creation (``restart_of`` is None).
         * @var array<string, mixed>|null
         */
        public ?array $jsonInputs = null,
        /** Workflow version to run: 'production', 'draft', or a pinned version id like 'ver_...'. Only valid for fresh-run creation. */
        public ?string $version = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'workflow_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for CreateFreshWorkflowRunRequest::fromArray()");
            }
        }
        return new self(
            workflowId: $data['workflow_id'],
            documents: $data['documents'] ?? null,
            jsonInputs: $data['json_inputs'] ?? null,
            version: $data['version'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'workflow_id' => $this->workflowId,
            'documents' => $this->documents,
            'json_inputs' => $this->jsonInputs,
            'version' => $this->version,
        ];
    }
}
