<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Body for ``POST /v1/workflows/blocks/executions``.
 *
 * ``block_id`` is the block to replay; ``run_id`` is the workflow run that
 * sourced the original step's ``handle_inputs``. ``step_id`` optionally pins
 * a concrete step row whose inputs should be used, which is useful for
 * iteration-prefixed for_each body steps.
 */
readonly class CreateBlockExecutionRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Workflow run id that owns the step. */
        public string $runId,
        /** Workflow block id to execute. */
        public string $blockId,
        /** Optional concrete step id whose inputs should be used. When omitted, the block id is used as the canonical step lookup key. */
        public ?string $stepId = null,
        /** Optional override for n_consensus on extract / split / classifier blocks. Must be 3, 5, or 7. */
        public ?int $nConsensus = null,
        /** Whether to verify the upstream subgraph hasn't drifted since the source run. Disable only for explicit force-rerun flows. */
        public ?bool $checkEligibility = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'run_id',
            'block_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for CreateBlockExecutionRequest::fromArray()");
            }
        }
        return new self(
            runId: $data['run_id'],
            blockId: $data['block_id'],
            stepId: $data['step_id'] ?? null,
            nConsensus: $data['n_consensus'] ?? null,
            checkEligibility: $data['check_eligibility'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'run_id' => $this->runId,
            'block_id' => $this->blockId,
            'step_id' => $this->stepId,
            'n_consensus' => $this->nConsensus,
            'check_eligibility' => $this->checkEligibility,
        ];
    }
}
