<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Public create-edit-template request body. */
readonly class CreateEditTemplateRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Name of the template. */
        public string $name,
        /** The PDF document to use as the empty template. */
        public MimeData $document,
        /**
         * Form fields to attach to the template.
         * @var array<\Retab\Resource\FormField>
         */
        public array $formFields,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'name',
            'document',
            'form_fields',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for CreateEditTemplateRequest::fromArray()");
            }
        }
        return new self(
            name: $data['name'],
            document: MimeData::fromArray($data['document']),
            formFields: array_map(fn ($item) => FormField::fromArray($item), $data['form_fields']),
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'name' => $this->name,
            'document' => $this->document->toArray(),
            'form_fields' => array_map(fn ($item) => $item->toArray(), $this->formFields),
        ];
    }
}
