<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class CreateUploadResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Underlying file ID */
        public string $fileId,
        /** Short-lived signed upload URL */
        public string $uploadUrl,
        /** Durable Retab MIMEData reference */
        public MimeData $mimeData,
        /** Upload URL expiration */
        public \DateTimeImmutable $expiresAt,
        /** HTTP method for upload */
        public ?string $uploadMethod = null,
        /**
         * Headers required by the signed upload URL
         * @var array<string, string>|null
         */
        public ?array $uploadHeaders = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            fileId: $data['fileId'],
            uploadUrl: $data['uploadUrl'],
            mimeData: MimeData::fromArray($data['mimeData']),
            expiresAt: new \DateTimeImmutable($data['expiresAt']),
            uploadMethod: $data['uploadMethod'] ?? null,
            uploadHeaders: $data['uploadHeaders'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'fileId' => $this->fileId,
            'uploadUrl' => $this->uploadUrl,
            'mimeData' => $this->mimeData->toArray(),
            'expiresAt' => $this->expiresAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'uploadMethod' => $this->uploadMethod,
            'uploadHeaders' => $this->uploadHeaders,
        ];
    }
}
