<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Run every workflow test for one target in a workflow. */
readonly class CreateWorkflowTestRunForTargetRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $workflowId,
        public WorkflowTestBlockTarget $target,
        public ?int $nConsensus = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            workflowId: $data['workflow_id'],
            target: WorkflowTestBlockTarget::fromArray($data['target']),
            nConsensus: $data['n_consensus'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'workflow_id' => $this->workflowId,
            'target' => $this->target->toArray(),
            'n_consensus' => $this->nConsensus,
        ];
    }
}
