<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * POST /workflows/reviews/versions body.
 *
 * Public callers create corrections, not seeds. ``parent_id`` must
 * reference an existing version under the same ``review_id``; seed versions
 * are created by the runtime through the store path.
 */
readonly class CreateReviewVersionRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $reviewId,
        public string $parentId,
        /**
         * The full reviewed snapshot to store as an immutable version. The object must match the gated block type: extract uses the raw output object; classifier uses {'category': string}; split uses {'documents': [{'name': string, 'pages': positive sorted int[]}]}; for_each uses {'partitions': [{'key': string, 'pages': positive sorted int[]}]}. The server validates the shape and stores the exact submitted object when valid.
         * @var array<string, mixed>
         */
        public array $snapshot,
        public ?string $note = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            reviewId: $data['review_id'],
            parentId: $data['parent_id'],
            snapshot: $data['snapshot'],
            note: $data['note'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'review_id' => $this->reviewId,
            'parent_id' => $this->parentId,
            'snapshot' => $this->snapshot,
            'note' => $this->note,
        ];
    }
}
