<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Body for the flat ``POST /workflows/experiments/runs`` route.
 *
 * Carries the scoping identity in the body — no parent id in the URL
 * (meta-pattern-blueprint §1). ``workflow_id`` is optional because it is
 * derivable from the experiment record; when supplied it is validated
 * against the experiment's stored workflow.
 */
readonly class CreateExperimentRunRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The experiment to create a run for. */
        public string $experimentId,
        /** Optional. When omitted, the workflow is derived from the experiment record. When supplied, must match the experiment's workflow_id (404 otherwise). */
        public ?string $workflowId = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'experiment_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for CreateExperimentRunRequest::fromArray()");
            }
        }
        return new self(
            experimentId: $data['experiment_id'],
            workflowId: $data['workflow_id'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'experiment_id' => $this->experimentId,
            'workflow_id' => $this->workflowId,
        ];
    }
}
