<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class DeclarativePlanChange implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public mixed $before = null,
        public mixed $after = null,
        public mixed $beforeSensitive = null,
        public mixed $afterSensitive = null,
        /** @var array<\Retab\Resource\DeclarativePlanFieldChange>|null */
        public ?array $fieldChanges = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            before: $data['before'] ?? null,
            after: $data['after'] ?? null,
            beforeSensitive: $data['before_sensitive'] ?? null,
            afterSensitive: $data['after_sensitive'] ?? null,
            fieldChanges: isset($data['field_changes']) ? array_map(fn ($item) => DeclarativePlanFieldChange::fromArray($item), $data['field_changes']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'before' => $this->before,
            'after' => $this->after,
            'before_sensitive' => $this->beforeSensitive,
            'after_sensitive' => $this->afterSensitive,
            'field_changes' => $this->fieldChanges !== null ? array_map(fn ($item) => $item->toArray(), $this->fieldChanges) : null,
        ];
    }
}
