<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class DeclarativeValidationResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $workflowId,
        public int $blockCount,
        public int $edgeCount,
        public bool $isValid,
        /** @var array<string, mixed> */
        public array $diagnostics,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'workflow_id',
            'block_count',
            'edge_count',
            'is_valid',
            'diagnostics',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DeclarativeValidationResponse::fromArray()");
            }
        }
        return new self(
            workflowId: $data['workflow_id'],
            blockCount: $data['block_count'],
            edgeCount: $data['edge_count'],
            isValid: $data['is_valid'],
            diagnostics: $data['diagnostics'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'workflow_id' => $this->workflowId,
            'block_count' => $this->blockCount,
            'edge_count' => $this->edgeCount,
            'is_valid' => $this->isValid,
            'diagnostics' => $this->diagnostics,
        ];
    }
}
