<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class DeclarativePlanResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $workflowId,
        public DeclarativePlanResponseAction $action,
        public int $blockCount,
        public int $edgeCount,
        /** @var array<string, mixed> */
        public array $diagnostics,
        public ?string $formatVersion = null,
        public ?DeclarativePlanSummary $summary = null,
        /** @var array<\Retab\Resource\DeclarativePlanResourceChange>|null */
        public ?array $resourceChanges = null,
        public ?string $renderedPlan = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'workflow_id',
            'action',
            'block_count',
            'edge_count',
            'diagnostics',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DeclarativePlanResponse::fromArray()");
            }
        }
        return new self(
            workflowId: $data['workflow_id'],
            action: DeclarativePlanResponseAction::from($data['action']),
            blockCount: $data['block_count'],
            edgeCount: $data['edge_count'],
            diagnostics: $data['diagnostics'],
            formatVersion: $data['format_version'] ?? null,
            summary: isset($data['summary']) ? DeclarativePlanSummary::fromArray($data['summary']) : null,
            resourceChanges: isset($data['resource_changes']) ? array_map(fn ($item) => DeclarativePlanResourceChange::fromArray($item), $data['resource_changes']) : null,
            renderedPlan: $data['rendered_plan'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'workflow_id' => $this->workflowId,
            'action' => $this->action->value,
            'block_count' => $this->blockCount,
            'edge_count' => $this->edgeCount,
            'diagnostics' => $this->diagnostics,
            'format_version' => $this->formatVersion,
            'summary' => $this->summary?->toArray(),
            'resource_changes' => $this->resourceChanges !== null ? array_map(fn ($item) => $item->toArray(), $this->resourceChanges) : null,
            'rendered_plan' => $this->renderedPlan,
        ];
    }
}
