<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class DeclarativePlanResourceChange implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $address,
        public DeclarativePlanResourceChangeTarget $target,
        public string $targetId,
        public string $name,
        /** Resource kind for this plan entry. ``workflow`` and ``edge`` are flat singletons; for ``target='block'`` this carries the block's concrete type (e.g. ``extract``, ``api_call``) so the plan summary can render type-specific labels. */
        public DeclarativePlanResourceChangeType $type,
        /** @var array<\Retab\Resource\DeclarativePlanFieldChangeAction> */
        public array $actions,
        public string $summary,
        public DeclarativePlanChange $change,
        public ?string $path = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            address: $data['address'],
            target: DeclarativePlanResourceChangeTarget::from($data['target']),
            targetId: $data['target_id'],
            name: $data['name'],
            type: DeclarativePlanResourceChangeType::from($data['type']),
            actions: array_map(fn ($item) => DeclarativePlanFieldChangeAction::from($item), $data['actions']),
            summary: $data['summary'],
            change: DeclarativePlanChange::fromArray($data['change']),
            path: $data['path'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'address' => $this->address,
            'target' => $this->target->value,
            'target_id' => $this->targetId,
            'name' => $this->name,
            'type' => $this->type->value,
            'actions' => array_map(fn ($item) => $item->value, $this->actions),
            'summary' => $this->summary,
            'change' => $this->change->toArray(),
            'path' => $this->path,
        ];
    }
}
