<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class DeclarativeExportResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $workflowId,
        public string $yamlDefinition,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'workflow_id',
            'yaml_definition',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DeclarativeExportResponse::fromArray()");
            }
        }
        return new self(
            workflowId: $data['workflow_id'],
            yamlDefinition: $data['yaml_definition'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'workflow_id' => $this->workflowId,
            'yaml_definition' => $this->yamlDefinition,
        ];
    }
}
