<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

enum DeclarativePlanFieldChangeAction: string
{
    case Create = 'create';
    case Update = 'update';
    case Delete = 'delete';
}
