<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class EditResult implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /**
         * Filled form fields (positions, descriptions, and filled values).
         * @var array<\Retab\Resource\FormField>
         */
        public array $formData,
        /** PDF with the filled form values rendered in. */
        public MimeData $filledDocument,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'form_data',
            'filled_document',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for EditResult::fromArray()");
            }
        }
        return new self(
            formData: array_map(fn ($item) => FormField::fromArray($item), $data['form_data']),
            filledDocument: MimeData::fromArray($data['filled_document']),
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'form_data' => array_map(fn ($item) => $item->toArray(), $this->formData),
            'filled_document' => $this->filledDocument->toArray(),
        ];
    }
}
