<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class EditTemplate implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Unique identifier of the template. */
        public string $id,
        /** Name of the template. */
        public string $name,
        /** File information for the empty PDF template. */
        public FileRef $file,
        /** Timestamp of creation. */
        public \DateTimeImmutable $createdAt,
        /** Timestamp of last update. */
        public \DateTimeImmutable $updatedAt,
        /**
         * Form fields attached to the template.
         * @var array<\Retab\Resource\FormField>|null
         */
        public ?array $formFields = null,
        /** Number of form fields in the template. */
        public ?int $fieldCount = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'name',
            'file',
            'created_at',
            'updated_at',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for EditTemplate::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            name: $data['name'],
            file: FileRef::fromArray($data['file']),
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
            formFields: isset($data['form_fields']) ? array_map(fn ($item) => FormField::fromArray($item), $data['form_fields']) : null,
            fieldCount: $data['field_count'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'file' => $this->file->toArray(),
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'form_fields' => $this->formFields !== null ? array_map(fn ($item) => $item->toArray(), $this->formFields) : null,
            'field_count' => $this->fieldCount,
        ];
    }
}
