<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class EditWorkflowArtifact implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Unique identifier of the edit. */
        public string $id,
        /** Information about the source file (input document or template PDF). */
        public FileRef $file,
        /** Model used for the edit operation. */
        public string $model,
        /** Configuration used for the edit operation. */
        public EditConfig $config,
        /** The edit result: filled form fields and the rendered PDF. */
        public EditResult $output,
        /** When this artifact was written by the orchestrator. */
        public \DateTimeImmutable $createdAt,
        /** Free-form instructions supplied with the edit request. */
        public ?string $instructions = null,
        /** Template id used when the edit was created from a template; null for direct-document edits. */
        public ?string $templateId = null,
        /** Usage information for the edit operation. */
        public ?RetabUsage $usage = null,
        /** Artifact operation that determines the backing record type */
        public string $operation = 'edit',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'file',
            'model',
            'config',
            'output',
            'created_at',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for EditWorkflowArtifact::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            file: FileRef::fromArray($data['file']),
            model: $data['model'],
            config: EditConfig::fromArray($data['config']),
            output: EditResult::fromArray($data['output']),
            createdAt: new \DateTimeImmutable($data['created_at']),
            instructions: $data['instructions'] ?? null,
            templateId: $data['template_id'] ?? null,
            usage: isset($data['usage']) ? RetabUsage::fromArray($data['usage']) : null,
            operation: $data['operation'] ?? 'edit',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'file' => $this->file->toArray(),
            'model' => $this->model,
            'config' => $this->config->toArray(),
            'output' => $this->output->toArray(),
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'instructions' => $this->instructions,
            'template_id' => $this->templateId,
            'usage' => $this->usage?->toArray(),
            'operation' => $this->operation,
        ];
    }
}
