<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Run started by an inbound email message. */
readonly class EmailTrigger implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Sender email address */
        public string $sender,
        /** Email subject line */
        public ?string $subject = null,
        public string $type = 'email',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'sender',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for EmailTrigger::fromArray()");
            }
        }
        return new self(
            sender: $data['sender'],
            subject: $data['subject'] ?? null,
            type: $data['type'] ?? 'email',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'sender' => $this->sender,
            'subject' => $this->subject,
            'type' => $this->type,
        ];
    }
}
