<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** The result row failed. Per-job error message is bundled into lifecycle. */
readonly class ErrorWorkflowExperimentResult implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?string $status = null,
        /** Human-readable error message */
        public ?string $message = null,
        /** Structured error context including stack trace */
        public ?ErrorDetails $details = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            status: $data['status'] ?? null,
            message: $data['message'] ?? null,
            details: isset($data['details']) ? ErrorDetails::fromArray($data['details']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'status' => $this->status,
            'message' => $this->message,
            'details' => $this->details?->toArray(),
        ];
    }
}
