<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** The step failed. Error details are bundled into lifecycle. */
readonly class ErrorStepLifecycle implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Human-readable error message */
        public string $message,
        public ?ErrorTerminalStage $stage = null,
        public ?ErrorTerminalCategory $category = null,
        public ?ErrorDetails $details = null,
        public string $status = 'error',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'message',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ErrorStepLifecycle::fromArray()");
            }
        }
        return new self(
            message: $data['message'],
            stage: isset($data['stage']) ? ErrorTerminalStage::from($data['stage']) : null,
            category: isset($data['category']) ? ErrorTerminalCategory::from($data['category']) : null,
            details: isset($data['details']) ? ErrorDetails::fromArray($data['details']) : null,
            status: $data['status'] ?? 'error',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'message' => $this->message,
            'stage' => $this->stage?->value,
            'category' => $this->category?->value,
            'details' => $this->details?->toArray(),
            'status' => $this->status,
        ];
    }
}
