<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** The run failed. All loose error fields are bundled here. */
readonly class ErrorTerminal implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Human-readable error message */
        public string $message,
        public ?string $status = null,
        /** Which execution stage failed */
        public ?ErrorTerminalStage $stage = null,
        /** Error category for retry decisions */
        public ?ErrorTerminalCategory $category = null,
        /** Detailed error context including stack trace */
        public ?ErrorDetails $details = null,
        /** Step ID of the failing step, when the failure was attributable to a specific step */
        public ?string $failingStepId = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            message: $data['message'],
            status: $data['status'] ?? null,
            stage: isset($data['stage']) ? ErrorTerminalStage::from($data['stage']) : null,
            category: isset($data['category']) ? ErrorTerminalCategory::from($data['category']) : null,
            details: isset($data['details']) ? ErrorDetails::fromArray($data['details']) : null,
            failingStepId: $data['failing_step_id'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'message' => $this->message,
            'status' => $this->status,
            'stage' => $this->stage?->value,
            'category' => $this->category?->value,
            'details' => $this->details?->toArray(),
            'failing_step_id' => $this->failingStepId,
        ];
    }
}
