<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * The test run failed. The error message lives on this variant.
 *
 * Carries the same structured ``details`` envelope as workflow runs so
 * consumers can branch on ``error_code`` / ``stage`` rather than parsing
 * a free-text message.
 */
readonly class ErrorWorkflowTestRun implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Human-readable error message */
        public ?string $message = null,
        /** Structured error context including stack trace */
        public ?ErrorDetails $details = null,
        public string $status = 'error',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            message: $data['message'] ?? null,
            details: isset($data['details']) ? ErrorDetails::fromArray($data['details']) : null,
            status: $data['status'] ?? 'error',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'message' => $this->message,
            'details' => $this->details?->toArray(),
            'status' => $this->status,
        ];
    }
}
