<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Detailed error information for debugging.
 *
 * Captures stack traces and context about where and why an error occurred.
 */
readonly class ErrorDetails implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Human-readable error message. Free-text; the structured fields below are the machine-readable counterpart. */
        public ?string $message = null,
        /** Full Python stack trace */
        public ?string $stackTrace = null,
        /** ID of the block that failed */
        public ?string $blockId = null,
        /** Name/label of the block that failed */
        public ?string $blockName = null,
        /** Error code if available */
        public ?string $errorCode = null,
        /**
         * Additional context about the error
         * @var array<string, mixed>|null
         */
        public ?array $context = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            message: $data['message'] ?? null,
            stackTrace: $data['stack_trace'] ?? null,
            blockId: $data['block_id'] ?? null,
            blockName: $data['block_name'] ?? null,
            errorCode: $data['error_code'] ?? null,
            context: $data['context'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'message' => $this->message,
            'stack_trace' => $this->stackTrace,
            'block_id' => $this->blockId,
            'block_name' => $this->blockName,
            'error_code' => $this->errorCode,
            'context' => $this->context,
        ];
    }
}
