<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * The experiment run failed.
 *
 * Carries a human-readable ``message`` and a structured ``details`` envelope
 * consumers can branch on instead of parsing free text.
 */
readonly class ErrorWorkflowExperimentRun implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?string $status = null,
        /** Human-readable error message */
        public ?string $message = null,
        /** Structured error context including stack trace */
        public ?ErrorDetails $details = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            status: $data['status'] ?? null,
            message: $data['message'] ?? null,
            details: isset($data['details']) ? ErrorDetails::fromArray($data['details']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'status' => $this->status,
            'message' => $this->message,
            'details' => $this->details?->toArray(),
        ];
    }
}
