<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Terminal: the executed block raised. ``message`` is the executor's
 * error string.
 */
readonly class ErrorBlockExecutionLifecycle implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Human-readable error message */
        public string $message,
        public ?string $status = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            message: $data['message'],
            status: $data['status'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'message' => $this->message,
            'status' => $this->status,
        ];
    }
}
