<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Terminal: the executed block raised. ``message`` is the executor's
 * error string.
 */
readonly class ErrorBlockExecutionLifecycle implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Human-readable error message */
        public string $message,
        public string $status = 'error',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'message',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ErrorBlockExecutionLifecycle::fromArray()");
            }
        }
        return new self(
            message: $data['message'],
            status: $data['status'] ?? 'error',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'message' => $this->message,
            'status' => $this->status,
        ];
    }
}
