<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Run-scoped per-document experiment result.
 *
 * The storage row is still named ``experiment_jobs`` internally, but the
 * public contract is a result row addressed by ``run_id`` + ``document_id``.
 */
readonly class ExperimentResult implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        public string $runId,
        public string $experimentId,
        public string $documentId,
        public PendingWorkflowExperimentResult|QueuedWorkflowExperimentResult|RunningWorkflowExperimentResult|CompletedWorkflowExperimentResult|ErrorWorkflowExperimentResult|CancelledWorkflowExperimentResult $lifecycle,
        public ExperimentResultTiming $timing,
        public ReviewBlockType $blockType,
        /** @var array<string, \Retab\Resource\JsonHandleInput|\Retab\Resource\FileHandleInput>|null */
        public ?array $handleInputs = null,
        public ?StepArtifactRef $artifact = null,
        public ?int $attempt = null,
        public ?bool $isPlaceholder = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'run_id',
            'experiment_id',
            'document_id',
            'lifecycle',
            'timing',
            'block_type',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ExperimentResult::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            runId: $data['run_id'],
            experimentId: $data['experiment_id'],
            documentId: $data['document_id'],
            lifecycle: match ($data['lifecycle']['status'] ?? null) { 'cancelled' => CancelledWorkflowExperimentResult::fromArray($data['lifecycle']), 'completed' => CompletedWorkflowExperimentResult::fromArray($data['lifecycle']), 'error' => ErrorWorkflowExperimentResult::fromArray($data['lifecycle']), 'pending' => PendingWorkflowExperimentResult::fromArray($data['lifecycle']), 'queued' => QueuedWorkflowExperimentResult::fromArray($data['lifecycle']), 'running' => RunningWorkflowExperimentResult::fromArray($data['lifecycle']), default => throw new \UnexpectedValueException(sprintf('Unknown status: %s', json_encode($data['lifecycle']['status'] ?? null))) },
            timing: ExperimentResultTiming::fromArray($data['timing']),
            blockType: ReviewBlockType::from($data['block_type']),
            handleInputs: $data['handle_inputs'] ?? null,
            artifact: isset($data['artifact']) ? StepArtifactRef::fromArray($data['artifact']) : null,
            attempt: $data['attempt'] ?? null,
            isPlaceholder: $data['is_placeholder'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'run_id' => $this->runId,
            'experiment_id' => $this->experimentId,
            'document_id' => $this->documentId,
            'lifecycle' => $this->lifecycle->toArray(),
            'timing' => $this->timing->toArray(),
            'block_type' => $this->blockType->value,
            'handle_inputs' => $this->handleInputs,
            'artifact' => $this->artifact?->toArray(),
            'attempt' => $this->attempt,
            'is_placeholder' => $this->isPlaceholder,
        ];
    }
}
