<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Run-level summary plus block-specific diagnostics.
 *
 * ``prior_run_id`` + ``prior_score`` populate when the request opts into
 * prior-comparison and a completed prior run exists.
 */
readonly class ExperimentSummaryMetricsResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $experimentId,
        public string $runId,
        public ReviewBlockType $blockType,
        public ?string $kind = null,
        public ?string $view = null,
        public ?string $definitionFingerprint = null,
        public ?float $score = null,
        public ?float $priorScore = null,
        /** @var array<\Retab\Resource\ExperimentSummaryMetricDocument>|null */
        public ?array $documents = null,
        public ExperimentExtractSummaryAggregate|ExperimentConfusionSummaryAggregate|null $aggregate = null,
        public ?string $priorRunId = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            experimentId: $data['experiment_id'],
            runId: $data['run_id'],
            blockType: ReviewBlockType::from($data['block_type']),
            kind: $data['kind'] ?? null,
            view: $data['view'] ?? null,
            definitionFingerprint: $data['definition_fingerprint'] ?? null,
            score: $data['score'] ?? null,
            priorScore: $data['prior_score'] ?? null,
            documents: isset($data['documents']) ? array_map(fn ($item) => ExperimentSummaryMetricDocument::fromArray($item), $data['documents']) : null,
            aggregate: $data['aggregate'] ?? null,
            priorRunId: $data['prior_run_id'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'experiment_id' => $this->experimentId,
            'run_id' => $this->runId,
            'block_type' => $this->blockType->value,
            'kind' => $this->kind,
            'view' => $this->view,
            'definition_fingerprint' => $this->definitionFingerprint,
            'score' => $this->score,
            'prior_score' => $this->priorScore,
            'documents' => $this->documents !== null ? array_map(fn ($item) => $item->toArray(), $this->documents) : null,
            'aggregate' => $this->aggregate?->toArray(),
            'prior_run_id' => $this->priorRunId,
        ];
    }
}
