<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Returned when the latest run's config or document set has drifted
 * from the current draft, so its metrics no longer reflect the
 * experiment's definition.
 */
readonly class ExperimentMetricsStaleError implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $experimentId,
        public MetricsStaleErrorLastRun $lastRun,
        public string $message,
        /** @var array<string>|null */
        public ?array $staleReasons = null,
        public ?string $currentConfigFingerprint = null,
        public string $kind = 'stale_metrics',
        public string $error = 'stale_metrics',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'experiment_id',
            'last_run',
            'message',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ExperimentMetricsStaleError::fromArray()");
            }
        }
        return new self(
            experimentId: $data['experiment_id'],
            lastRun: MetricsStaleErrorLastRun::fromArray($data['last_run']),
            message: $data['message'],
            staleReasons: $data['stale_reasons'] ?? null,
            currentConfigFingerprint: $data['current_config_fingerprint'] ?? null,
            kind: $data['kind'] ?? 'stale_metrics',
            error: $data['error'] ?? 'stale_metrics',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'experiment_id' => $this->experimentId,
            'last_run' => $this->lastRun->toArray(),
            'message' => $this->message,
            'stale_reasons' => $this->staleReasons,
            'current_config_fingerprint' => $this->currentConfigFingerprint,
            'kind' => $this->kind,
            'error' => $this->error,
        ];
    }
}
