<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Document identity for the vote matrix response. */
readonly class ExperimentVotesMetricDocument implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        public string $filename,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'filename',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ExperimentVotesMetricDocument::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            filename: $data['filename'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'filename' => $this->filename,
        ];
    }
}
