<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class ExperimentResultTiming implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?\DateTimeImmutable $createdAt = null,
        public ?\DateTimeImmutable $startedAt = null,
        public ?\DateTimeImmutable $completedAt = null,
        public ?int $durationMs = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            createdAt: isset($data['created_at']) ? new \DateTimeImmutable($data['created_at']) : null,
            startedAt: isset($data['started_at']) ? new \DateTimeImmutable($data['started_at']) : null,
            completedAt: isset($data['completed_at']) ? new \DateTimeImmutable($data['completed_at']) : null,
            durationMs: $data['duration_ms'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'created_at' => $this->createdAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'started_at' => $this->startedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'completed_at' => $this->completedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'duration_ms' => $this->durationMs,
        ];
    }
}
