<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Run-id-first public experiment run shape.
 *
 * The canonical identity is ``id``. Internal queue handles and duplicate
 * identity aliases are intentionally absent.
 */
readonly class ExperimentRun implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        public WorkflowSnapshotRef $workflow,
        public ExperimentRunTrigger $trigger,
        public string $experimentId,
        public string $blockId,
        public ReviewBlockType $blockType,
        public NConsensusValue $nConsensus,
        public PendingWorkflowExperimentRun|QueuedWorkflowExperimentRun|RunningWorkflowExperimentRun|CompletedWorkflowExperimentRun|ErrorWorkflowExperimentRun|CancelledWorkflowExperimentRun $lifecycle,
        public ExperimentRunTiming $timing,
        public string $definitionFingerprint,
        public string $documentsFingerprint,
        public ?string $parentRunId = null,
        public ?float $score = null,
        public ?int $totalDocumentCount = null,
        public ?int $completedDocumentCount = null,
        public ?int $documentCount = null,
        public ?int $errorCount = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            workflow: WorkflowSnapshotRef::fromArray($data['workflow']),
            trigger: ExperimentRunTrigger::fromArray($data['trigger']),
            experimentId: $data['experiment_id'],
            blockId: $data['block_id'],
            blockType: ReviewBlockType::from($data['block_type']),
            nConsensus: NConsensusValue::from($data['n_consensus']),
            lifecycle: match ($data['lifecycle']['status'] ?? null) { 'cancelled' => CancelledWorkflowExperimentRun::fromArray($data['lifecycle']), 'completed' => CompletedWorkflowExperimentRun::fromArray($data['lifecycle']), 'error' => ErrorWorkflowExperimentRun::fromArray($data['lifecycle']), 'pending' => PendingWorkflowExperimentRun::fromArray($data['lifecycle']), 'queued' => QueuedWorkflowExperimentRun::fromArray($data['lifecycle']), 'running' => RunningWorkflowExperimentRun::fromArray($data['lifecycle']), default => throw new \UnexpectedValueException(sprintf('Unknown status: %s', json_encode($data['lifecycle']['status'] ?? null))) },
            timing: ExperimentRunTiming::fromArray($data['timing']),
            definitionFingerprint: $data['definition_fingerprint'],
            documentsFingerprint: $data['documents_fingerprint'],
            parentRunId: $data['parent_run_id'] ?? null,
            score: $data['score'] ?? null,
            totalDocumentCount: $data['total_document_count'] ?? null,
            completedDocumentCount: $data['completed_document_count'] ?? null,
            documentCount: $data['document_count'] ?? null,
            errorCount: $data['error_count'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'workflow' => $this->workflow->toArray(),
            'trigger' => $this->trigger->toArray(),
            'experiment_id' => $this->experimentId,
            'block_id' => $this->blockId,
            'block_type' => $this->blockType->value,
            'n_consensus' => $this->nConsensus->value,
            'lifecycle' => $this->lifecycle->toArray(),
            'timing' => $this->timing->toArray(),
            'definition_fingerprint' => $this->definitionFingerprint,
            'documents_fingerprint' => $this->documentsFingerprint,
            'parent_run_id' => $this->parentRunId,
            'score' => $this->score,
            'total_document_count' => $this->totalDocumentCount,
            'completed_document_count' => $this->completedDocumentCount,
            'document_count' => $this->documentCount,
            'error_count' => $this->errorCount,
        ];
    }
}
