<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Lightweight document row returned by the summary view. */
readonly class ExperimentSummaryMetricDocument implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        public string $filename,
        public ?float $score = null,
        public ?float $priorScore = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'filename',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ExperimentSummaryMetricDocument::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            filename: $data['filename'],
            score: $data['score'] ?? null,
            priorScore: $data['prior_score'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'filename' => $this->filename,
            'score' => $this->score,
            'prior_score' => $this->priorScore,
        ];
    }
}
