<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** One non-diagonal confusion flow between two labels. */
readonly class ExperimentConfusionFlowMetric implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $source,
        public string $target,
        public float $score,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'source',
            'target',
            'score',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ExperimentConfusionFlowMetric::fromArray()");
            }
        }
        return new self(
            source: $data['source'],
            target: $data['target'],
            score: $data['score'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'source' => $this->source,
            'target' => $this->target,
            'score' => $this->score,
        ];
    }
}
