<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Compact target score returned by the per-document metrics view. */
readonly class ExperimentByDocumentTargetMetric implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $path,
        public ?float $score = null,
        public ?float $priorScore = null,
        public mixed $value = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'path',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ExperimentByDocumentTargetMetric::fromArray()");
            }
        }
        return new self(
            path: $data['path'],
            score: $data['score'] ?? null,
            priorScore: $data['prior_score'] ?? null,
            value: $data['value'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'path' => $this->path,
            'score' => $this->score,
            'prior_score' => $this->priorScore,
            'value' => $this->value,
        ];
    }
}
