<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** One target's compact per-document distribution. */
readonly class ExperimentByTargetMetricsResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $runId,
        public string $target,
        public ?string $kind = null,
        public ?string $view = null,
        public ?float $score = null,
        public ?float $priorScore = null,
        public ?ExperimentTargetConfusionMetric $confusion = null,
        /** @var array<\Retab\Resource\ExperimentByTargetDocumentMetric>|null */
        public ?array $documents = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            runId: $data['run_id'],
            target: $data['target'],
            kind: $data['kind'] ?? null,
            view: $data['view'] ?? null,
            score: $data['score'] ?? null,
            priorScore: $data['prior_score'] ?? null,
            confusion: isset($data['confusion']) ? ExperimentTargetConfusionMetric::fromArray($data['confusion']) : null,
            documents: isset($data['documents']) ? array_map(fn ($item) => ExperimentByTargetDocumentMetric::fromArray($item), $data['documents']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'run_id' => $this->runId,
            'target' => $this->target,
            'kind' => $this->kind,
            'view' => $this->view,
            'score' => $this->score,
            'prior_score' => $this->priorScore,
            'confusion' => $this->confusion?->toArray(),
            'documents' => $this->documents !== null ? array_map(fn ($item) => $item->toArray(), $this->documents) : null,
        ];
    }
}
