<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Returned when the experiment has no runs at all. */
readonly class ExperimentMetricsMissingError implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $experimentId,
        public string $message,
        public string $kind = 'no_metrics',
        public string $error = 'no_metrics',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'experiment_id',
            'message',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ExperimentMetricsMissingError::fromArray()");
            }
        }
        return new self(
            experimentId: $data['experiment_id'],
            message: $data['message'],
            kind: $data['kind'] ?? 'no_metrics',
            error: $data['error'] ?? 'no_metrics',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'experiment_id' => $this->experimentId,
            'message' => $this->message,
            'kind' => $this->kind,
            'error' => $this->error,
        ];
    }
}
