<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** One document's compact per-target breakdown. */
readonly class ExperimentByDocumentMetricsResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $runId,
        public ExperimentMetricDocumentRef $document,
        public ?float $score = null,
        public ?float $priorScore = null,
        public ?ExperimentDocumentConfusionMetric $confusion = null,
        /** @var array<\Retab\Resource\ExperimentByDocumentTargetMetric>|null */
        public ?array $targets = null,
        public string $kind = 'by_document',
        public string $view = 'by_document',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'run_id',
            'document',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ExperimentByDocumentMetricsResponse::fromArray()");
            }
        }
        return new self(
            runId: $data['run_id'],
            document: ExperimentMetricDocumentRef::fromArray($data['document']),
            score: $data['score'] ?? null,
            priorScore: $data['prior_score'] ?? null,
            confusion: isset($data['confusion']) ? ExperimentDocumentConfusionMetric::fromArray($data['confusion']) : null,
            targets: isset($data['targets']) ? array_map(fn ($item) => ExperimentByDocumentTargetMetric::fromArray($item), $data['targets']) : null,
            kind: $data['kind'] ?? 'by_document',
            view: $data['view'] ?? 'by_document',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'run_id' => $this->runId,
            'document' => $this->document->toArray(),
            'score' => $this->score,
            'prior_score' => $this->priorScore,
            'confusion' => $this->confusion?->toArray(),
            'targets' => $this->targets !== null ? array_map(fn ($item) => $item->toArray(), $this->targets) : null,
            'kind' => $this->kind,
            'view' => $this->view,
        ];
    }
}
