<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

enum ExperimentRunMetricsView: string
{
    case Summary = 'summary';
    case ByDocument = 'by_document';
    case ByTarget = 'by_target';
    case Votes = 'votes';
}
