<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Capture one experiment document from workflow execution provenance. */
readonly class ExperimentDocumentCaptureRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $workflowRunId,
        public ?string $stepId = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'workflow_run_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ExperimentDocumentCaptureRequest::fromArray()");
            }
        }
        return new self(
            workflowRunId: $data['workflow_run_id'],
            stepId: $data['step_id'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'workflow_run_id' => $this->workflowRunId,
            'step_id' => $this->stepId,
        ];
    }
}
