<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Consensus and flat voter values for one selected target row. */
readonly class ExperimentVoteRow implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public mixed $consensus = null,
        /** @var array<string>|null */
        public ?array $votes = null,
        public ?float $score = null,
        public ?float $rowPresenceScore = null,
        public ?int $presentVoterCount = null,
        public ?int $totalVoterCount = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            consensus: $data['consensus'] ?? null,
            votes: $data['votes'] ?? null,
            score: $data['score'] ?? null,
            rowPresenceScore: $data['row_presence_score'] ?? null,
            presentVoterCount: $data['present_voter_count'] ?? null,
            totalVoterCount: $data['total_voter_count'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'consensus' => $this->consensus,
            'votes' => $this->votes,
            'score' => $this->score,
            'row_presence_score' => $this->rowPresenceScore,
            'present_voter_count' => $this->presentVoterCount,
            'total_voter_count' => $this->totalVoterCount,
        ];
    }
}
