<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Document-local confusion summary for split/classifier blocks. */
readonly class ExperimentDocumentConfusionMetric implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<string, float>|null */
        public ?array $diag = null,
        /** @var array<\Retab\Resource\ExperimentConfusionFlowMetric>|null */
        public ?array $flows = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            diag: $data['diag'] ?? null,
            flows: isset($data['flows']) ? array_map(fn ($item) => ExperimentConfusionFlowMetric::fromArray($item), $data['flows']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'diag' => $this->diag,
            'flows' => $this->flows !== null ? array_map(fn ($item) => $item->toArray(), $this->flows) : null,
        ];
    }
}
