<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class ExplicitExperimentDocumentRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<string, \Retab\Resource\JsonHandleInput|\Retab\Resource\FileHandleInput> */
        public array $handleInputs,
        public ?ExperimentDocumentProvenance $provenance = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'handle_inputs',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ExplicitExperimentDocumentRequest::fromArray()");
            }
        }
        return new self(
            handleInputs: $data['handle_inputs'],
            provenance: isset($data['provenance']) ? ExperimentDocumentProvenance::fromArray($data['provenance']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'handle_inputs' => $this->handleInputs,
            'provenance' => $this->provenance?->toArray(),
        ];
    }
}
