<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class ExtractionWorkflowArtifact implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Unique identifier of the extraction */
        public string $id,
        /** Information about the extracted file */
        public FileRef $file,
        /** Model used for the extraction */
        public string $model,
        /**
         * JSON schema used for the extraction
         * @var array<string, mixed>
         */
        public array $jsonSchema,
        /**
         * The extracted structured data
         * @var array<string, mixed>
         */
        public array $output,
        /** When this artifact was written by the orchestrator. */
        public \DateTimeImmutable $createdAt,
        /** Number of consensus votes used */
        public ?int $nConsensus = null,
        /** DPI used to render document images */
        public ?int $imageResolutionDpi = null,
        /** Free-form instructions supplied with the extraction request. */
        public ?string $instructions = null,
        /** Consensus metadata for multi-vote extraction runs */
        public ?ExtractionConsensus $consensus = null,
        /** @var array<string, string>|null */
        public ?array $metadata = null,
        /** Usage information for the extraction */
        public ?RetabUsage $usage = null,
        /** Artifact operation that determines the backing record type */
        public string $operation = 'extraction',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'file',
            'model',
            'json_schema',
            'output',
            'created_at',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ExtractionWorkflowArtifact::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            file: FileRef::fromArray($data['file']),
            model: $data['model'],
            jsonSchema: $data['json_schema'],
            output: $data['output'],
            createdAt: new \DateTimeImmutable($data['created_at']),
            nConsensus: $data['n_consensus'] ?? null,
            imageResolutionDpi: $data['image_resolution_dpi'] ?? null,
            instructions: $data['instructions'] ?? null,
            consensus: isset($data['consensus']) ? ExtractionConsensus::fromArray($data['consensus']) : null,
            metadata: $data['metadata'] ?? null,
            usage: isset($data['usage']) ? RetabUsage::fromArray($data['usage']) : null,
            operation: $data['operation'] ?? 'extraction',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'file' => $this->file->toArray(),
            'model' => $this->model,
            'json_schema' => $this->jsonSchema,
            'output' => $this->output,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'n_consensus' => $this->nConsensus,
            'image_resolution_dpi' => $this->imageResolutionDpi,
            'instructions' => $this->instructions,
            'consensus' => $this->consensus?->toArray(),
            'metadata' => $this->metadata,
            'usage' => $this->usage?->toArray(),
            'operation' => $this->operation,
        ];
    }
}
