<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** File reference for a handle input. */
readonly class FileHandleInput implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public MaterializedDocument $document,
        public ?string $type = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            document: MaterializedDocument::fromArray($data['document']),
            type: $data['type'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'document' => $this->document->toArray(),
            'type' => $this->type,
        ];
    }
}
