<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Public/shared file reference used across SDK and customer-facing APIs. */
readonly class FileRef implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** ID of the file */
        public string $id,
        /** Filename of the file */
        public string $filename,
        /** MIME type of the file */
        public string $mimeType,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'filename',
            'mime_type',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for FileRef::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            filename: $data['filename'],
            mimeType: $data['mime_type'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'filename' => $this->filename,
            'mime_type' => $this->mimeType,
        ];
    }
}
