<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class FileLink implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The signed URL to download the file */
        public string $downloadUrl,
        /** The expiration time of the signed URL */
        public string $expiresIn,
        /** The name of the file */
        public string $filename,
        /** Durable Retab MIMEData reference for API reuse */
        public ?MimeData $mimeData = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            downloadUrl: $data['download_url'],
            expiresIn: $data['expires_in'],
            filename: $data['filename'],
            mimeData: isset($data['mime_data']) ? MimeData::fromArray($data['mime_data']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'download_url' => $this->downloadUrl,
            'expires_in' => $this->expiresIn,
            'filename' => $this->filename,
            'mime_data' => $this->mimeData?->toArray(),
        ];
    }
}
