<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class File implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The unique identifier of the file */
        public string $id,
        /** The name of the file */
        public string $filename,
        /** When the file was created */
        public \DateTimeImmutable $createdAt,
        /** When the file was last updated */
        public \DateTimeImmutable $updatedAt,
        /** Number of pages in the file */
        public ?int $pageCount = null,
        public string $object = 'file',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'filename',
            'created_at',
            'updated_at',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for File::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            filename: $data['filename'],
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
            pageCount: $data['page_count'] ?? null,
            object: $data['object'] ?? 'file',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'filename' => $this->filename,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'page_count' => $this->pageCount,
            'object' => $this->object,
        ];
    }
}
