<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** File reference for a handle input. */
readonly class FileHandleInput implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public MaterializedDocument $document,
        public string $type = 'file',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'document',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for FileHandleInput::fromArray()");
            }
        }
        return new self(
            document: MaterializedDocument::fromArray($data['document']),
            type: $data['type'] ?? 'file',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'document' => $this->document->toArray(),
            'type' => $this->type,
        ];
    }
}
