<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class FunctionInvocation implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        public string $workflowRunId,
        public string $stepId,
        /** When this artifact was written by the orchestrator. */
        public \DateTimeImmutable $createdAt,
        /** Artifact operation that determines the backing record type */
        public ?string $operation = null,
        /** @var array<string, mixed>|null */
        public ?array $inputs = null,
        public mixed $output = null,
        public ?int $durationMs = null,
        public ?ErrorDetails $error = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            workflowRunId: $data['workflow_run_id'],
            stepId: $data['step_id'],
            createdAt: new \DateTimeImmutable($data['created_at']),
            operation: $data['operation'] ?? null,
            inputs: $data['inputs'] ?? null,
            output: $data['output'] ?? null,
            durationMs: $data['duration_ms'] ?? null,
            error: isset($data['error']) ? ErrorDetails::fromArray($data['error']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'workflow_run_id' => $this->workflowRunId,
            'step_id' => $this->stepId,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'operation' => $this->operation,
            'inputs' => $this->inputs,
            'output' => $this->output,
            'duration_ms' => $this->durationMs,
            'error' => $this->error?->toArray(),
        ];
    }
}
