<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class HttpValidationError implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<\Retab\Resource\ValidationError>|null */
        public ?array $detail = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            detail: isset($data['detail']) ? array_map(fn ($item) => ValidationError::fromArray($item), $data['detail']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'detail' => $this->detail !== null ? array_map(fn ($item) => $item->toArray(), $this->detail) : null,
        ];
    }
}
