<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Core Job object following OpenAI-style specification.
 *
 * Represents a single asynchronous job that can be polled for status
 * and result retrieval.
 */
readonly class Job implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public JobsEndpoint $endpoint,
        public ?string $id = null,
        public ?string $object = null,
        public ?JobStatus $status = null,
        public ?JobError $error = null,
        /** @var array<\Retab\Resource\JobWarning>|null */
        public ?array $warnings = null,
        public ?string $createdAt = null,
        public ?string $startedAt = null,
        public ?string $completedAt = null,
        public ?string $expiresAt = null,
        /** @var array<string, string>|null */
        public ?array $metadata = null,
        public ?bool $cancelled = null,
        public ?int $attemptCount = null,
        public ?string $lastAttemptAt = null,
        public ?string $lastFailureCode = null,
        /** @var array<string, mixed>|null */
        public ?array $request = null,
        public ?JobResponse $response = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            endpoint: JobsEndpoint::from($data['endpoint']),
            id: $data['id'] ?? null,
            object: $data['object'] ?? null,
            status: isset($data['status']) ? JobStatus::from($data['status']) : null,
            error: isset($data['error']) ? JobError::fromArray($data['error']) : null,
            warnings: isset($data['warnings']) ? array_map(fn ($item) => JobWarning::fromArray($item), $data['warnings']) : null,
            createdAt: $data['created_at'] ?? null,
            startedAt: $data['started_at'] ?? null,
            completedAt: $data['completed_at'] ?? null,
            expiresAt: $data['expires_at'] ?? null,
            metadata: $data['metadata'] ?? null,
            cancelled: $data['cancelled'] ?? null,
            attemptCount: $data['attempt_count'] ?? null,
            lastAttemptAt: $data['last_attempt_at'] ?? null,
            lastFailureCode: $data['last_failure_code'] ?? null,
            request: $data['request'] ?? null,
            response: isset($data['response']) ? JobResponse::fromArray($data['response']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'endpoint' => $this->endpoint->value,
            'id' => $this->id,
            'object' => $this->object,
            'status' => $this->status?->value,
            'error' => $this->error?->toArray(),
            'warnings' => $this->warnings !== null ? array_map(fn ($item) => $item->toArray(), $this->warnings) : null,
            'created_at' => $this->createdAt,
            'started_at' => $this->startedAt,
            'completed_at' => $this->completedAt,
            'expires_at' => $this->expiresAt,
            'metadata' => $this->metadata,
            'cancelled' => $this->cancelled,
            'attempt_count' => $this->attemptCount,
            'last_attempt_at' => $this->lastAttemptAt,
            'last_failure_code' => $this->lastFailureCode,
            'request' => $this->request,
            'response' => $this->response?->toArray(),
        ];
    }
}
