<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Public response returned when job completes successfully. */
readonly class JobResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public int $statusCode,
        /** @var array<string, mixed> */
        public array $body,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'status_code',
            'body',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for JobResponse::fromArray()");
            }
        }
        return new self(
            statusCode: $data['status_code'],
            body: $data['body'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'status_code' => $this->statusCode,
            'body' => $this->body,
        ];
    }
}
