<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

enum JobsEndpoint: string
{
    case V1Extractions = '/v1/extractions';
    case V1Parses = '/v1/parses';
    case V1Splits = '/v1/splits';
    case V1Partitions = '/v1/partitions';
    case V1Classifications = '/v1/classifications';
    case V1SchemasGenerate = '/v1/schemas/generate';
    case V1Edits = '/v1/edits';
    case V1EditsTemplatesGenerate = '/v1/edits/templates/generate';
    case V1EvalsExtractProcess = '/v1/evals/extract/process';
    case V1EvalsExtractExtract = '/v1/evals/extract/extract';
    case V1EvalsExtractSplit = '/v1/evals/extract/split';
}
