<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class JsonSchemaValidCondition implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?string $kind = null,
        /** @var array<string, mixed>|null */
        public ?array $schema = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            kind: $data['kind'] ?? null,
            schema: $data['schema'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'kind' => $this->kind,
            'schema' => $this->schema,
        ];
    }
}
