<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class JsonSchemaValidCondition implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<string, mixed>|null */
        public ?array $schema = null,
        public string $kind = 'json_schema_valid',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            schema: $data['schema'] ?? null,
            kind: $data['kind'] ?? 'json_schema_valid',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'schema' => $this->schema,
            'kind' => $this->kind,
        ];
    }
}
