<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** JSON payload for a handle input. ``data`` is the raw JSON value. */
readonly class JsonHandleInput implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public mixed $data = null,
        public string $type = 'json',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            data: $data['data'] ?? null,
            type: $data['type'] ?? 'json',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'data' => $this->data,
            'type' => $this->type,
        ];
    }
}
