<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Summary of the most recent block-test run.
 *
 * The two harmonized axes — execution status and verdict outcome — are
 * exposed as separate fields. The runner only writes the summary on
 * terminal-state transitions, so in practice ``status`` is one of
 * ``completed | error | cancelled`` and ``outcome`` is populated when
 * ``status == "completed"``.
 *
 * ``status`` is a flat enum — there's no per-state payload to carry on a
 * summary projection, so the API_DESIGN.md ``lifecycle`` vs ``status``
 * convention says use ``status`` here.
 */
readonly class LatestBlockTestRunSummary implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $runRecordId,
        public WorkflowExperimentsStatus $status,
        public \DateTimeImmutable $startedAt,
        public ?AssertionOutcome $outcome = null,
        public ?\DateTimeImmutable $completedAt = null,
        public ?int $durationMs = null,
        public ?string $workflowDraftFingerprint = null,
        public ?string $blockConfigFingerprint = null,
        public ?int $assertionsPassed = null,
        public ?int $assertionsFailed = null,
        public ?int $blockedAssertions = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'run_record_id',
            'status',
            'started_at',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for LatestBlockTestRunSummary::fromArray()");
            }
        }
        return new self(
            runRecordId: $data['run_record_id'],
            status: WorkflowExperimentsStatus::from($data['status']),
            startedAt: new \DateTimeImmutable($data['started_at']),
            outcome: isset($data['outcome']) ? AssertionOutcome::from($data['outcome']) : null,
            completedAt: isset($data['completed_at']) ? new \DateTimeImmutable($data['completed_at']) : null,
            durationMs: $data['duration_ms'] ?? null,
            workflowDraftFingerprint: $data['workflow_draft_fingerprint'] ?? null,
            blockConfigFingerprint: $data['block_config_fingerprint'] ?? null,
            assertionsPassed: $data['assertions_passed'] ?? null,
            assertionsFailed: $data['assertions_failed'] ?? null,
            blockedAssertions: $data['blocked_assertions'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'run_record_id' => $this->runRecordId,
            'status' => $this->status->value,
            'started_at' => $this->startedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'outcome' => $this->outcome?->value,
            'completed_at' => $this->completedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'duration_ms' => $this->durationMs,
            'workflow_draft_fingerprint' => $this->workflowDraftFingerprint,
            'block_config_fingerprint' => $this->blockConfigFingerprint,
            'assertions_passed' => $this->assertionsPassed,
            'assertions_failed' => $this->assertionsFailed,
            'blocked_assertions' => $this->blockedAssertions,
        ];
    }
}
