<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class LengthCompareCondition implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public LengthCompareConditionOp $op,
        public int $expected,
        public ?string $kind = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            op: LengthCompareConditionOp::from($data['op']),
            expected: $data['expected'],
            kind: $data['kind'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'op' => $this->op->value,
            'expected' => $this->expected,
            'kind' => $this->kind,
        ];
    }
}
