<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class LlmJudgedAsCondition implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $rubric,
        public ?string $kind = null,
        public ?string $expectedLabel = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            rubric: $data['rubric'],
            kind: $data['kind'] ?? null,
            expectedLabel: $data['expected_label'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'rubric' => $this->rubric,
            'kind' => $this->kind,
            'expected_label' => $this->expectedLabel,
        ];
    }
}
