<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class ManualWorkflowTestSource implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<string, \Retab\Resource\JsonHandleInput|\Retab\Resource\FileHandleInput>|null */
        public ?array $handleInputs = null,
        public string $type = 'manual',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            handleInputs: $data['handle_inputs'] ?? null,
            type: $data['type'] ?? 'manual',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'handle_inputs' => $this->handleInputs,
            'type' => $this->type,
        ];
    }
}
