<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class ManualWorkflowTestSource implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?string $type = null,
        /** @var array<string, \Retab\Resource\JsonHandleInput|\Retab\Resource\FileHandleInput>|null */
        public ?array $handleInputs = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            type: $data['type'] ?? null,
            handleInputs: $data['handle_inputs'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'type' => $this->type,
            'handle_inputs' => $this->handleInputs,
        ];
    }
}
