<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class MatcheRegexCondition implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $pattern,
        public ?string $kind = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            pattern: $data['pattern'],
            kind: $data['kind'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'pattern' => $this->pattern,
            'kind' => $this->kind,
        ];
    }
}
