<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class MatcheRegexCondition implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $pattern,
        public string $kind = 'matches_regex',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'pattern',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for MatcheRegexCondition::fromArray()");
            }
        }
        return new self(
            pattern: $data['pattern'],
            kind: $data['kind'] ?? 'matches_regex',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'pattern' => $this->pattern,
            'kind' => $this->kind,
        ];
    }
}
