<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class MaterializedDocument implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $originalId,
        public string $filename,
        public string $mimeType,
        public string $gcsUri,
        public ?int $sizeBytes = null,
        public ?string $contentFingerprint = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            originalId: $data['original_id'],
            filename: $data['filename'],
            mimeType: $data['mime_type'],
            gcsUri: $data['gcs_uri'],
            sizeBytes: $data['size_bytes'] ?? null,
            contentFingerprint: $data['content_fingerprint'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'original_id' => $this->originalId,
            'filename' => $this->filename,
            'mime_type' => $this->mimeType,
            'gcs_uri' => $this->gcsUri,
            'size_bytes' => $this->sizeBytes,
            'content_fingerprint' => $this->contentFingerprint,
        ];
    }
}
