<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class MetricsStaleErrorLastRun implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $runId,
        public ?string $definitionFingerprint = null,
        public ?float $score = null,
        public ?\DateTimeImmutable $createdAt = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            runId: $data['run_id'],
            definitionFingerprint: $data['definition_fingerprint'] ?? null,
            score: $data['score'] ?? null,
            createdAt: isset($data['created_at']) ? new \DateTimeImmutable($data['created_at']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'run_id' => $this->runId,
            'definition_fingerprint' => $this->definitionFingerprint,
            'score' => $this->score,
            'created_at' => $this->createdAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
