<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

enum NConsensusValue: int
{
    case Value3 = 3;
    case Value5 = 5;
    case Value7 = 7;
}
