<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class NumberCompareCondition implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public LengthCompareConditionOp $op,
        public int|float $expected,
        public string $kind = 'number_compare',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'op',
            'expected',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for NumberCompareCondition::fromArray()");
            }
        }
        return new self(
            op: LengthCompareConditionOp::from($data['op']),
            expected: $data['expected'],
            kind: $data['kind'] ?? 'number_compare',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'op' => $this->op->value,
            'expected' => $this->expected,
            'kind' => $this->kind,
        ];
    }
}
