<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Structured block-test assertion target. */
readonly class OutputTarget implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $outputHandleId,
        public ?string $path = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            outputHandleId: $data['output_handle_id'],
            path: $data['path'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'output_handle_id' => $this->outputHandleId,
            'path' => $this->path,
        ];
    }
}
