<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Public create-parse request body. */
readonly class ParseRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The document to parse */
        public MimeData|FileRef $document,
        /** The model to use for parsing */
        public ?string $model = null,
        /** Format used to render tables extracted from the document */
        public ?TableParsingFormat $tableParsingFormat = null,
        /** DPI used when rasterizing pages for the parser */
        public ?int $imageResolutionDpi = null,
        /** Free-form instructions appended to the system prompt to steer the parse. */
        public ?string $instructions = null,
        /** If true, skip the LLM cache and force a fresh completion */
        public ?bool $bustCache = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            document: $data['document'],
            model: $data['model'] ?? null,
            tableParsingFormat: isset($data['table_parsing_format']) ? TableParsingFormat::from($data['table_parsing_format']) : null,
            imageResolutionDpi: $data['image_resolution_dpi'] ?? null,
            instructions: $data['instructions'] ?? null,
            bustCache: $data['bust_cache'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'document' => $this->document->toArray(),
            'model' => $this->model,
            'table_parsing_format' => $this->tableParsingFormat?->value,
            'image_resolution_dpi' => $this->imageResolutionDpi,
            'instructions' => $this->instructions,
            'bust_cache' => $this->bustCache,
        ];
    }
}
