<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class Parse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Unique identifier of the parse */
        public string $id,
        /** Information about the parsed file */
        public FileRef $file,
        /** Model used for parsing */
        public string $model,
        /** Format used to render tables extracted from the document */
        public TableParsingFormat $tableParsingFormat,
        /** DPI used when rasterizing pages for the parser */
        public int $imageResolutionDpi,
        /** The parsed document content */
        public ParseOutput $output,
        /** Free-form instructions supplied with the parse request. */
        public ?string $instructions = null,
        /** Usage information for the parse operation */
        public ?RetabUsage $usage = null,
        public ?\DateTimeImmutable $createdAt = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            file: FileRef::fromArray($data['file']),
            model: $data['model'],
            tableParsingFormat: TableParsingFormat::from($data['table_parsing_format']),
            imageResolutionDpi: $data['image_resolution_dpi'],
            output: ParseOutput::fromArray($data['output']),
            instructions: $data['instructions'] ?? null,
            usage: isset($data['usage']) ? RetabUsage::fromArray($data['usage']) : null,
            createdAt: isset($data['created_at']) ? new \DateTimeImmutable($data['created_at']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'file' => $this->file->toArray(),
            'model' => $this->model,
            'table_parsing_format' => $this->tableParsingFormat->value,
            'image_resolution_dpi' => $this->imageResolutionDpi,
            'output' => $this->output->toArray(),
            'instructions' => $this->instructions,
            'usage' => $this->usage?->toArray(),
            'created_at' => $this->createdAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
