<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class PartitionConsensus implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /**
         * Alternative partition vote outputs used to build the consolidated result.
         * @var array<array<\Retab\Resource\PartitionChunk>>|null
         */
        public ?array $choices = null,
        /**
         * Consensus likelihoods aligned with the partition output.
         * @var array<\Retab\Resource\PartitionChunkLikelihood>|null
         */
        public ?array $likelihoods = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            choices: isset($data['choices']) ? $data['choices'] : null,
            likelihoods: isset($data['likelihoods']) ? array_map(fn ($item) => PartitionChunkLikelihood::fromArray($item), $data['likelihoods']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'choices' => $this->choices,
            'likelihoods' => $this->likelihoods !== null ? array_map(fn ($item) => $item->toArray(), $this->likelihoods) : null,
        ];
    }
}
