<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Public create-partition request body. */
readonly class PartitionRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The document to partition */
        public MimeData|FileRef $document,
        /** The key to partition the document by */
        public string $key,
        /** Instructions describing how the document should be partitioned */
        public string $instructions,
        /** The model to use for partitioning */
        public ?string $model = null,
        /** Number of partitioning runs to use for consensus voting. Uses deterministic single-pass when set to 1. */
        public ?int $nConsensus = null,
        /** If true, allow a page to appear in more than one partition chunk */
        public ?bool $allowOverlap = null,
        /** If true, skip the LLM cache and force a fresh completion */
        public ?bool $bustCache = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            document: $data['document'],
            key: $data['key'],
            instructions: $data['instructions'],
            model: $data['model'] ?? null,
            nConsensus: $data['n_consensus'] ?? null,
            allowOverlap: $data['allow_overlap'] ?? null,
            bustCache: $data['bust_cache'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'document' => $this->document->toArray(),
            'key' => $this->key,
            'instructions' => $this->instructions,
            'model' => $this->model,
            'n_consensus' => $this->nConsensus,
            'allow_overlap' => $this->allowOverlap,
            'bust_cache' => $this->bustCache,
        ];
    }
}
