<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class PartitionChunkLikelihood implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Confidence that this partition key value is correct */
        public ?float $key = null,
        /**
         * Confidence for each page in the corresponding partition chunk.pages array
         * @var array<float>|null
         */
        public ?array $pages = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            key: $data['key'] ?? null,
            pages: $data['pages'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'key' => $this->key,
            'pages' => $this->pages,
        ];
    }
}
