<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** The experiment run is enqueued and waiting for a worker. */
readonly class QueuedWorkflowExperimentRun implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $status = 'queued',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            status: $data['status'] ?? 'queued',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'status' => $this->status,
        ];
    }
}
