<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Run created by restarting a parent run. */
readonly class RestartTrigger implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** ID of the parent run that was restarted */
        public string $parentRunId,
        public ?string $type = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            parentRunId: $data['parent_run_id'],
            type: $data['type'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'parent_run_id' => $this->parentRunId,
            'type' => $this->type,
        ];
    }
}
