<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

enum ResumeStatus: string
{
    case Resumed = 'resumed';
    case Pending = 'pending';
    case Skipped = 'skipped';
}
