<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Usage information for document processing. */
readonly class RetabUsage implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Credits consumed for processing */
        public float $credits,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'credits',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RetabUsage::fromArray()");
            }
        }
        return new self(
            credits: $data['credits'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'credits' => $this->credits,
        ];
    }
}
