<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Gate when a conditional-block-style JSON condition matches.
 *
 * The `condition` payload uses the same shape as workflow conditional blocks:
 * one condition group with `sub_conditions` and a `logical_operator`. Paths are
 * evaluated against a review condition root, for example `data.invoice_total`
 * or `likelihoods.invoice_total`.
 */
readonly class ReviewJsonCondition implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /**
         * Conditional-block Condition payload.
         * @var array<string, mixed>
         */
        public array $condition,
        public string $kind = 'json_condition',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'condition',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ReviewJsonCondition::fromArray()");
            }
        }
        return new self(
            condition: $data['condition'],
            kind: $data['kind'] ?? 'json_condition',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'condition' => $this->condition,
            'kind' => $this->kind,
        ];
    }
}
