<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class ReviewEvaluation implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        public string $workflowRunId,
        public string $stepId,
        /** When this artifact was written by the orchestrator. */
        public \DateTimeImmutable $createdAt,
        /** @var array<\Retab\Resource\ConditionEvaluationResult>|null */
        public ?array $evaluations = null,
        /** @var array<string>|null */
        public ?array $selectedHandles = null,
        public ?string $matchedBranchId = null,
        /** @var array<string>|null */
        public ?array $matchedConditionIds = null,
        public ?bool $requiresHumanReview = null,
        public ?string $reviewerId = null,
        public ?ReviewVerdict $reviewDecision = null,
        public ?string $reviewNotes = null,
        public ?bool $requestedRevision = null,
        public ?\DateTimeImmutable $reviewedAt = null,
        /** Artifact operation that determines the backing record type */
        public string $operation = 'review_trigger_evaluation',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'workflow_run_id',
            'step_id',
            'created_at',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ReviewEvaluation::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            workflowRunId: $data['workflow_run_id'],
            stepId: $data['step_id'],
            createdAt: new \DateTimeImmutable($data['created_at']),
            evaluations: isset($data['evaluations']) ? array_map(fn ($item) => ConditionEvaluationResult::fromArray($item), $data['evaluations']) : null,
            selectedHandles: $data['selected_handles'] ?? null,
            matchedBranchId: $data['matched_branch_id'] ?? null,
            matchedConditionIds: $data['matched_condition_ids'] ?? null,
            requiresHumanReview: $data['requires_human_review'] ?? null,
            reviewerId: $data['reviewer_id'] ?? null,
            reviewDecision: isset($data['review_decision']) ? ReviewVerdict::from($data['review_decision']) : null,
            reviewNotes: $data['review_notes'] ?? null,
            requestedRevision: $data['requested_revision'] ?? null,
            reviewedAt: isset($data['reviewed_at']) ? new \DateTimeImmutable($data['reviewed_at']) : null,
            operation: $data['operation'] ?? 'review_trigger_evaluation',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'workflow_run_id' => $this->workflowRunId,
            'step_id' => $this->stepId,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'evaluations' => $this->evaluations !== null ? array_map(fn ($item) => $item->toArray(), $this->evaluations) : null,
            'selected_handles' => $this->selectedHandles,
            'matched_branch_id' => $this->matchedBranchId,
            'matched_condition_ids' => $this->matchedConditionIds,
            'requires_human_review' => $this->requiresHumanReview,
            'reviewer_id' => $this->reviewerId,
            'review_decision' => $this->reviewDecision?->value,
            'review_notes' => $this->reviewNotes,
            'requested_revision' => $this->requestedRevision,
            'reviewed_at' => $this->reviewedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'operation' => $this->operation,
        ];
    }
}
