<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Gate when any resulting split has fewer than `min_pages` pages. */
readonly class ReviewAnySplitPagesLt implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public int $minPages,
        public string $kind = 'any_split_pages_lt',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'min_pages',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ReviewAnySplitPagesLt::fromArray()");
            }
        }
        return new self(
            minPages: $data['min_pages'],
            kind: $data['kind'] ?? 'any_split_pages_lt',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'min_pages' => $this->minPages,
            'kind' => $this->kind,
        ];
    }
}
