<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Gate if the block output fails its declared schema validation. */
readonly class ReviewValidationFailed implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $kind = 'validation_failed',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            kind: $data['kind'] ?? 'validation_failed',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'kind' => $this->kind,
        ];
    }
}
