<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Gate when (top1_prob - top2_prob) < `margin` — model was torn. */
readonly class ReviewTopMarginLt implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public float $margin,
        public ?string $kind = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            margin: $data['margin'],
            kind: $data['kind'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'margin' => $this->margin,
            'kind' => $this->kind,
        ];
    }
}
