<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Gate when the predicted category is in `categories` (e.g., review fraud alerts). */
readonly class ReviewCategoryIn implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<string> */
        public array $categories,
        public ?string $kind = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            categories: $data['categories'],
            kind: $data['kind'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'categories' => $this->categories,
            'kind' => $this->kind,
        ];
    }
}
