<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Gate when any split boundary's confidence is below `threshold`. */
readonly class ReviewBoundaryConfidenceLt implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public float $threshold,
        public ?string $kind = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            threshold: $data['threshold'],
            kind: $data['kind'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'threshold' => $this->threshold,
            'kind' => $this->kind,
        ];
    }
}
