<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Gate when any required field in the extract schema is null/missing.
 *
 * First-class predicate because this is the most common real-world driver
 * for structured-extraction review.
 */
readonly class ReviewAnyRequiredFieldNull implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $kind = 'any_required_field_null',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            kind: $data['kind'] ?? 'any_required_field_null',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'kind' => $this->kind,
        ];
    }
}
