<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Gate when the field at `path` has confidence below `threshold`. */
readonly class ReviewFieldConfidenceLt implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** JSONPath-style path, e.g. '$.invoice.total' or 'invoice.total' */
        public string $path,
        public float $threshold,
        public string $kind = 'field_confidence_lt',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'path',
            'threshold',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ReviewFieldConfidenceLt::fromArray()");
            }
        }
        return new self(
            path: $data['path'],
            threshold: $data['threshold'],
            kind: $data['kind'] ?? 'field_confidence_lt',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'path' => $this->path,
            'threshold' => $this->threshold,
            'kind' => $this->kind,
        ];
    }
}
