<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Gate when a conditional-style result chose a branch in `branches`.
 *
 * Conditional blocks are intentionally not reviewable. The predicate remains in
 * the global union so old review/evaluator payloads can still be parsed.
 */
readonly class ReviewBranchIn implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<string> */
        public array $branches,
        public ?string $kind = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            branches: $data['branches'],
            kind: $data['kind'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'branches' => $this->branches,
            'kind' => $this->kind,
        ];
    }
}
