<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Gate when any split boundary's confidence is below `threshold`. */
readonly class ReviewBoundaryConfidenceLt implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public float $threshold,
        public string $kind = 'boundary_confidence_lt',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'threshold',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ReviewBoundaryConfidenceLt::fromArray()");
            }
        }
        return new self(
            threshold: $data['threshold'],
            kind: $data['kind'] ?? 'boundary_confidence_lt',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'threshold' => $this->threshold,
            'kind' => $this->kind,
        ];
    }
}
