<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Gate when any resulting split has fewer than `min_pages` pages. */
readonly class ReviewAnySplitPagesLt implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public int $minPages,
        public ?string $kind = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            minPages: $data['min_pages'],
            kind: $data['kind'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'min_pages' => $this->minPages,
            'kind' => $this->kind,
        ];
    }
}
