<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Gate fires if ANY child predicate fires. Evaluated in list order;
 * `triggered_by` reports the first match (decision: first-match wins).
 */
readonly class ReviewAnyOf implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<\Retab\Resource\ReviewAlways|\Retab\Resource\ReviewValidationFailed|\Retab\Resource\ReviewConfidenceLt|\Retab\Resource\ReviewCategoryIn|\Retab\Resource\ReviewTopMarginLt|\Retab\Resource\ReviewSplitCountNeq|\Retab\Resource\ReviewAnySplitPagesLt|\Retab\Resource\ReviewBoundaryConfidenceLt|\Retab\Resource\ReviewAnyRequiredFieldNull|\Retab\Resource\ReviewFieldConfidenceLt|\Retab\Resource\ReviewJsonCondition|\Retab\Resource\ReviewBranchIn|\Retab\Resource\ReviewAnyOf|\Retab\Resource\ReviewAllOf> */
        public array $predicates,
        public string $kind = 'any_of',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'predicates',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ReviewAnyOf::fromArray()");
            }
        }
        return new self(
            predicates: $data['predicates'],
            kind: $data['kind'] ?? 'any_of',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'predicates' => $this->predicates,
            'kind' => $this->kind,
        ];
    }
}
