<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class RunStepWorkflowTestSource implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $runId,
        public ?string $type = null,
        public ?string $stepId = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            runId: $data['run_id'],
            type: $data['type'] ?? null,
            stepId: $data['step_id'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'run_id' => $this->runId,
            'type' => $this->type,
            'step_id' => $this->stepId,
        ];
    }
}
