<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * All timing information for a run.
 *
 * ``duration_ms`` is backfilled at read time from
 * ``completed_at - started_at`` when both timestamps are present and the
 * stored value is ``None``. The field is ``init=False`` so producers cannot
 * pass it through ``__init__`` — they must round-trip through
 * ``model_validate`` (or persist via the Mongo projection helpers in
 * ``run_duration.py``). Records that already store ``duration_ms`` are left
 * untouched (idempotent), so backfill cannot drift from the canonical value
 * written by the projection.
 */
readonly class RunTiming implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** When the run record was created */
        public ?\DateTimeImmutable $createdAt = null,
        /** When the run started executing */
        public ?\DateTimeImmutable $startedAt = null,
        /** When the run finished executing */
        public ?\DateTimeImmutable $completedAt = null,
        /** When the current awaiting_review period started */
        public ?\DateTimeImmutable $reviewWaitingStartedAt = null,
        /** Accumulated time spent waiting for review across the run */
        public ?int $accumulatedReviewWaitingMs = null,
        /** Total run duration in milliseconds. Backfilled from ``completed_at - started_at`` on read when not stored. */
        public ?int $durationMs = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            createdAt: isset($data['created_at']) ? new \DateTimeImmutable($data['created_at']) : null,
            startedAt: isset($data['started_at']) ? new \DateTimeImmutable($data['started_at']) : null,
            completedAt: isset($data['completed_at']) ? new \DateTimeImmutable($data['completed_at']) : null,
            reviewWaitingStartedAt: isset($data['review_waiting_started_at']) ? new \DateTimeImmutable($data['review_waiting_started_at']) : null,
            accumulatedReviewWaitingMs: $data['accumulated_review_waiting_ms'] ?? null,
            durationMs: $data['duration_ms'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'created_at' => $this->createdAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'started_at' => $this->startedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'completed_at' => $this->completedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'review_waiting_started_at' => $this->reviewWaitingStartedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'accumulated_review_waiting_ms' => $this->accumulatedReviewWaitingMs,
            'duration_ms' => $this->durationMs,
        ];
    }
}
