<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Run started by a workflow schedule. */
readonly class ScheduleTrigger implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** ID of the schedule that fired this run */
        public string $scheduleId,
        public ?string $type = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            scheduleId: $data['schedule_id'],
            type: $data['type'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'schedule_id' => $this->scheduleId,
            'type' => $this->type,
        ];
    }
}
