<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

enum SimilarityGteConditionMethod: string
{
    case Levenshtein = 'levenshtein';
    case Embeddings = 'embeddings';
}
