<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Terminal: the block declared its inputs unsatisfied via
 * ``should_skip_block`` and was skipped. ``reason`` is the skip rationale
 * surfaced by the block's input requirements registry.
 */
readonly class SkippedBlockExecutionLifecycle implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Reason the block was skipped */
        public string $reason,
        public string $status = 'skipped',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'reason',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SkippedBlockExecutionLifecycle::fromArray()");
            }
        }
        return new self(
            reason: $data['reason'],
            status: $data['status'] ?? 'skipped',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'reason' => $this->reason,
            'status' => $this->status,
        ];
    }
}
