<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class SourcesResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** ID of the extraction */
        public string $extractionId,
        /** Detected document type of the source file */
        public SourcesResponseDocumentType $documentType,
        /** File metadata (id, filename, mime_type) */
        public FileRef $file,
        /**
         * Original extraction output
         * @var array<string, mixed>
         */
        public array $extraction,
        /**
         * Same shape as extraction but leaves are {value, source} objects
         * @var array<string, mixed>
         */
        public array $sources,
        public string $object = 'extraction.sources',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'extraction_id',
            'document_type',
            'file',
            'extraction',
            'sources',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SourcesResponse::fromArray()");
            }
        }
        return new self(
            extractionId: $data['extraction_id'],
            documentType: SourcesResponseDocumentType::from($data['document_type']),
            file: FileRef::fromArray($data['file']),
            extraction: $data['extraction'],
            sources: $data['sources'],
            object: $data['object'] ?? 'extraction.sources',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'extraction_id' => $this->extractionId,
            'document_type' => $this->documentType->value,
            'file' => $this->file->toArray(),
            'extraction' => $this->extraction,
            'sources' => $this->sources,
            'object' => $this->object,
        ];
    }
}
