<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

enum SourcesResponseDocumentType: string
{
    case Pdf = 'pdf';
    case Image = 'image';
    case Csv = 'csv';
    case Xlsx = 'xlsx';
    case Docx = 'docx';
    case Txt = 'txt';
}
