<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class SplitSubdocumentLikelihood implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Confidence that this split label is correct */
        public ?float $name = null,
        /**
         * Confidence for each page in the corresponding split.pages array
         * @var array<float>|null
         */
        public ?array $pages = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            name: $data['name'] ?? null,
            pages: $data['pages'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'name' => $this->name,
            'pages' => $this->pages,
        ];
    }
}
