<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Canonical split request. */
readonly class SplitRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The document to split */
        public MimeData|FileRef $document,
        /**
         * The subdocuments to split the document into
         * @var array<\Retab\Resource\Subdocument>
         */
        public array $subdocuments,
        /** The model to use to split the document */
        public ?string $model = null,
        /** Free-form instructions appended to the system prompt to steer the split. */
        public ?string $instructions = null,
        /** Number of consensus split runs to perform. Uses deterministic single-pass when set to 1. */
        public ?int $nConsensus = null,
        /** If true, skip the LLM cache and force a fresh completion */
        public ?bool $bustCache = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'document',
            'subdocuments',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SplitRequest::fromArray()");
            }
        }
        return new self(
            document: $data['document'],
            subdocuments: array_map(fn ($item) => Subdocument::fromArray($item), $data['subdocuments']),
            model: $data['model'] ?? null,
            instructions: $data['instructions'] ?? null,
            nConsensus: $data['n_consensus'] ?? null,
            bustCache: $data['bust_cache'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'document' => $this->document->toArray(),
            'subdocuments' => array_map(fn ($item) => $item->toArray(), $this->subdocuments),
            'model' => $this->model,
            'instructions' => $this->instructions,
            'n_consensus' => $this->nConsensus,
            'bust_cache' => $this->bustCache,
        ];
    }
}
