<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class Split implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Unique identifier of the split result */
        public string $id,
        /** Information about the split file */
        public FileRef $file,
        /** Model used for the split operation */
        public string $model,
        /**
         * Subdocuments used for the split operation
         * @var array<\Retab\Resource\Subdocument>
         */
        public array $subdocuments,
        /**
         * The list of document splits with their assigned pages
         * @var array<\Retab\Resource\SplitResult>
         */
        public array $output,
        /** Number of consensus votes used */
        public ?int $nConsensus = null,
        /** Free-form instructions supplied with the split request. */
        public ?string $instructions = null,
        /** Consensus metadata for multi-vote split runs */
        public ?SplitConsensus $consensus = null,
        /** Usage information for the split operation */
        public ?RetabUsage $usage = null,
        public ?\DateTimeImmutable $createdAt = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'file',
            'model',
            'subdocuments',
            'output',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for Split::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            file: FileRef::fromArray($data['file']),
            model: $data['model'],
            subdocuments: array_map(fn ($item) => Subdocument::fromArray($item), $data['subdocuments']),
            output: array_map(fn ($item) => SplitResult::fromArray($item), $data['output']),
            nConsensus: $data['n_consensus'] ?? null,
            instructions: $data['instructions'] ?? null,
            consensus: isset($data['consensus']) ? SplitConsensus::fromArray($data['consensus']) : null,
            usage: isset($data['usage']) ? RetabUsage::fromArray($data['usage']) : null,
            createdAt: isset($data['created_at']) ? new \DateTimeImmutable($data['created_at']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'file' => $this->file->toArray(),
            'model' => $this->model,
            'subdocuments' => array_map(fn ($item) => $item->toArray(), $this->subdocuments),
            'output' => array_map(fn ($item) => $item->toArray(), $this->output),
            'n_consensus' => $this->nConsensus,
            'instructions' => $this->instructions,
            'consensus' => $this->consensus?->toArray(),
            'usage' => $this->usage?->toArray(),
            'created_at' => $this->createdAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
