<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Intersection-over-Union for split page assignments.
 *
 * ``expected`` is stored in the canonical split-eval payload shape:
 * ``{"splits": [{"name", "pages"}]}``
 */
readonly class SplitIouCondition implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<string, mixed> */
        public array $expected,
        public ?float $threshold = null,
        public string $kind = 'split_iou_gte',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'expected',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SplitIouCondition::fromArray()");
            }
        }
        return new self(
            expected: $data['expected'],
            threshold: $data['threshold'] ?? null,
            kind: $data['kind'] ?? 'split_iou_gte',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'expected' => $this->expected,
            'threshold' => $this->threshold,
            'kind' => $this->kind,
        ];
    }
}
