<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Canonical persisted resource produced by a workflow step.
 *
 * Uniformly a `(operation, id)` ref into a backing collection. The artifact
 * itself carries no payload — consumers dispatch on ``operation`` and fetch
 * the backing record by ``id``.
 */
readonly class StepArtifactRef implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Persisted resource operation; identifies the backing collection */
        public StepArtifactRefOperation $operation,
        /** Persisted resource identifier */
        public string $id,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            operation: StepArtifactRefOperation::from($data['operation']),
            id: $data['id'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'operation' => $this->operation->value,
            'id' => $this->id,
        ];
    }
}
