<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Public block execution result for a single workflow block.
 *
 * Terminal state is carried by the discriminated ``lifecycle`` union. The
 * legacy flat ``success`` / ``error`` / ``skipped`` fields were removed in
 * the hard cutover — they let invalid combinations (``success=true`` with
 * a non-empty ``error``) be representable on the wire and forced consumers
 * to know an undocumented field-precedence rule.
 */
readonly class StoredBlockExecution implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Unique block execution ID */
        public string $id,
        /** Workflow the block belongs to */
        public string $workflowId,
        /** Run whose inputs were used */
        public string $runId,
        /** ID of the block that was executed */
        public string $blockId,
        /** Type of the block */
        public string $blockType,
        /** Terminal lifecycle state for this block execution. One of ``{status: 'completed'}``, ``{status: 'error', message: ...}``, or ``{status: 'skipped', reason: ...}``. */
        public CompletedBlockExecutionLifecycle|ErrorBlockExecutionLifecycle|SkippedBlockExecutionLifecycle $lifecycle,
        /**
         * Input payloads keyed by handle ID (file metadata for files, data for json)
         * @var array<string, mixed>|null
         */
        public ?array $handleInputs = null,
        /** Canonical persisted-ref artifact for this block execution (operation + id), if any */
        public ?StepArtifactRef $artifact = null,
        /**
         * Output payloads keyed by handle ID
         * @var array<string, mixed>|null
         */
        public ?array $handleOutputs = null,
        /**
         * Active output handles for routing decisions
         * @var array<string>|null
         */
        public ?array $routingDecision = null,
        /** Duration of the block execution in milliseconds */
        public ?float $durationMs = null,
        public ?\DateTimeImmutable $createdAt = null,
        /**
         * The draft block config used for this block execution
         * @var array<string, mixed>|null
         */
        public ?array $blockConfig = null,
        /** The step ID that was used for inputs (includes iteration prefix if applicable) */
        public ?string $stepId = null,
        /**
         * When the block has multiple iterations, lists all available ones
         * @var array<array<string, mixed>>|null
         */
        public ?array $availableIterations = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'workflow_id',
            'run_id',
            'block_id',
            'block_type',
            'lifecycle',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for StoredBlockExecution::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            workflowId: $data['workflow_id'],
            runId: $data['run_id'],
            blockId: $data['block_id'],
            blockType: $data['block_type'],
            lifecycle: match ($data['lifecycle']['status'] ?? null) { 'completed' => CompletedBlockExecutionLifecycle::fromArray($data['lifecycle']), 'error' => ErrorBlockExecutionLifecycle::fromArray($data['lifecycle']), 'skipped' => SkippedBlockExecutionLifecycle::fromArray($data['lifecycle']), default => throw new \UnexpectedValueException(sprintf('Unknown status: %s', json_encode($data['lifecycle']['status'] ?? null))) },
            handleInputs: $data['handle_inputs'] ?? null,
            artifact: isset($data['artifact']) ? StepArtifactRef::fromArray($data['artifact']) : null,
            handleOutputs: $data['handle_outputs'] ?? null,
            routingDecision: $data['routing_decision'] ?? null,
            durationMs: $data['duration_ms'] ?? null,
            createdAt: isset($data['created_at']) ? new \DateTimeImmutable($data['created_at']) : null,
            blockConfig: $data['block_config'] ?? null,
            stepId: $data['step_id'] ?? null,
            availableIterations: $data['available_iterations'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'workflow_id' => $this->workflowId,
            'run_id' => $this->runId,
            'block_id' => $this->blockId,
            'block_type' => $this->blockType,
            'lifecycle' => $this->lifecycle->toArray(),
            'handle_inputs' => $this->handleInputs,
            'artifact' => $this->artifact?->toArray(),
            'handle_outputs' => $this->handleOutputs,
            'routing_decision' => $this->routingDecision,
            'duration_ms' => $this->durationMs,
            'created_at' => $this->createdAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'block_config' => $this->blockConfig,
            'step_id' => $this->stepId,
            'available_iterations' => $this->availableIterations,
        ];
    }
}
