<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Response from POST /workflows/reviews/{review_id}/approve | /reject.
 *
 * The shape carries ``resume_status`` so callers can see whether the
 * Temporal resume signal succeeded — meta-pattern §2 action-endpoint
 * criterion #4 (divergent response shape).
 */
readonly class SubmitDecisionResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public Review $review,
        public ?SubmissionStatus $submissionStatus = null,
        public ?ResumeStatus $resumeStatus = null,
        public ?string $resumeError = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'review',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SubmitDecisionResponse::fromArray()");
            }
        }
        return new self(
            review: Review::fromArray($data['review']),
            submissionStatus: isset($data['submission_status']) ? SubmissionStatus::from($data['submission_status']) : null,
            resumeStatus: isset($data['resume_status']) ? ResumeStatus::from($data['resume_status']) : null,
            resumeError: $data['resume_error'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'review' => $this->review->toArray(),
            'submission_status' => $this->submissionStatus?->value,
            'resume_status' => $this->resumeStatus?->value,
            'resume_error' => $this->resumeError,
        ];
    }
}
