<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

enum TableParsingFormat: string
{
    case Markdown = 'markdown';
    case Yaml = 'yaml';
    case Html = 'html';
    case Json = 'json';
}
