<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Request to update a block. Only provided fields are updated.
 *
 * ``config_mode`` is a request-level signal (not persisted) that controls
 * how the route folds the ``config`` patch into the existing config doc:
 *
 * * ``"merge"`` (default): RFC 7396 JSON Merge Patch — dicts recurse,
 *   arrays/scalars replace, ``null`` deletes the key. This is what CLI
 *   callers pass via ``--merge-config-file``.
 * * ``"replace"``: take ``config`` as the full new typed config. Top-level
 *   ``null`` values are pruned so the caller can wipe a key with one
 *   request. This is what CLI callers pass via ``--config-file``.
 *
 * Pre-config_mode callers (legacy SDKs, the canvas, any code that doesn't
 * send the field) keep the merge behavior; they were already sending
 * full configs on every save, which is idempotent under merge.
 */
readonly class UpdateWorkflowBlockRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?string $label = null,
        public ?float $positionX = null,
        public ?float $positionY = null,
        public ?float $width = null,
        public ?float $height = null,
        /** @var array<string, mixed>|null */
        public ?array $config = null,
        public ?string $parentId = null,
        /** How to apply the ``config`` field. 'merge' (default) deep-merges the patch into the existing config with null-as-delete; 'replace' uses the patch as the full new config. Not persisted. */
        public ?UpdateWorkflowBlockRequestConfigMode $configMode = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            label: $data['label'] ?? null,
            positionX: $data['position_x'] ?? null,
            positionY: $data['position_y'] ?? null,
            width: $data['width'] ?? null,
            height: $data['height'] ?? null,
            config: $data['config'] ?? null,
            parentId: $data['parent_id'] ?? null,
            configMode: isset($data['config_mode']) ? UpdateWorkflowBlockRequestConfigMode::from($data['config_mode']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'label' => $this->label,
            'position_x' => $this->positionX,
            'position_y' => $this->positionY,
            'width' => $this->width,
            'height' => $this->height,
            'config' => $this->config,
            'parent_id' => $this->parentId,
            'config_mode' => $this->configMode?->value,
        ];
    }
}
