<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class UpdateWorkflowTestRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?string $name = null,
        public ?AssertionSpec $assertion = null,
        public ManualWorkflowTestSource|RunStepWorkflowTestSource|null $source = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            name: $data['name'] ?? null,
            assertion: isset($data['assertion']) ? AssertionSpec::fromArray($data['assertion']) : null,
            source: isset($data['source']) ? match ($data['source']['type'] ?? null) { 'manual' => ManualWorkflowTestSource::fromArray($data['source']), 'run_step' => RunStepWorkflowTestSource::fromArray($data['source']), default => throw new \UnexpectedValueException(sprintf('Unknown type: %s', json_encode($data['source']['type'] ?? null))) } : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'name' => $this->name,
            'assertion' => $this->assertion?->toArray(),
            'source' => $this->source?->toArray(),
        ];
    }
}
