<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class UploadFileRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Filename to store */
        public string $filename,
        /** Expected upload size in bytes */
        public int $sizeBytes,
        /** MIME type the client will upload */
        public ?string $contentType = null,
        /** Optional SHA-256 checksum */
        public ?string $sha256 = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'filename',
            'size_bytes',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for UploadFileRequest::fromArray()");
            }
        }
        return new self(
            filename: $data['filename'],
            sizeBytes: $data['size_bytes'],
            contentType: $data['content_type'] ?? null,
            sha256: $data['sha256'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'filename' => $this->filename,
            'size_bytes' => $this->sizeBytes,
            'content_type' => $this->contentType,
            'sha256' => $this->sha256,
        ];
    }
}
