<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class VerdictSummary implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public bool $result,
        public ?int $assertionsPassed = null,
        public ?int $assertionsFailed = null,
        public ?int $blockedAssertions = null,
        /** @var array<string>|null */
        public ?array $failedAssertionIds = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            result: $data['result'],
            assertionsPassed: $data['assertions_passed'] ?? null,
            assertionsFailed: $data['assertions_failed'] ?? null,
            blockedAssertions: $data['blocked_assertions'] ?? null,
            failedAssertionIds: $data['failed_assertion_ids'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'result' => $this->result,
            'assertions_passed' => $this->assertionsPassed,
            'assertions_failed' => $this->assertionsFailed,
            'blocked_assertions' => $this->blockedAssertions,
            'failed_assertion_ids' => $this->failedAssertionIds,
        ];
    }
}
