<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Run started by an inbound webhook. */
readonly class WebhookTrigger implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** ID of the webhook configuration, when known */
        public ?string $webhookId = null,
        public string $type = 'webhook',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            webhookId: $data['webhook_id'] ?? null,
            type: $data['type'] ?? 'webhook',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'webhook_id' => $this->webhookId,
            'type' => $this->type,
        ];
    }
}
