<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

enum WhileLoopTerminationTerminationReason: string
{
    case MaxIterationsReached = 'max_iterations_reached';
    case ConditionMatched = 'condition_matched';
    case Error = 'error';
}
