<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class WorkflowExportPayloadRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Workflow ID to export */
        public string $workflowId,
        /** Block ID to export */
        public string $blockId,
        /** Use block outputs or inputs */
        public ?WorkflowExportPayloadRequestExportSource $exportSource = null,
        /**
         * Run IDs filter (null means all runs)
         * @var array<string>|null
         */
        public ?array $selectedRunIds = null,
        /**
         * Doc type filter (null/empty means all)
         * @var array<string>|null
         */
        public ?array $selectedDocTypes = null,
        /** Optional status filter (intersects with completed-only export scope) */
        public ?WorkflowRunsStatus $status = null,
        /** Optional status exclusion filter (intersects with completed-only export scope) */
        public ?WorkflowRunsStatus $excludeStatus = null,
        /** Optional start date filter (YYYY-MM-DD) */
        public ?string $fromDate = null,
        /** Optional end date filter (YYYY-MM-DD) */
        public ?string $toDate = null,
        /**
         * Optional trigger type filters
         * @var array<\Retab\Resource\WorkflowRunsTriggerType>|null
         */
        public ?array $triggerTypes = null,
        /**
         * Preferred data column order
         * @var array<string>|null
         */
        public ?array $preferredColumns = null,
        /** CSV field delimiter. Default is ';' (Excel-EU locale default); pass ',' for RFC 4180 / pandas compatibility. Cell values are always quoted when they contain the delimiter, the line terminator, or the quote character, with embedded quotes doubled per RFC 4180. */
        public ?string $delimiter = null,
        /** CSV line delimiter */
        public ?string $lineDelimiter = null,
        /** CSV quote character */
        public ?string $quote = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'workflow_id',
            'block_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for WorkflowExportPayloadRequest::fromArray()");
            }
        }
        return new self(
            workflowId: $data['workflow_id'],
            blockId: $data['block_id'],
            exportSource: isset($data['export_source']) ? WorkflowExportPayloadRequestExportSource::from($data['export_source']) : null,
            selectedRunIds: $data['selected_run_ids'] ?? null,
            selectedDocTypes: $data['selected_doc_types'] ?? null,
            status: isset($data['status']) ? WorkflowRunsStatus::from($data['status']) : null,
            excludeStatus: isset($data['exclude_status']) ? WorkflowRunsStatus::from($data['exclude_status']) : null,
            fromDate: $data['from_date'] ?? null,
            toDate: $data['to_date'] ?? null,
            triggerTypes: isset($data['trigger_types']) ? array_map(fn ($item) => WorkflowRunsTriggerType::from($item), $data['trigger_types']) : null,
            preferredColumns: $data['preferred_columns'] ?? null,
            delimiter: $data['delimiter'] ?? null,
            lineDelimiter: $data['line_delimiter'] ?? null,
            quote: $data['quote'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'workflow_id' => $this->workflowId,
            'block_id' => $this->blockId,
            'export_source' => $this->exportSource?->value,
            'selected_run_ids' => $this->selectedRunIds,
            'selected_doc_types' => $this->selectedDocTypes,
            'status' => $this->status?->value,
            'exclude_status' => $this->excludeStatus?->value,
            'from_date' => $this->fromDate,
            'to_date' => $this->toDate,
            'trigger_types' => $this->triggerTypes !== null ? array_map(fn ($item) => $item->value, $this->triggerTypes) : null,
            'preferred_columns' => $this->preferredColumns,
            'delimiter' => $this->delimiter,
            'line_delimiter' => $this->lineDelimiter,
            'quote' => $this->quote,
        ];
    }
}
