<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

enum WorkflowRunsStatus: string
{
    case Pending = 'pending';
    case Queued = 'queued';
    case Running = 'running';
    case Completed = 'completed';
    case Error = 'error';
    case Failed = 'failed';
    case AwaitingReview = 'awaiting_review';
    case Cancelled = 'cancelled';
}
