<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Body for POST /v1/workflows/edges. */
readonly class WorkflowEdgeCreateRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Workflow to create the edge in. */
        public string $workflowId,
        /** Source block ID */
        public string $sourceBlock,
        /** Target block ID */
        public string $targetBlock,
        /** Opaque edge ID. Omit to let the server generate one. */
        public ?string $id = null,
        /** Output handle */
        public ?string $sourceHandle = null,
        /** Input handle */
        public ?string $targetHandle = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            workflowId: $data['workflow_id'],
            sourceBlock: $data['source_block'],
            targetBlock: $data['target_block'],
            id: $data['id'] ?? null,
            sourceHandle: $data['source_handle'] ?? null,
            targetHandle: $data['target_handle'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'workflow_id' => $this->workflowId,
            'source_block' => $this->sourceBlock,
            'target_block' => $this->targetBlock,
            'id' => $this->id,
            'source_handle' => $this->sourceHandle,
            'target_handle' => $this->targetHandle,
        ];
    }
}
