<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class WorkflowBlockPosition implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public float $x,
        public float $y,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            x: $data['x'],
            y: $data['y'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'x' => $this->x,
            'y' => $this->y,
        ];
    }
}
