<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class WorkflowTestRun implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        public WorkflowSnapshotRef $workflow,
        public ManualTrigger|ApiTrigger|ScheduleTrigger|WebhookTrigger|EmailTrigger|RestartTrigger $trigger,
        public PendingWorkflowTestRun|QueuedWorkflowTestRun|RunningWorkflowTestRun|CompletedWorkflowTestRun|ErrorWorkflowTestRun|CancelledWorkflowTestRun $lifecycle,
        public WorkflowTestRunTiming $timing,
        public int $totalTests,
        public ?WorkflowTestBlockTarget $target = null,
        public ?string $testId = null,
        public ?BlockTestBatchExecutionCounts $counts = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            workflow: WorkflowSnapshotRef::fromArray($data['workflow']),
            trigger: match ($data['trigger']['type'] ?? null) { 'api' => ApiTrigger::fromArray($data['trigger']), 'email' => EmailTrigger::fromArray($data['trigger']), 'manual' => ManualTrigger::fromArray($data['trigger']), 'restart' => RestartTrigger::fromArray($data['trigger']), 'schedule' => ScheduleTrigger::fromArray($data['trigger']), 'webhook' => WebhookTrigger::fromArray($data['trigger']), default => throw new \UnexpectedValueException(sprintf('Unknown type: %s', json_encode($data['trigger']['type'] ?? null))) },
            lifecycle: match ($data['lifecycle']['status'] ?? null) { 'cancelled' => CancelledWorkflowTestRun::fromArray($data['lifecycle']), 'completed' => CompletedWorkflowTestRun::fromArray($data['lifecycle']), 'error' => ErrorWorkflowTestRun::fromArray($data['lifecycle']), 'pending' => PendingWorkflowTestRun::fromArray($data['lifecycle']), 'queued' => QueuedWorkflowTestRun::fromArray($data['lifecycle']), 'running' => RunningWorkflowTestRun::fromArray($data['lifecycle']), default => throw new \UnexpectedValueException(sprintf('Unknown status: %s', json_encode($data['lifecycle']['status'] ?? null))) },
            timing: WorkflowTestRunTiming::fromArray($data['timing']),
            totalTests: $data['total_tests'],
            target: isset($data['target']) ? WorkflowTestBlockTarget::fromArray($data['target']) : null,
            testId: $data['test_id'] ?? null,
            counts: isset($data['counts']) ? BlockTestBatchExecutionCounts::fromArray($data['counts']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'workflow' => $this->workflow->toArray(),
            'trigger' => $this->trigger->toArray(),
            'lifecycle' => $this->lifecycle->toArray(),
            'timing' => $this->timing->toArray(),
            'total_tests' => $this->totalTests,
            'target' => $this->target?->toArray(),
            'test_id' => $this->testId,
            'counts' => $this->counts?->toArray(),
        ];
    }
}
