<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class WorkflowExperiment implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        public string $workflowId,
        public string $blockId,
        public NConsensusValue $nConsensus,
        public string $name,
        public ReviewBlockType $blockType,
        public ?int $documentCount = null,
        public ?string $lastRunId = null,
        public ?\DateTimeImmutable $createdAt = null,
        public ?\DateTimeImmutable $updatedAt = null,
        public ?ExperimentPublicStatus $status = null,
        public ?float $score = null,
        public ?bool $isStale = null,
        public ?WorkflowTestSchemaDrift $schemaDrift = null,
        public ?string $schemaDriftDetail = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'workflow_id',
            'block_id',
            'n_consensus',
            'name',
            'block_type',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for WorkflowExperiment::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            workflowId: $data['workflow_id'],
            blockId: $data['block_id'],
            nConsensus: NConsensusValue::from($data['n_consensus']),
            name: $data['name'],
            blockType: ReviewBlockType::from($data['block_type']),
            documentCount: $data['document_count'] ?? null,
            lastRunId: $data['last_run_id'] ?? null,
            createdAt: isset($data['created_at']) ? new \DateTimeImmutable($data['created_at']) : null,
            updatedAt: isset($data['updated_at']) ? new \DateTimeImmutable($data['updated_at']) : null,
            status: isset($data['status']) ? ExperimentPublicStatus::from($data['status']) : null,
            score: $data['score'] ?? null,
            isStale: $data['is_stale'] ?? null,
            schemaDrift: isset($data['schema_drift']) ? WorkflowTestSchemaDrift::from($data['schema_drift']) : null,
            schemaDriftDetail: $data['schema_drift_detail'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'workflow_id' => $this->workflowId,
            'block_id' => $this->blockId,
            'n_consensus' => $this->nConsensus->value,
            'name' => $this->name,
            'block_type' => $this->blockType->value,
            'document_count' => $this->documentCount,
            'last_run_id' => $this->lastRunId,
            'created_at' => $this->createdAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'status' => $this->status?->value,
            'score' => $this->score,
            'is_stale' => $this->isStale,
            'schema_drift' => $this->schemaDrift?->value,
            'schema_drift_detail' => $this->schemaDriftDetail,
        ];
    }
}
