<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class WorkflowPublished implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Published content-addressed workflow version ID */
        public ?string $versionId = null,
        /** When the workflow was last published */
        public ?\DateTimeImmutable $publishedAt = null,
        /** Release note attached to the currently published version. Echoes the ``description`` body passed to ``POST /v1/workflows/{id}/publish`` so the caller can confirm it was stored without a separate fetch. */
        public ?string $description = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            versionId: $data['version_id'] ?? null,
            publishedAt: isset($data['published_at']) ? new \DateTimeImmutable($data['published_at']) : null,
            description: $data['description'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'version_id' => $this->versionId,
            'published_at' => $this->publishedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'description' => $this->description,
        ];
    }
}
