<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Public workflow-test target.
 *
 * The storage layer remains block-scoped today, but the API shape names the
 * tested entity explicitly so workflow-level targets can be added later.
 */
readonly class WorkflowTestBlockTarget implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $blockId,
        public string $type = 'block',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'block_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for WorkflowTestBlockTarget::fromArray()");
            }
        }
        return new self(
            blockId: $data['block_id'],
            type: $data['type'] ?? 'block',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'block_id' => $this->blockId,
            'type' => $this->type,
        ];
    }
}
