<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Public live workflow edge object. */
readonly class WorkflowEdgeDoc implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        /** Foreign key to workflow */
        public string $workflowId,
        /** ID of the source block */
        public string $sourceBlock,
        /** ID of the target block */
        public string $targetBlock,
        public \DateTimeImmutable $updatedAt,
        /** Output handle on source block */
        public ?string $sourceHandle = null,
        /** Input handle on target block */
        public ?string $targetHandle = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'workflow_id',
            'source_block',
            'target_block',
            'updated_at',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for WorkflowEdgeDoc::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            workflowId: $data['workflow_id'],
            sourceBlock: $data['source_block'],
            targetBlock: $data['target_block'],
            updatedAt: new \DateTimeImmutable($data['updated_at']),
            sourceHandle: $data['source_handle'] ?? null,
            targetHandle: $data['target_handle'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'workflow_id' => $this->workflowId,
            'source_block' => $this->sourceBlock,
            'target_block' => $this->targetBlock,
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'source_handle' => $this->sourceHandle,
            'target_handle' => $this->targetHandle,
        ];
    }
}
