<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Dereferenced workflow artifact with operation-specific fields preserved. */
readonly class WorkflowArtifact implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Artifact operation that determines the backing record type */
        public StepArtifactRefOperation $operation,
        /** Persisted resource identifier */
        public string $id,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            operation: StepArtifactRefOperation::from($data['operation']),
            id: $data['id'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'operation' => $this->operation->value,
            'id' => $this->id,
        ];
    }
}
