<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class WorkflowTest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        public string $workflowId,
        public WorkflowTestBlockTarget $target,
        public ManualWorkflowTestSource|RunStepWorkflowTestSource $source,
        public ?string $name = null,
        public ?AssertionSpec $assertion = null,
        public ?AssertionSchemaDep $assertionSchemaDep = null,
        public ?AssertionDriftStatus $assertionDriftStatus = null,
        public ?WorkflowTestSchemaDrift $schemaDrift = null,
        public ?string $schemaDriftDetail = null,
        public ?string $validationStatus = null,
        /** @var array<string>|null */
        public ?array $validationIssues = null,
        public ?LatestBlockTestRunSummary $latestRunSummary = null,
        public ?LatestBlockTestRunSummary $latestPassingRunSummary = null,
        public ?LatestBlockTestRunSummary $latestFailingRunSummary = null,
        public ?\DateTimeImmutable $createdAt = null,
        public ?\DateTimeImmutable $updatedAt = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'workflow_id',
            'target',
            'source',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for WorkflowTest::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            workflowId: $data['workflow_id'],
            target: WorkflowTestBlockTarget::fromArray($data['target']),
            source: match ($data['source']['type'] ?? null) { 'manual' => ManualWorkflowTestSource::fromArray($data['source']), 'run_step' => RunStepWorkflowTestSource::fromArray($data['source']), default => throw new \UnexpectedValueException(sprintf('Unknown type: %s', json_encode($data['source']['type'] ?? null))) },
            name: $data['name'] ?? null,
            assertion: isset($data['assertion']) ? AssertionSpec::fromArray($data['assertion']) : null,
            assertionSchemaDep: isset($data['assertion_schema_dep']) ? AssertionSchemaDep::fromArray($data['assertion_schema_dep']) : null,
            assertionDriftStatus: isset($data['assertion_drift_status']) ? AssertionDriftStatus::from($data['assertion_drift_status']) : null,
            schemaDrift: isset($data['schema_drift']) ? WorkflowTestSchemaDrift::from($data['schema_drift']) : null,
            schemaDriftDetail: $data['schema_drift_detail'] ?? null,
            validationStatus: $data['validation_status'] ?? null,
            validationIssues: $data['validation_issues'] ?? null,
            latestRunSummary: isset($data['latest_run_summary']) ? LatestBlockTestRunSummary::fromArray($data['latest_run_summary']) : null,
            latestPassingRunSummary: isset($data['latest_passing_run_summary']) ? LatestBlockTestRunSummary::fromArray($data['latest_passing_run_summary']) : null,
            latestFailingRunSummary: isset($data['latest_failing_run_summary']) ? LatestBlockTestRunSummary::fromArray($data['latest_failing_run_summary']) : null,
            createdAt: isset($data['created_at']) ? new \DateTimeImmutable($data['created_at']) : null,
            updatedAt: isset($data['updated_at']) ? new \DateTimeImmutable($data['updated_at']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'workflow_id' => $this->workflowId,
            'target' => $this->target->toArray(),
            'source' => $this->source->toArray(),
            'name' => $this->name,
            'assertion' => $this->assertion?->toArray(),
            'assertion_schema_dep' => $this->assertionSchemaDep?->toArray(),
            'assertion_drift_status' => $this->assertionDriftStatus?->value,
            'schema_drift' => $this->schemaDrift?->value,
            'schema_drift_detail' => $this->schemaDriftDetail,
            'validation_status' => $this->validationStatus,
            'validation_issues' => $this->validationIssues,
            'latest_run_summary' => $this->latestRunSummary?->toArray(),
            'latest_passing_run_summary' => $this->latestPassingRunSummary?->toArray(),
            'latest_failing_run_summary' => $this->latestFailingRunSummary?->toArray(),
            'created_at' => $this->createdAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
