<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class WorkflowExportPayloadResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** CSV content */
        public string $csvData,
        /** Data row count */
        public int $rows,
        /** Column count including fixed columns */
        public int $columns,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            csvData: $data['csv_data'],
            rows: $data['rows'],
            columns: $data['columns'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'csv_data' => $this->csvData,
            'rows' => $this->rows,
            'columns' => $this->columns,
        ];
    }
}
