<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

enum WorkflowBlockType: string
{
    case StartDocument = 'start_document';
    case StartJson = 'start_json';
    case Note = 'note';
    case Parse = 'parse';
    case Edit = 'edit';
    case Extract = 'extract';
    case Split = 'split';
    case Classifier = 'classifier';
    case Conditional = 'conditional';
    case ApiCall = 'api_call';
    case Review = 'review';
    case Function = 'function';
    case WhileLoop = 'while_loop';
    case ForEach = 'for_each';
    case MergeDicts = 'merge_dicts';
    case WhileLoopSentinelStart = 'while_loop_sentinel_start';
    case WhileLoopSentinelEnd = 'while_loop_sentinel_end';
    case ForEachSentinelStart = 'for_each_sentinel_start';
    case ForEachSentinelEnd = 'for_each_sentinel_end';
}
