<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Public workflow run response without tenant isolation fields.
 *
 * This is the API response shape — distinct from the internal storage
 * model (:class:`StoredWorkflowRun`), which carries persistence-only
 * fields that never appear in API responses. Routes call
 * :func:`serialize_workflow_run_response` to convert the storage shape
 * into this response shape; constructing this class directly for
 * persistence would drop those storage-only fields silently. The two
 * classes were deliberately renamed to avoid the prior name collision.
 */
readonly class WorkflowRun implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Unique ID for this run */
        public string $id,
        /** Workflow + version reference */
        public WorkflowSnapshotRef $workflow,
        /** What started this run */
        public ManualTrigger|ApiTrigger|ScheduleTrigger|WebhookTrigger|EmailTrigger|RestartTrigger $trigger,
        /** Discriminated lifecycle state. */
        public PendingRun|RunningRun|AwaitingReviewRun|CompletedTerminal|ErrorTerminal|CancelledTerminal|null $lifecycle = null,
        /** All timing information */
        public ?RunTiming $timing = null,
        /** Input payloads supplied at run creation time */
        public ?RunInputs $inputs = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            workflow: WorkflowSnapshotRef::fromArray($data['workflow']),
            trigger: match ($data['trigger']['type'] ?? null) { 'api' => ApiTrigger::fromArray($data['trigger']), 'email' => EmailTrigger::fromArray($data['trigger']), 'manual' => ManualTrigger::fromArray($data['trigger']), 'restart' => RestartTrigger::fromArray($data['trigger']), 'schedule' => ScheduleTrigger::fromArray($data['trigger']), 'webhook' => WebhookTrigger::fromArray($data['trigger']), default => throw new \UnexpectedValueException(sprintf('Unknown type: %s', json_encode($data['trigger']['type'] ?? null))) },
            lifecycle: isset($data['lifecycle']) ? match ($data['lifecycle']['status'] ?? null) { 'awaiting_review' => AwaitingReviewRun::fromArray($data['lifecycle']), 'cancelled' => CancelledTerminal::fromArray($data['lifecycle']), 'completed' => CompletedTerminal::fromArray($data['lifecycle']), 'error' => ErrorTerminal::fromArray($data['lifecycle']), 'pending' => PendingRun::fromArray($data['lifecycle']), 'running' => RunningRun::fromArray($data['lifecycle']), default => throw new \UnexpectedValueException(sprintf('Unknown status: %s', json_encode($data['lifecycle']['status'] ?? null))) } : null,
            timing: isset($data['timing']) ? RunTiming::fromArray($data['timing']) : null,
            inputs: isset($data['inputs']) ? RunInputs::fromArray($data['inputs']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'workflow' => $this->workflow->toArray(),
            'trigger' => $this->trigger->toArray(),
            'lifecycle' => $this->lifecycle?->toArray(),
            'timing' => $this->timing?->toArray(),
            'inputs' => $this->inputs?->toArray(),
        ];
    }
}
