<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Public workflow resource returned by workflow metadata endpoints.
 *
 * This is the API response shape — distinct from the internal storage
 * model (:class:`StoredWorkflow`), which carries persistence-only fields
 * that never appear in API responses. Routes call
 * :func:`serialize_workflow_response` to convert the storage shape into
 * this response shape; constructing this class directly for persistence
 * would drop those storage-only fields silently. The two classes were
 * deliberately renamed to avoid the prior name collision.
 */
readonly class Workflow implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Unique ID for this workflow */
        public string $id,
        public \DateTimeImmutable $createdAt,
        public \DateTimeImmutable $updatedAt,
        /** The name of the workflow */
        public ?string $name = null,
        /** Description of the workflow */
        public ?string $description = null,
        /** Published workflow metadata when a published version exists */
        public ?WorkflowPublished $published = null,
        /** Email trigger allowlist policy */
        public ?WorkflowEmailTrigger $emailTrigger = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
            name: $data['name'] ?? null,
            description: $data['description'] ?? null,
            published: isset($data['published']) ? WorkflowPublished::fromArray($data['published']) : null,
            emailTrigger: isset($data['email_trigger']) ? WorkflowEmailTrigger::fromArray($data['email_trigger']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'name' => $this->name,
            'description' => $this->description,
            'published' => $this->published?->toArray(),
            'email_trigger' => $this->emailTrigger?->toArray(),
        ];
    }
}
