<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Reference to the workflow + immutable version that drove the run.
 *
 * The class name is retained temporarily for compatibility with surrounding
 * run-model code, but public API output uses ``version_id`` rather than
 * snapshot identity.
 */
readonly class WorkflowSnapshotRef implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** ID of the workflow that was run */
        public string $workflowId,
        /** Content-addressed workflow version used for this run. */
        public string $versionId,
        /** Workflow name as it was at run-creation time (denormalized for display). */
        public string $nameAtRunTime,
        /** Raw version selector requested when this run was created */
        public ?string $requestedVersion = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            workflowId: $data['workflow_id'],
            versionId: $data['version_id'],
            nameAtRunTime: $data['name_at_run_time'],
            requestedVersion: $data['requested_version'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'workflow_id' => $this->workflowId,
            'version_id' => $this->versionId,
            'name_at_run_time' => $this->nameAtRunTime,
            'requested_version' => $this->requestedVersion,
        ];
    }
}
