<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class WorkflowConfigEdge implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** ID of the source block */
        public string $source,
        /** ID of the target block */
        public string $target,
        public ?string $id = null,
        public ?string $sourceHandle = null,
        public ?string $targetHandle = null,
        public ?bool $animated = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'source',
            'target',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for WorkflowConfigEdge::fromArray()");
            }
        }
        return new self(
            source: $data['source'],
            target: $data['target'],
            id: $data['id'] ?? null,
            sourceHandle: $data['source_handle'] ?? null,
            targetHandle: $data['target_handle'] ?? null,
            animated: $data['animated'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'source' => $this->source,
            'target' => $this->target,
            'id' => $this->id,
            'source_handle' => $this->sourceHandle,
            'target_handle' => $this->targetHandle,
            'animated' => $this->animated,
        ];
    }
}
