<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

enum WorkflowTestSchemaDrift: string
{
    case None = 'none';
    case Partial = 'partial';
    case Drifted = 'drifted';
    case Unknown = 'unknown';
}
