<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

enum WorkflowRunsTriggerType: string
{
    case Manual = 'manual';
    case Api = 'api';
    case Schedule = 'schedule';
    case Webhook = 'webhook';
    case Email = 'email';
    case Restart = 'restart';
}
