<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Retab\TestHelper;

class EditTemplatesTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('list_edit_template');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->editTemplates()->list(before: 'test_value', after: 'test_value', limit: 1, order: \Retab\Resource\JobsOrder::Asc, name: 'test_value', sortBy: 'test_value');
        $this->assertInstanceOf(\Retab\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/edits/templates', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['before']);
        $this->assertSame('test_value', $query['after']);
        $this->assertArrayHasKey('limit', $query);
        $this->assertSame('asc', $query['order']);
        $this->assertSame('test_value', $query['name']);
        $this->assertSame('test_value', $query['sort_by']);
    }

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('edit_template');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->editTemplates()->create(name: 'test_value', document: \Retab\Resource\MimeData::fromArray($this->loadFixture('mime_data')), formFields: []);
        $this->assertInstanceOf(\Retab\Resource\EditTemplate::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['name'], $result->name);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/edits/templates', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['name']);
    }

    public function testGet(): void
    {
        $fixture = $this->loadFixture('edit_template');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->editTemplates()->get('test_template_id');
        $this->assertInstanceOf(\Retab\Resource\EditTemplate::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['name'], $result->name);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/edits/templates/test_template_id', $request->getUri()->getPath());
    }

    public function testUpdate(): void
    {
        $fixture = $this->loadFixture('edit_template');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->editTemplates()->update('test_template_id');
        $this->assertInstanceOf(\Retab\Resource\EditTemplate::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['name'], $result->name);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v1/edits/templates/test_template_id', $request->getUri()->getPath());
    }

    public function testDelete(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->editTemplates()->delete('test_template_id');
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('v1/edits/templates/test_template_id', $request->getUri()->getPath());
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_edit_template');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->editTemplates()->list();
        $this->assertInstanceOf(\Retab\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
