<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Retab\TestHelper;

class ExperimentRunsTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('list_experiment_run');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->experimentRuns()->list(workflowId: 'test_value', experimentId: 'test_value', blockId: 'test_value', status: \Retab\Resource\WorkflowExperimentsStatus::Pending, statuses: 'test_value', excludeStatus: \Retab\Resource\WorkflowExperimentsStatus::Pending, triggerType: 'test_value', triggerTypes: 'test_value', fromDate: 'test_value', toDate: 'test_value', sortBy: 'test_value', before: 'test_value', after: 'test_value', limit: 1, order: \Retab\Resource\JobsOrder::Asc);
        $this->assertInstanceOf(\Retab\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/experiments/runs', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['workflow_id']);
        $this->assertSame('test_value', $query['experiment_id']);
        $this->assertSame('test_value', $query['block_id']);
        $this->assertSame('pending', $query['status']);
        $this->assertSame('test_value', $query['statuses']);
        $this->assertSame('pending', $query['exclude_status']);
        $this->assertSame('test_value', $query['trigger_type']);
        $this->assertSame('test_value', $query['trigger_types']);
        $this->assertSame('test_value', $query['from_date']);
        $this->assertSame('test_value', $query['to_date']);
        $this->assertSame('test_value', $query['sort_by']);
        $this->assertSame('test_value', $query['before']);
        $this->assertSame('test_value', $query['after']);
        $this->assertArrayHasKey('limit', $query);
        $this->assertSame('asc', $query['order']);
    }

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('experiment_run');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->experimentRuns()->create(experimentId: 'test_value');
        $this->assertInstanceOf(\Retab\Resource\ExperimentRun::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['experiment_id'], $result->experimentId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/experiments/runs', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['experiment_id']);
    }

    public function testGet(): void
    {
        $fixture = $this->loadFixture('experiment_run');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->experimentRuns()->get('test_run_id');
        $this->assertInstanceOf(\Retab\Resource\ExperimentRun::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['experiment_id'], $result->experimentId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/experiments/runs/test_run_id', $request->getUri()->getPath());
    }

    public function testCancel(): void
    {
        $fixture = $this->loadFixture('cancel_workflow_experiment_run_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->experimentRuns()->cancel('test_run_id');
        $this->assertInstanceOf(\Retab\Resource\CancelWorkflowExperimentRunResponse::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/experiments/runs/test_run_id/cancel', $request->getUri()->getPath());
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_experiment_run');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->experimentRuns()->list();
        $this->assertInstanceOf(\Retab\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
