<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Retab\TestHelper;

class ExperimentRunMetricsTest extends TestCase
{
    use TestHelper;

    public function testGet(): void
    {
        $fixture = $this->loadFixture('experiment_summary_metrics_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->experimentRunMetrics()->get(runId: 'test_value');
        $this->assertInstanceOf(\Retab\Resource\ExperimentSummaryMetricsResponse::class, $result);
        $this->assertSame($fixture['experiment_id'], $result->experimentId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/experiments/metrics', $request->getUri()->getPath());
    }
}
