<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Retab\TestHelper;

class FilesTest extends TestCase
{
    use TestHelper;

    public function testCreateUpload(): void
    {
        $fixture = $this->loadFixture('create_upload_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->files()->createUpload(filename: 'test_value', sizeBytes: 1);
        $this->assertInstanceOf(\Retab\Resource\CreateUploadResponse::class, $result);
        $this->assertSame($fixture['fileId'], $result->fileId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/files/upload', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['filename']);
        $this->assertSame(1, $body['size_bytes']);
    }

    public function testCompleteUpload(): void
    {
        $fixture = $this->loadFixture('mime_data');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->files()->completeUpload('test_file_id');
        $this->assertInstanceOf(\Retab\Resource\MimeData::class, $result);
        $this->assertSame($fixture['filename'], $result->filename);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/files/upload/test_file_id/complete', $request->getUri()->getPath());
    }

    public function testList(): void
    {
        $fixture = $this->loadFixture('list_file');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->files()->list(before: 'test_value', after: 'test_value', limit: 1, order: \Retab\Resource\JobsOrder::Asc, filename: 'test_value', mimeType: 'test_value', fromDate: 'test_value', toDate: 'test_value', includeEmbeddings: true, sortBy: 'test_value');
        $this->assertInstanceOf(\Retab\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/files', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['before']);
        $this->assertSame('test_value', $query['after']);
        $this->assertArrayHasKey('limit', $query);
        $this->assertSame('asc', $query['order']);
        $this->assertSame('test_value', $query['filename']);
        $this->assertSame('test_value', $query['mime_type']);
        $this->assertSame('test_value', $query['from_date']);
        $this->assertSame('test_value', $query['to_date']);
        $this->assertArrayHasKey('include_embeddings', $query);
        $this->assertSame('test_value', $query['sort_by']);
    }

    public function testGet(): void
    {
        $fixture = $this->loadFixture('file');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->files()->get('test_file_id');
        $this->assertInstanceOf(\Retab\Resource\File::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['filename'], $result->filename);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/files/test_file_id', $request->getUri()->getPath());
    }

    public function testGetDownloadLink(): void
    {
        $fixture = $this->loadFixture('file_link');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->files()->getDownloadLink('test_file_id');
        $this->assertInstanceOf(\Retab\Resource\FileLink::class, $result);
        $this->assertSame($fixture['download_url'], $result->downloadUrl);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/files/test_file_id/download-link', $request->getUri()->getPath());
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_file');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->files()->list();
        $this->assertInstanceOf(\Retab\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
