<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Retab\TestHelper;

class SchemaTest extends TestCase
{
    use TestHelper;

    public function testGenerate(): void
    {
        $fixture = $this->loadFixture('partial_schema');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->schemas()->generate(documents: []);
        $this->assertInstanceOf(\Retab\Resource\PartialSchema::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/schemas/generate', $request->getUri()->getPath());
    }
}
