<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Retab\TestHelper;

class WorkflowBlockExecutionsTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('block_execution_list');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowBlockExecutions()->list(runId: 'test_value', blockId: 'test_value');
        $this->assertInstanceOf(\Retab\Resource\BlockExecutionList::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/blocks/executions', $request->getUri()->getPath());
    }

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('stored_block_execution');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowBlockExecutions()->create(runId: 'test_value', blockId: 'test_value');
        $this->assertInstanceOf(\Retab\Resource\StoredBlockExecution::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['workflow_id'], $result->workflowId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/blocks/executions', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['run_id']);
        $this->assertSame('test_value', $body['block_id']);
    }
}
