<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Retab\TestHelper;

class WorkflowStepsTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('list_workflow_run_step');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowSteps()->list(runId: 'test_value', blockId: 'test_value', blockIds: [], stepId: 'test_value', blockType: [], status: [], before: 'test_value', after: 'test_value', limit: 1);
        $this->assertInstanceOf(\Retab\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/steps', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['run_id']);
        $this->assertSame('test_value', $query['block_id']);
        $this->assertSame('test_value', $query['step_id']);
        $this->assertSame('test_value', $query['before']);
        $this->assertSame('test_value', $query['after']);
        $this->assertArrayHasKey('limit', $query);
    }

    public function testGet(): void
    {
        $fixture = $this->loadFixture('workflow_run_step');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowSteps()->get('test_step_id');
        $this->assertInstanceOf(\Retab\Resource\WorkflowRunStep::class, $result);
        $this->assertSame($fixture['block_id'], $result->blockId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/steps/test_step_id', $request->getUri()->getPath());
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_workflow_run_step');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowSteps()->list();
        $this->assertInstanceOf(\Retab\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
