<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Retab\TestHelper;

class WorkflowTestRunResultsTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('workflow_test_result_list');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowTestRunResults()->list(runId: 'test_value');
        $this->assertInstanceOf(\Retab\Resource\WorkflowTestResultList::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/tests/results', $request->getUri()->getPath());
    }

    public function testGet(): void
    {
        $fixture = $this->loadFixture('workflow_test_result');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowTestRunResults()->get('test_result_id');
        $this->assertInstanceOf(\Retab\Resource\WorkflowTestResult::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['test_id'], $result->testId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/tests/results/test_result_id', $request->getUri()->getPath());
    }
}
