<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Retab\TestHelper;

class WorkflowSpecsTest extends TestCase
{
    use TestHelper;

    public function testValidate(): void
    {
        $fixture = $this->loadFixture('declarative_validation_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowSpecs()->validate(yamlDefinition: 'test_value');
        $this->assertInstanceOf(\Retab\Resource\DeclarativeValidationResponse::class, $result);
        $this->assertSame($fixture['workflow_id'], $result->workflowId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/spec/validate', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['yaml_definition']);
    }

    public function testPlan(): void
    {
        $fixture = $this->loadFixture('declarative_plan_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowSpecs()->plan(yamlDefinition: 'test_value');
        $this->assertInstanceOf(\Retab\Resource\DeclarativePlanResponse::class, $result);
        $this->assertSame($fixture['workflow_id'], $result->workflowId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/spec/plan', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['yaml_definition']);
    }

    public function testApply(): void
    {
        $fixture = $this->loadFixture('declarative_apply_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowSpecs()->apply(yamlDefinition: 'test_value');
        $this->assertInstanceOf(\Retab\Resource\DeclarativeApplyResponse::class, $result);
        $this->assertSame($fixture['workflow_id'], $result->workflowId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/spec/apply', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['yaml_definition']);
    }

    public function testGet(): void
    {
        $fixture = $this->loadFixture('declarative_export_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowSpecs()->get('test_workflow_id');
        $this->assertInstanceOf(\Retab\Resource\DeclarativeExportResponse::class, $result);
        $this->assertSame($fixture['workflow_id'], $result->workflowId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/test_workflow_id/spec', $request->getUri()->getPath());
    }
}
