<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Retab\TestHelper;

class WorkflowReviewsTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('list_review');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowReviews()->list(workflowId: 'test_value', runId: 'test_value', blockId: 'test_value', stepId: 'test_value', iterationKey: 'test_value', decisionStatus: \Retab\Resource\ReviewDecisionStatus::Pending, before: 'test_value', after: 'test_value', limit: 1);
        $this->assertInstanceOf(\Retab\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/reviews', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['workflow_id']);
        $this->assertSame('test_value', $query['run_id']);
        $this->assertSame('test_value', $query['block_id']);
        $this->assertSame('test_value', $query['step_id']);
        $this->assertSame('test_value', $query['iteration_key']);
        $this->assertSame('pending', $query['decision_status']);
        $this->assertSame('test_value', $query['before']);
        $this->assertSame('test_value', $query['after']);
        $this->assertArrayHasKey('limit', $query);
    }

    public function testGet(): void
    {
        $fixture = $this->loadFixture('review');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowReviews()->get('test_review_id');
        $this->assertInstanceOf(\Retab\Resource\Review::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['workflow_id'], $result->workflowId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/reviews/test_review_id', $request->getUri()->getPath());
    }

    public function testApprove(): void
    {
        $fixture = $this->loadFixture('submit_decision_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowReviews()->approve('test_review_id', versionId: 'test_value');
        $this->assertInstanceOf(\Retab\Resource\SubmitDecisionResponse::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/reviews/test_review_id/approve', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['version_id']);
    }

    public function testReject(): void
    {
        $fixture = $this->loadFixture('submit_decision_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowReviews()->reject('test_review_id', versionId: 'test_value', reason: 'test_value');
        $this->assertInstanceOf(\Retab\Resource\SubmitDecisionResponse::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/reviews/test_review_id/reject', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['version_id']);
        $this->assertSame('test_value', $body['reason']);
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_review');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowReviews()->list();
        $this->assertInstanceOf(\Retab\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
