<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Retab\TestHelper;

class WorkflowEdgesTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('list_workflow_edge_doc');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowEdges()->list(workflowId: 'test_value', sourceBlock: 'test_value', targetBlock: 'test_value', before: 'test_value', after: 'test_value', limit: 1);
        $this->assertInstanceOf(\Retab\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/edges', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['workflow_id']);
        $this->assertSame('test_value', $query['source_block']);
        $this->assertSame('test_value', $query['target_block']);
        $this->assertSame('test_value', $query['before']);
        $this->assertSame('test_value', $query['after']);
        $this->assertArrayHasKey('limit', $query);
    }

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('workflow_edge_doc');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowEdges()->create(workflowId: 'test_value', sourceBlock: 'test_value', targetBlock: 'test_value');
        $this->assertInstanceOf(\Retab\Resource\WorkflowEdgeDoc::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['workflow_id'], $result->workflowId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/edges', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['workflow_id']);
        $this->assertSame('test_value', $body['source_block']);
        $this->assertSame('test_value', $body['target_block']);
    }

    public function testGet(): void
    {
        $fixture = $this->loadFixture('workflow_edge_doc');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowEdges()->get('test_edge_id');
        $this->assertInstanceOf(\Retab\Resource\WorkflowEdgeDoc::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['workflow_id'], $result->workflowId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/edges/test_edge_id', $request->getUri()->getPath());
    }

    public function testDelete(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->workflowEdges()->delete('test_edge_id');
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/edges/test_edge_id', $request->getUri()->getPath());
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_workflow_edge_doc');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowEdges()->list(workflowId: 'test_value');
        $this->assertInstanceOf(\Retab\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
