<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Retab\TestHelper;

class WorkflowTestsTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('list_workflow_test');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowTests()->list(workflowId: 'test_value', targetBlockId: 'test_value', before: 'test_value', after: 'test_value', limit: 1, order: \Retab\Resource\JobsOrder::Asc);
        $this->assertInstanceOf(\Retab\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/tests', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['workflow_id']);
        $this->assertSame('test_value', $query['target_block_id']);
        $this->assertSame('test_value', $query['before']);
        $this->assertSame('test_value', $query['after']);
        $this->assertArrayHasKey('limit', $query);
        $this->assertSame('asc', $query['order']);
    }

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('workflow_test');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowTests()->create(workflowId: 'test_value', target: \Retab\Resource\WorkflowTestBlockTarget::fromArray($this->loadFixture('workflow_test_block_target')), source: 'test_value', assertion: \Retab\Resource\AssertionSpec::fromArray($this->loadFixture('assertion_spec')));
        $this->assertInstanceOf(\Retab\Resource\WorkflowTest::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['workflow_id'], $result->workflowId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/tests', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['workflow_id']);
    }

    public function testGet(): void
    {
        $fixture = $this->loadFixture('workflow_test');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowTests()->get('test_test_id');
        $this->assertInstanceOf(\Retab\Resource\WorkflowTest::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['workflow_id'], $result->workflowId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/tests/test_test_id', $request->getUri()->getPath());
    }

    public function testUpdate(): void
    {
        $fixture = $this->loadFixture('workflow_test');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowTests()->update('test_test_id');
        $this->assertInstanceOf(\Retab\Resource\WorkflowTest::class, $result);
        $this->assertSame($fixture['id'], $result->id);
        $this->assertSame($fixture['workflow_id'], $result->workflowId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/tests/test_test_id', $request->getUri()->getPath());
    }

    public function testDelete(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->workflowTests()->delete('test_test_id');
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('v1/workflows/tests/test_test_id', $request->getUri()->getPath());
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_workflow_test');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->workflowTests()->list(workflowId: 'test_value');
        $this->assertInstanceOf(\Retab\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
