<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\EditTemplate;

class EditTemplates
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * List Templates
     * @param string|null $before
     * @param string|null $after
     * @param int|null $limit Defaults to 10.
     * @param \Retab\Resource\ParsOrder $order Defaults to "desc".
     * @param string|null $name
     * @param string|null $sortBy Defaults to "created_at".
     * @return \Retab\PaginatedResponse<\Retab\Resource\EditTemplate>
     * @throws \Retab\Exception\RetabException
     */
    public function list(
        ?string $before = null,
        ?string $after = null,
        ?int $limit = null,
        \Retab\Resource\ParsOrder $order = \Retab\Resource\ParsOrder::Desc,
        ?string $name = null,
        ?string $sortBy = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order->value,
            'name' => $name,
            'sort_by' => $sortBy,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v1/edits/templates',
            query: $query,
            modelClass: EditTemplate::class,
            options: $options,
        );
    }

    /**
     * Create Template
     * @param string $name Name of the template.
     * @param \Retab\Resource\MimeData|\SplFileInfo|string|resource|array{filename?: string, url: string} $document The PDF document to use as the empty template.
     * @param array<\Retab\Resource\FormField> $formFields Form fields to attach to the template.
     * @return \Retab\Resource\EditTemplate
     * @throws \Retab\Exception\RetabException
     */
    public function create(
        string $name,
        mixed $document,
        array $formFields,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\EditTemplate {
        $document = \Retab\Resource\MimeDataCoerce::coerce($document);
        $body = [
            'name' => $name,
            'document' => $document,
            'form_fields' => $formFields,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/edits/templates',
            body: $body,
            options: $options,
        );
        return EditTemplate::fromArray($response);
    }

    /**
     * Get Template
     * @param string $templateId
     * @return \Retab\Resource\EditTemplate
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $templateId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\EditTemplate {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/edits/templates/' . rawurlencode($templateId),
            options: $options,
        );
        return EditTemplate::fromArray($response);
    }

    /**
     * Update Template
     * @param string $templateId
     * @param string|null $name New name for the template.
     * @param array<\Retab\Resource\FormField>|null $formFields Replacement list of form fields.
     * @return \Retab\Resource\EditTemplate
     * @throws \Retab\Exception\RetabException
     */
    public function update(
        string $templateId,
        ?string $name = null,
        ?array $formFields = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\EditTemplate {
        $body = array_filter([
            'name' => $name,
            'form_fields' => $formFields,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'PATCH',
            path: 'v1/edits/templates/' . rawurlencode($templateId),
            body: $body,
            options: $options,
        );
        return EditTemplate::fromArray($response);
    }

    /**
     * Delete Template
     * @param string $templateId
     * @return void
     * @throws \Retab\Exception\RetabException
     */
    public function delete(
        string $templateId,
        ?\Retab\RequestOptions $options = null,
    ): void {
        $this->client->request(
            method: 'DELETE',
            path: 'v1/edits/templates/' . rawurlencode($templateId),
            options: $options,
        );
    }
}
