<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\ExperimentSummaryMetricsResponse;

class ExperimentRunMetrics
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * Get Experiment Metrics For Run
     * @param string $runId
     * @param \Retab\Resource\ExperimentRunMetricsView $view Defaults to "summary".
     * @param string|null $documentId
     * @param string|null $targetPath
     * @param bool|null $includePrior Defaults to true.
     * @param string|null $priorRunId
     * @return \Retab\Resource\ExperimentSummaryMetricsResponse
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $runId,
        \Retab\Resource\ExperimentRunMetricsView $view = \Retab\Resource\ExperimentRunMetricsView::Summary,
        ?string $documentId = null,
        ?string $targetPath = null,
        ?bool $includePrior = null,
        ?string $priorRunId = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\ExperimentSummaryMetricsResponse {
        $query = array_filter([
            'run_id' => $runId,
            'view' => $view->value,
            'document_id' => $documentId,
            'target_path' => $targetPath,
            'include_prior' => $includePrior,
            'prior_run_id' => $priorRunId,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/workflows/experiments/metrics',
            query: $query,
            options: $options,
        );
        return ExperimentSummaryMetricsResponse::fromArray($response);
    }
}
