<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\CancelWorkflowExperimentRunResponse;
use Retab\Resource\ExperimentRun;

class ExperimentRuns
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * List Experiment Runs
     * @param string|null $workflowId
     * @param string|null $experimentId
     * @param string|null $blockId
     * @param \Retab\Resource\WorkflowExperimentsStatus|null $status
     * @param string|null $statuses
     * @param \Retab\Resource\WorkflowExperimentsStatus|null $excludeStatus
     * @param string|null $triggerType
     * @param string|null $triggerTypes
     * @param string|null $fromDate
     * @param string|null $toDate
     * @param string|null $sortBy Defaults to "created_at".
     * @param string|null $before
     * @param string|null $after
     * @param int|null $limit Defaults to 20.
     * @param \Retab\Resource\JobsOrder $order Defaults to "desc".
     * @return \Retab\PaginatedResponse<\Retab\Resource\ExperimentRun>
     * @throws \Retab\Exception\RetabException
     */
    public function list(
        ?string $workflowId = null,
        ?string $experimentId = null,
        ?string $blockId = null,
        ?\Retab\Resource\WorkflowExperimentsStatus $status = null,
        ?string $statuses = null,
        ?\Retab\Resource\WorkflowExperimentsStatus $excludeStatus = null,
        ?string $triggerType = null,
        ?string $triggerTypes = null,
        ?string $fromDate = null,
        ?string $toDate = null,
        ?string $sortBy = null,
        ?string $before = null,
        ?string $after = null,
        ?int $limit = null,
        \Retab\Resource\JobsOrder $order = \Retab\Resource\JobsOrder::Desc,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\PaginatedResponse {
        $query = array_filter([
            'workflow_id' => $workflowId,
            'experiment_id' => $experimentId,
            'block_id' => $blockId,
            'status' => $status?->value,
            'statuses' => $statuses,
            'exclude_status' => $excludeStatus?->value,
            'trigger_type' => $triggerType,
            'trigger_types' => $triggerTypes,
            'from_date' => $fromDate,
            'to_date' => $toDate,
            'sort_by' => $sortBy,
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order->value,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v1/workflows/experiments/runs',
            query: $query,
            modelClass: ExperimentRun::class,
            options: $options,
        );
    }

    /**
     * Create Experiment Run Flat
     *
     * Create an experiment run.
     *
     * The ``experiment_id`` and (optionally) ``workflow_id`` live in the
     * body — flat-resource shape per meta-pattern-blueprint §1. When
     * ``workflow_id`` is absent the experiment's stored workflow is used;
     * when present it must match (the validation rejects mismatched pairs
     * with 404, defending against confused-deputy callers).
     * @param string $experimentId The experiment to create a run for.
     * @param string|null $workflowId Optional. When omitted, the workflow is derived from the experiment record. When supplied, must match the experiment's workflow_id (404 otherwise).
     * @return \Retab\Resource\ExperimentRun
     * @throws \Retab\Exception\RetabException
     */
    public function create(
        string $experimentId,
        ?string $workflowId = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\ExperimentRun {
        $body = array_filter([
            'experiment_id' => $experimentId,
            'workflow_id' => $workflowId,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/workflows/experiments/runs',
            body: $body,
            options: $options,
        );
        return ExperimentRun::fromArray($response);
    }

    /**
     * Get Experiment Run
     * @param string $runId
     * @return \Retab\Resource\ExperimentRun
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $runId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\ExperimentRun {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/workflows/experiments/runs/' . rawurlencode($runId),
            options: $options,
        );
        return ExperimentRun::fromArray($response);
    }

    /**
     * Cancel Experiment Run
     * @param string $runId
     * @return \Retab\Resource\CancelWorkflowExperimentRunResponse
     * @throws \Retab\Exception\RetabException
     */
    public function cancel(
        string $runId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\CancelWorkflowExperimentRunResponse {
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/workflows/experiments/runs/' . rawurlencode($runId) . '/cancel',
            options: $options,
        );
        return CancelWorkflowExperimentRunResponse::fromArray($response);
    }
}
