<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\ExperimentResult;

class ExperimentRunResults
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * List Experiment Results
     * @param string $runId
     * @param int|null $limit Defaults to 100.
     * @return list<\Retab\Resource\ExperimentResult>
     * @throws \Retab\Exception\RetabException
     */
    public function list(
        string $runId,
        ?int $limit = null,
        ?\Retab\RequestOptions $options = null,
    ): array {
        $query = array_filter([
            'run_id' => $runId,
            'limit' => $limit,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/workflows/experiments/results',
            query: $query,
            options: $options,
        );
        return array_map(fn ($item) => ExperimentResult::fromArray($item), $response['data'] ?? []);
    }

    /**
     * Get Experiment Result
     * @param string $resultId
     * @return \Retab\Resource\ExperimentResult
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $resultId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\ExperimentResult {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/workflows/experiments/results/' . rawurlencode($resultId),
            options: $options,
        );
        return ExperimentResult::fromArray($response);
    }
}
