<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\CreateUploadResponse;
use Retab\Resource\File;
use Retab\Resource\FileLink;
use Retab\Resource\MimeData;

class Files
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * Upload File
     * @param string $filename Filename to store
     * @param string|null $contentType MIME type the client will upload
     * @param int $sizeBytes Expected upload size in bytes
     * @param string|null $sha256 Optional SHA-256 checksum
     * @return \Retab\Resource\CreateUploadResponse
     * @throws \Retab\Exception\RetabException
     */
    public function upload(
        string $filename,
        int $sizeBytes,
        ?string $contentType = null,
        ?string $sha256 = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\CreateUploadResponse {
        $body = array_filter([
            'filename' => $filename,
            'content_type' => $contentType,
            'size_bytes' => $sizeBytes,
            'sha256' => $sha256,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/files/upload',
            body: $body,
            options: $options,
        );
        return CreateUploadResponse::fromArray($response);
    }

    /**
     * Complete Upload File
     * @param string $fileId
     * @param string|null $sha256 Optional SHA-256 checksum
     * @return \Retab\Resource\MimeData
     * @throws \Retab\Exception\RetabException
     */
    public function completeUpload(
        string $fileId,
        ?string $sha256 = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\MimeData {
        $body = array_filter([
            'sha256' => $sha256,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/files/upload/' . rawurlencode($fileId) . '/complete',
            body: $body,
            options: $options,
        );
        return MimeData::fromArray($response);
    }

    /**
     * List Files
     *
     * List files with pagination and optional filtering.
     * @param string|null $before
     * @param string|null $after
     * @param int|null $limit Items per page Defaults to 10.
     * @param \Retab\Resource\JobsOrder $order Defaults to "desc".
     * @param string|null $filename
     * @param string|null $mimeType
     * @param string|null $fromDate
     * @param string|null $toDate
     * @param bool|null $includeEmbeddings Include embeddings in the response Defaults to false.
     * @param string|null $sortBy Defaults to "created_at".
     * @return \Retab\PaginatedResponse<\Retab\Resource\File>
     * @throws \Retab\Exception\RetabException
     */
    public function list(
        ?string $before = null,
        ?string $after = null,
        ?int $limit = null,
        \Retab\Resource\JobsOrder $order = \Retab\Resource\JobsOrder::Desc,
        ?string $filename = null,
        ?string $mimeType = null,
        ?string $fromDate = null,
        ?string $toDate = null,
        ?bool $includeEmbeddings = null,
        ?string $sortBy = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order->value,
            'filename' => $filename,
            'mime_type' => $mimeType,
            'from_date' => $fromDate,
            'to_date' => $toDate,
            'include_embeddings' => $includeEmbeddings,
            'sort_by' => $sortBy,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v1/files',
            query: $query,
            modelClass: File::class,
            options: $options,
        );
    }

    /**
     * Get File
     * @param string $fileId
     * @return \Retab\Resource\File
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $fileId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\File {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/files/' . rawurlencode($fileId),
            options: $options,
        );
        return File::fromArray($response);
    }

    /**
     * Download Link
     * @param string $fileId
     * @return \Retab\Resource\FileLink
     * @throws \Retab\Exception\RetabException
     */
    public function getDownloadLink(
        string $fileId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\FileLink {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/files/' . rawurlencode($fileId) . '/download-link',
            options: $options,
        );
        return FileLink::fromArray($response);
    }
}
