<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\Parse;

class Parses
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * List Parses
     * @param string|null $before
     * @param string|null $after
     * @param int|null $limit Defaults to 10.
     * @param \Retab\Resource\JobsOrder $order Defaults to "desc".
     * @param string|null $filename
     * @param string|null $fromDate
     * @param string|null $toDate
     * @return \Retab\PaginatedResponse<\Retab\Resource\Parse>
     * @throws \Retab\Exception\RetabException
     */
    public function list(
        ?string $before = null,
        ?string $after = null,
        ?int $limit = null,
        \Retab\Resource\JobsOrder $order = \Retab\Resource\JobsOrder::Desc,
        ?string $filename = null,
        ?string $fromDate = null,
        ?string $toDate = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order->value,
            'filename' => $filename,
            'from_date' => $fromDate,
            'to_date' => $toDate,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v1/parses',
            query: $query,
            modelClass: Parse::class,
            options: $options,
        );
    }

    /**
     * Create Parse
     * @param \Retab\Resource\MimeData|\SplFileInfo|string|resource|array{filename?: string, url: string} $document The document to parse
     * @param string|null $model The model to use for parsing
     * @param \Retab\Resource\TableParsingFormat|null $tableParsingFormat Format used to render tables extracted from the document
     * @param int|null $imageResolutionDpi DPI used when rasterizing pages for the parser
     * @param string|null $instructions Free-form instructions appended to the system prompt to steer the parse.
     * @param bool|null $bustCache If true, skip the LLM cache and force a fresh completion
     * @return \Retab\Resource\Parse
     * @throws \Retab\Exception\RetabException
     */
    public function create(
        mixed $document,
        ?string $model = null,
        ?\Retab\Resource\TableParsingFormat $tableParsingFormat = null,
        ?int $imageResolutionDpi = null,
        ?string $instructions = null,
        ?bool $bustCache = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\Parse {
        $document = \Retab\Resource\MimeDataCoerce::coerce($document);
        $body = array_filter([
            'document' => $document,
            'model' => $model,
            'table_parsing_format' => $tableParsingFormat?->value,
            'image_resolution_dpi' => $imageResolutionDpi,
            'instructions' => $instructions,
            'bust_cache' => $bustCache,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/parses',
            body: $body,
            options: $options,
        );
        return Parse::fromArray($response);
    }

    /**
     * Get Parse
     * @param string $parseId
     * @return \Retab\Resource\Parse
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $parseId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\Parse {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/parses/' . rawurlencode($parseId),
            options: $options,
        );
        return Parse::fromArray($response);
    }

    /**
     * Delete Parse
     * @param string $parseId
     * @return void
     * @throws \Retab\Exception\RetabException
     */
    public function delete(
        string $parseId,
        ?\Retab\RequestOptions $options = null,
    ): void {
        $this->client->request(
            method: 'DELETE',
            path: 'v1/parses/' . rawurlencode($parseId),
            options: $options,
        );
    }
}
