<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\Partition;

class PartitionService
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * List Partitions
     * @param string|null $before
     * @param string|null $after
     * @param int|null $limit Defaults to 10.
     * @param \Retab\Resource\ParsOrder $order Defaults to "desc".
     * @param string|null $filename
     * @param string|null $fromDate
     * @param string|null $toDate
     * @return \Retab\PaginatedResponse<\Retab\Resource\Partition>
     * @throws \Retab\Exception\RetabException
     */
    public function list(
        ?string $before = null,
        ?string $after = null,
        ?int $limit = null,
        \Retab\Resource\ParsOrder $order = \Retab\Resource\ParsOrder::Desc,
        ?string $filename = null,
        ?string $fromDate = null,
        ?string $toDate = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order->value,
            'filename' => $filename,
            'from_date' => $fromDate,
            'to_date' => $toDate,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v1/partitions',
            query: $query,
            modelClass: Partition::class,
            options: $options,
        );
    }

    /**
     * Create Partitions
     * @param \Retab\Resource\MimeData|\SplFileInfo|string|resource|array{filename?: string, url: string} $document The document to partition
     * @param string $key The key to partition the document by
     * @param string $instructions Instructions describing how the document should be partitioned
     * @param string|null $model The model to use for partitioning
     * @param int|null $nConsensus Number of partitioning runs to use for consensus voting. Uses deterministic single-pass when set to 1.
     * @param bool|null $allowOverlap If true, allow a page to appear in more than one partition chunk
     * @param bool|null $bustCache If true, skip the LLM cache and force a fresh completion
     * @return \Retab\Resource\Partition
     * @throws \Retab\Exception\RetabException
     */
    public function create(
        mixed $document,
        string $key,
        string $instructions,
        ?string $model = null,
        ?int $nConsensus = null,
        ?bool $allowOverlap = null,
        ?bool $bustCache = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\Partition {
        $document = \Retab\Resource\MimeDataCoerce::coerce($document);
        $body = array_filter([
            'document' => $document,
            'key' => $key,
            'instructions' => $instructions,
            'model' => $model,
            'n_consensus' => $nConsensus,
            'allow_overlap' => $allowOverlap,
            'bust_cache' => $bustCache,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/partitions',
            body: $body,
            options: $options,
        );
        return Partition::fromArray($response);
    }

    /**
     * Get Partition
     * @param string $partitionId
     * @return \Retab\Resource\Partition
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $partitionId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\Partition {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/partitions/' . rawurlencode($partitionId),
            options: $options,
        );
        return Partition::fromArray($response);
    }

    /**
     * Delete Partition
     * @param string $partitionId
     * @return void
     * @throws \Retab\Exception\RetabException
     */
    public function delete(
        string $partitionId,
        ?\Retab\RequestOptions $options = null,
    ): void {
        $this->client->request(
            method: 'DELETE',
            path: 'v1/partitions/' . rawurlencode($partitionId),
            options: $options,
        );
    }
}
