<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\PartialSchema;

class Schemas
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * Generate Schema From Examples
     *
     * Generates a JSON Schema from scratch by inferring structure from the content of the provided example documents.
     * @param array<\Retab\Resource\MimeData|\SplFileInfo|string|resource|array{filename?: string, url: string}> $documents
     * @param string|null $model
     * @param \Retab\Resource\GenerateSchemaRequestReasoningEffort|null $reasoningEffort
     * @param string|null $instructions
     * @param int|null $imageResolutionDpi Resolution of the image sent to the LLM
     * @param bool|null $stream
     * @return \Retab\Resource\PartialSchema
     * @throws \Retab\Exception\RetabException
     */
    public function generate(
        mixed $documents,
        ?string $model = null,
        ?\Retab\Resource\GenerateSchemaRequestReasoningEffort $reasoningEffort = null,
        ?string $instructions = null,
        ?int $imageResolutionDpi = null,
        ?bool $stream = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\PartialSchema {
        $documents = array_map([\Retab\Resource\MimeDataCoerce::class, 'coerce'], $documents);
        $body = array_filter([
            'documents' => $documents,
            'model' => $model,
            'reasoning_effort' => $reasoningEffort?->value,
            'instructions' => $instructions,
            'image_resolution_dpi' => $imageResolutionDpi,
            'stream' => $stream,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/schemas/generate',
            body: $body,
            options: $options,
        );
        return PartialSchema::fromArray($response);
    }
}
