<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\Split;

class Splits
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * List Splits
     * @param string|null $before
     * @param string|null $after
     * @param int|null $limit Defaults to 10.
     * @param \Retab\Resource\JobsOrder $order Defaults to "desc".
     * @param string|null $filename
     * @param string|null $fromDate
     * @param string|null $toDate
     * @return \Retab\PaginatedResponse<\Retab\Resource\Split>
     * @throws \Retab\Exception\RetabException
     */
    public function list(
        ?string $before = null,
        ?string $after = null,
        ?int $limit = null,
        \Retab\Resource\JobsOrder $order = \Retab\Resource\JobsOrder::Desc,
        ?string $filename = null,
        ?string $fromDate = null,
        ?string $toDate = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order->value,
            'filename' => $filename,
            'from_date' => $fromDate,
            'to_date' => $toDate,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v1/splits',
            query: $query,
            modelClass: Split::class,
            options: $options,
        );
    }

    /**
     * Create Split
     * @param \Retab\Resource\MimeData|\SplFileInfo|string|resource|array{filename?: string, url: string} $document The document to split
     * @param array<\Retab\Resource\Subdocument> $subdocuments The subdocuments to split the document into
     * @param string|null $model The model to use to split the document
     * @param string|null $instructions Free-form instructions appended to the system prompt to steer the split.
     * @param int|null $nConsensus Number of consensus split runs to perform. Uses deterministic single-pass when set to 1.
     * @param bool|null $bustCache If true, skip the LLM cache and force a fresh completion
     * @return \Retab\Resource\Split
     * @throws \Retab\Exception\RetabException
     */
    public function create(
        mixed $document,
        array $subdocuments,
        ?string $model = null,
        ?string $instructions = null,
        ?int $nConsensus = null,
        ?bool $bustCache = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\Split {
        $document = \Retab\Resource\MimeDataCoerce::coerce($document);
        $body = array_filter([
            'document' => $document,
            'subdocuments' => $subdocuments,
            'model' => $model,
            'instructions' => $instructions,
            'n_consensus' => $nConsensus,
            'bust_cache' => $bustCache,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/splits',
            body: $body,
            options: $options,
        );
        return Split::fromArray($response);
    }

    /**
     * Get Split
     * @param string $splitId
     * @return \Retab\Resource\Split
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $splitId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\Split {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/splits/' . rawurlencode($splitId),
            options: $options,
        );
        return Split::fromArray($response);
    }

    /**
     * Delete Split
     * @param string $splitId
     * @return void
     * @throws \Retab\Exception\RetabException
     */
    public function delete(
        string $splitId,
        ?\Retab\RequestOptions $options = null,
    ): void {
        $this->client->request(
            method: 'DELETE',
            path: 'v1/splits/' . rawurlencode($splitId),
            options: $options,
        );
    }
}
