<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\WorkflowTestResult;

class WorkflowTestRunResults
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * List Test Execution Results
     * @param string $runId
     * @return list<\Retab\Resource\WorkflowTestResult>
     * @throws \Retab\Exception\RetabException
     */
    public function list(
        string $runId,
        ?\Retab\RequestOptions $options = null,
    ): array {
        $query = [
            'run_id' => $runId,
        ];
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/workflows/tests/results',
            query: $query,
            options: $options,
        );
        return array_map(fn ($item) => WorkflowTestResult::fromArray($item), $response['data'] ?? []);
    }

    /**
     * Get Test Execution Result
     * @param string $resultId
     * @return \Retab\Resource\WorkflowTestResult
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $resultId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\WorkflowTestResult {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/workflows/tests/results/' . rawurlencode($resultId),
            options: $options,
        );
        return WorkflowTestResult::fromArray($response);
    }
}
