<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\ReviewVersion;

class WorkflowReviewVersions
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * List Review Versions Route
     *
     * List versions for one review.
     *
     * ``review_id`` is required by design — listing versions across all reviews
     * has no product use and would expose a needlessly wide query surface.
     * @param string $reviewId Required: the review whose versions to list.
     * @param string|null $before
     * @param string|null $after
     * @param int|null $limit Defaults to 50.
     * @return \Retab\PaginatedResponse<\Retab\Resource\ReviewVersion>
     * @throws \Retab\Exception\RetabException
     */
    public function list(
        string $reviewId,
        ?string $before = null,
        ?string $after = null,
        ?int $limit = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\PaginatedResponse {
        $query = array_filter([
            'review_id' => $reviewId,
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v1/workflows/reviews/versions',
            query: $query,
            modelClass: ReviewVersion::class,
            options: $options,
        );
    }

    /**
     * Create Review Version Route
     *
     * Create one immutable, content-addressed review version.
     * @param string $reviewId
     * @param string $parentId
     * @param array<string, mixed> $snapshot The full reviewed snapshot to store as an immutable version. The object must match the gated block type: extract uses the raw output object; classifier uses {'category': string}; split uses {'documents': [{'name': string, 'pages': positive sorted int[]}]}; for_each uses {'partitions': [{'key': string, 'pages': positive sorted int[]}]}. The server validates the shape and stores the exact submitted object when valid.
     * @param string|null $note
     * @return \Retab\Resource\ReviewVersion
     * @throws \Retab\Exception\RetabException
     */
    public function create(
        string $reviewId,
        string $parentId,
        array $snapshot,
        ?string $note = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\ReviewVersion {
        $body = array_filter([
            'review_id' => $reviewId,
            'parent_id' => $parentId,
            'snapshot' => $snapshot,
            'note' => $note,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/workflows/reviews/versions',
            body: $body,
            options: $options,
        );
        return ReviewVersion::fromArray($response);
    }

    /**
     * Get Review Version Route
     *
     * Read one review version by its content-addressed id.
     * @param string $versionId
     * @return \Retab\Resource\ReviewVersion
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $versionId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\ReviewVersion {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/workflows/reviews/versions/' . rawurlencode($versionId),
            options: $options,
        );
        return ReviewVersion::fromArray($response);
    }
}
