<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\WorkflowExperiment;

class WorkflowExperiments
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * List Experiments
     *
     * List experiments under one workflow with cursor pagination.
     *
     * The enrichment passes (latest-run snapshot, block info, drift detection)
     * run on the paginated page, not the full collection — so they scale with
     * ``limit``, not with the total experiment count under the workflow.
     * @param string $workflowId
     * @param string|null $before
     * @param string|null $after
     * @param int|null $limit Defaults to 50.
     * @param \Retab\Resource\JobsOrder $order Defaults to "desc".
     * @return \Retab\PaginatedResponse<\Retab\Resource\WorkflowExperiment>
     * @throws \Retab\Exception\RetabException
     */
    public function list(
        string $workflowId,
        ?string $before = null,
        ?string $after = null,
        ?int $limit = null,
        \Retab\Resource\JobsOrder $order = \Retab\Resource\JobsOrder::Desc,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\PaginatedResponse {
        $query = array_filter([
            'workflow_id' => $workflowId,
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order->value,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v1/workflows/experiments',
            query: $query,
            modelClass: WorkflowExperiment::class,
            options: $options,
        );
    }

    /**
     * Create Experiment
     *
     * Create an experiment.
     *
     * When ``source_experiment_id`` is set, duplicates the source experiment
     * (block, name + "(Copy)", n_consensus, documents) and rejects any other
     * field. Otherwise creates a fresh experiment from the provided fields.
     * @param string $workflowId
     * @param string|null $blockId
     * @param array<\Retab\Resource\ExperimentDocumentCaptureRequest>|null $documentCaptures
     * @param array<\Retab\Resource\ExplicitExperimentDocumentRequest>|null $documents
     * @param \Retab\Resource\NConsensusValue|null $nConsensus
     * @param string|null $name
     * @param string|null $sourceExperimentId
     * @return \Retab\Resource\WorkflowExperiment
     * @throws \Retab\Exception\RetabException
     */
    public function create(
        string $workflowId,
        ?string $blockId = null,
        ?array $documentCaptures = null,
        ?array $documents = null,
        ?\Retab\Resource\NConsensusValue $nConsensus = null,
        ?string $name = null,
        ?string $sourceExperimentId = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\WorkflowExperiment {
        $body = array_filter([
            'workflow_id' => $workflowId,
            'block_id' => $blockId,
            'document_captures' => $documentCaptures,
            'documents' => $documents,
            'n_consensus' => $nConsensus?->value,
            'name' => $name,
            'source_experiment_id' => $sourceExperimentId,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/workflows/experiments',
            body: $body,
            options: $options,
        );
        return WorkflowExperiment::fromArray($response);
    }

    /**
     * Get Experiment
     * @param string $experimentId
     * @return \Retab\Resource\WorkflowExperiment
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $experimentId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\WorkflowExperiment {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/workflows/experiments/' . rawurlencode($experimentId),
            options: $options,
        );
        return WorkflowExperiment::fromArray($response);
    }

    /**
     * Update Experiment
     * @param string $experimentId
     * @param array<\Retab\Resource\ExperimentDocumentCaptureRequest>|null $documentCaptures
     * @param array<\Retab\Resource\ExplicitExperimentDocumentRequest>|null $documents
     * @param \Retab\Resource\NConsensusValue|null $nConsensus
     * @param string|null $name
     * @return \Retab\Resource\WorkflowExperiment
     * @throws \Retab\Exception\RetabException
     */
    public function update(
        string $experimentId,
        ?array $documentCaptures = null,
        ?array $documents = null,
        ?\Retab\Resource\NConsensusValue $nConsensus = null,
        ?string $name = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\WorkflowExperiment {
        $body = array_filter([
            'document_captures' => $documentCaptures,
            'documents' => $documents,
            'n_consensus' => $nConsensus?->value,
            'name' => $name,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'PATCH',
            path: 'v1/workflows/experiments/' . rawurlencode($experimentId),
            body: $body,
            options: $options,
        );
        return WorkflowExperiment::fromArray($response);
    }

    /**
     * Delete Experiment
     * @param string $experimentId
     * @return void
     * @throws \Retab\Exception\RetabException
     */
    public function delete(
        string $experimentId,
        ?\Retab\RequestOptions $options = null,
    ): void {
        $this->client->request(
            method: 'DELETE',
            path: 'v1/workflows/experiments/' . rawurlencode($experimentId),
            options: $options,
        );
    }
}
