<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\WorkflowEdgeDoc;

class WorkflowEdges
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * List Edges
     *
     * List edges for a workflow with keyset cursor pagination.
     *
     * Optionally filter by source or target block ID. Sorted by ``updated_at``
     * descending with ``id`` as the tiebreaker. Pass ``after`` for the next
     * page, ``before`` for the previous page — mutually exclusive.
     * @param string $workflowId
     * @param string|null $sourceBlock Filter by source block ID
     * @param string|null $targetBlock Filter by target block ID
     * @param string|null $before Edge id cursor: return the page before this id (mutually exclusive with ``after``).
     * @param string|null $after Edge id cursor: return the page after this id (mutually exclusive with ``before``).
     * @param int|null $limit Maximum number of edges to return per page (1-200). Defaults to 100.
     * @return \Retab\PaginatedResponse<\Retab\Resource\WorkflowEdgeDoc>
     * @throws \Retab\Exception\RetabException
     */
    public function list(
        string $workflowId,
        ?string $sourceBlock = null,
        ?string $targetBlock = null,
        ?string $before = null,
        ?string $after = null,
        ?int $limit = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\PaginatedResponse {
        $query = array_filter([
            'workflow_id' => $workflowId,
            'source_block' => $sourceBlock,
            'target_block' => $targetBlock,
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v1/workflows/edges',
            query: $query,
            modelClass: WorkflowEdgeDoc::class,
            options: $options,
        );
    }

    /**
     * Create Edge
     *
     * Create a new edge connecting two blocks.
     *
     * Validates that:
     * - Both source and target blocks exist in the workflow
     * - The connection is semantically valid (type compatibility, container rules, etc.)
     * @param string $workflowId Workflow to create the edge in.
     * @param string|null $id Opaque edge ID. Omit to let the server generate one.
     * @param string $sourceBlock Source block ID
     * @param string $targetBlock Target block ID
     * @param string|null $sourceHandle Output handle
     * @param string|null $targetHandle Input handle
     * @return \Retab\Resource\WorkflowEdgeDoc
     * @throws \Retab\Exception\RetabException
     */
    public function create(
        string $workflowId,
        string $sourceBlock,
        string $targetBlock,
        ?string $id = null,
        ?string $sourceHandle = null,
        ?string $targetHandle = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\WorkflowEdgeDoc {
        $body = array_filter([
            'workflow_id' => $workflowId,
            'id' => $id,
            'source_block' => $sourceBlock,
            'target_block' => $targetBlock,
            'source_handle' => $sourceHandle,
            'target_handle' => $targetHandle,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/workflows/edges',
            body: $body,
            options: $options,
        );
        return WorkflowEdgeDoc::fromArray($response);
    }

    /**
     * Get Edge
     *
     * Get a single edge by ID.
     * @param string $edgeId
     * @return \Retab\Resource\WorkflowEdgeDoc
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $edgeId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\WorkflowEdgeDoc {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/workflows/edges/' . rawurlencode($edgeId),
            options: $options,
        );
        return WorkflowEdgeDoc::fromArray($response);
    }

    /**
     * Delete Edge
     *
     * Delete an edge from a workflow.
     * @param string $edgeId
     * @return void
     * @throws \Retab\Exception\RetabException
     */
    public function delete(
        string $edgeId,
        ?\Retab\RequestOptions $options = null,
    ): void {
        $this->client->request(
            method: 'DELETE',
            path: 'v1/workflows/edges/' . rawurlencode($edgeId),
            options: $options,
        );
    }
}
