<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\WorkflowTestRun;

class WorkflowTestRuns
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * List Test Execution Runs
     * @param string|null $workflowId
     * @param string|null $testId
     * @param string|null $targetBlockId
     * @param string|null $status
     * @param array<string>|null $statuses
     * @param string|null $excludeStatus
     * @param string|null $triggerType
     * @param array<string>|null $triggerTypes
     * @param \DateTimeImmutable|null $fromDate
     * @param \DateTimeImmutable|null $toDate
     * @param string|null $sortBy Defaults to "created_at".
     * @param string|null $before
     * @param string|null $after
     * @param int|null $limit Defaults to 50.
     * @param \Retab\Resource\JobsOrder $order Defaults to "desc".
     * @return \Retab\PaginatedResponse<\Retab\Resource\WorkflowTestRun>
     * @throws \Retab\Exception\RetabException
     */
    public function list(
        ?string $workflowId = null,
        ?string $testId = null,
        ?string $targetBlockId = null,
        ?string $status = null,
        ?array $statuses = null,
        ?string $excludeStatus = null,
        ?string $triggerType = null,
        ?array $triggerTypes = null,
        ?\DateTimeImmutable $fromDate = null,
        ?\DateTimeImmutable $toDate = null,
        ?string $sortBy = null,
        ?string $before = null,
        ?string $after = null,
        ?int $limit = null,
        \Retab\Resource\JobsOrder $order = \Retab\Resource\JobsOrder::Desc,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\PaginatedResponse {
        $query = array_filter([
            'workflow_id' => $workflowId,
            'test_id' => $testId,
            'target_block_id' => $targetBlockId,
            'status' => $status,
            'statuses' => $statuses,
            'exclude_status' => $excludeStatus,
            'trigger_type' => $triggerType,
            'trigger_types' => $triggerTypes,
            'from_date' => $fromDate,
            'to_date' => $toDate,
            'sort_by' => $sortBy,
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order->value,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v1/workflows/tests/runs',
            query: $query,
            modelClass: WorkflowTestRun::class,
            options: $options,
        );
    }

    /**
     * Create Test Run
     *
     * Create a workflow-scoped test run.
     *
     * Scoping identity comes from the body — ``workflow_id`` and/or
     * ``test_id`` per ``CreateWorkflowTestRunRequest``.
     * @return \Retab\Resource\WorkflowTestRun
     * @throws \Retab\Exception\RetabException
     */
    public function create(
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\WorkflowTestRun {
        $body = [
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/workflows/tests/runs',
            body: $body,
            options: $options,
        );
        return WorkflowTestRun::fromArray($response);
    }

    /**
     * Get Test Execution Run
     * @param string $runId
     * @return \Retab\Resource\WorkflowTestRun
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $runId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\WorkflowTestRun {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/workflows/tests/runs/' . rawurlencode($runId),
            options: $options,
        );
        return WorkflowTestRun::fromArray($response);
    }

    /**
     * Cancel Test Execution Run
     * @param string $runId
     * @return \Retab\Resource\WorkflowTestRun
     * @throws \Retab\Exception\RetabException
     */
    public function cancel(
        string $runId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\WorkflowTestRun {
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/workflows/tests/runs/' . rawurlencode($runId) . '/cancel',
            options: $options,
        );
        return WorkflowTestRun::fromArray($response);
    }
}
