<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\Workflow;
use Retab\Resource\WorkflowDiagnosisResponse;

class Workflows
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * List Workflows
     *
     * List workflows with pagination and optional filtering.
     * @param string|null $before
     * @param string|null $after
     * @param int|null $limit Items per page Defaults to 10.
     * @param \Retab\Resource\JobsOrder $order Defaults to "desc".
     * @param string|null $sortBy Defaults to "updated_at".
     * @return \Retab\PaginatedResponse<\Retab\Resource\Workflow>
     * @throws \Retab\Exception\RetabException
     */
    public function list(
        ?string $before = null,
        ?string $after = null,
        ?int $limit = null,
        \Retab\Resource\JobsOrder $order = \Retab\Resource\JobsOrder::Desc,
        ?string $sortBy = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\PaginatedResponse {
        $query = array_filter([
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
            'order' => $order->value,
            'sort_by' => $sortBy,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v1/workflows',
            query: $query,
            modelClass: Workflow::class,
            options: $options,
        );
    }

    /**
     * Create Workflow
     *
     * Create a new workflow.
     *
     * The workflow starts unpublished and is scaffolded with a default
     * "Document" input block in the live block collection.
     * @param string|null $name The name of the workflow
     * @param string|null $description Description of the workflow
     * @return \Retab\Resource\Workflow
     * @throws \Retab\Exception\RetabException
     */
    public function create(
        ?string $name = null,
        ?string $description = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\Workflow {
        $body = array_filter([
            'name' => $name,
            'description' => $description,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/workflows',
            body: $body,
            options: $options,
        );
        return Workflow::fromArray($response);
    }

    /**
     * Get Workflow
     *
     * Get a single workflow by ID.
     *
     * Returns workflow metadata only.
     * @param string $workflowId
     * @return \Retab\Resource\Workflow
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $workflowId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\Workflow {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/workflows/' . rawurlencode($workflowId),
            options: $options,
        );
        return Workflow::fromArray($response);
    }

    /**
     * Update Workflow
     *
     * Update an existing workflow.
     * @param string $workflowId
     * @param string|null $name The name of the workflow
     * @param string|null $description Description of the workflow
     * @return \Retab\Resource\Workflow
     * @throws \Retab\Exception\RetabException
     */
    public function update(
        string $workflowId,
        ?string $name = null,
        ?string $description = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\Workflow {
        $body = array_filter([
            'name' => $name,
            'description' => $description,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'PATCH',
            path: 'v1/workflows/' . rawurlencode($workflowId),
            body: $body,
            options: $options,
        );
        return Workflow::fromArray($response);
    }

    /**
     * Delete Workflow
     *
     * Delete a workflow and all its associated entities.
     *
     * This deletes:
     * - The workflow document
     * - All blocks and edges (live collections)
     * - All block and edge snapshots
     * - All workflow snapshots
     * @param string $workflowId
     * @return void
     * @throws \Retab\Exception\RetabException
     */
    public function delete(
        string $workflowId,
        ?\Retab\RequestOptions $options = null,
    ): void {
        $this->client->request(
            method: 'DELETE',
            path: 'v1/workflows/' . rawurlencode($workflowId),
            options: $options,
        );
    }

    /**
     * Diagnose Workflow Graph
     *
     * Diagnose a workflow graph payload for the given workflow.
     *
     * When the request omits ``blocks`` and ``edges`` (both ``None``) the route
     * loads the persisted draft from MongoDB. When either is provided (including
     * an explicit empty list) the request body is diagnosed as-is.
     * @param string $workflowId
     * @param array<\Retab\Resource\WorkflowConfigBlock>|null $blocks Blocks to diagnose; if omitted, the persisted draft is loaded server-side
     * @param array<\Retab\Resource\WorkflowConfigEdge>|null $edges Edges to diagnose; if omitted, the persisted draft is loaded server-side
     * @param bool|null $rePropagate Recompute derived schemas before validating the graph
     * @return \Retab\Resource\WorkflowDiagnosisResponse
     * @throws \Retab\Exception\RetabException
     */
    public function diagnose(
        string $workflowId,
        ?array $blocks = null,
        ?array $edges = null,
        ?bool $rePropagate = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\WorkflowDiagnosisResponse {
        $body = array_filter([
            'blocks' => $blocks,
            'edges' => $edges,
            're_propagate' => $rePropagate,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/workflows/' . rawurlencode($workflowId) . '/diagnose-graph',
            body: $body,
            options: $options,
        );
        return WorkflowDiagnosisResponse::fromArray($response);
    }

    /**
     * Publish Workflow
     *
     * Publish a workflow.
     *
     * This creates an immutable snapshot of the workflow configuration, making it available for workflow runs.
     * The live entities remain unchanged so users can continue editing.
     * @param string $workflowId
     * @return \Retab\Resource\Workflow
     * @throws \Retab\Exception\RetabException
     */
    public function publish(
        string $workflowId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\Workflow {
        $body = [
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/workflows/' . rawurlencode($workflowId) . '/publish',
            body: $body,
            options: $options,
        );
        return Workflow::fromArray($response);
    }
}
