<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\StoredBlockExecution;

class WorkflowBlockExecutions
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * List Block Executions
     *
     * List recent block executions for one workflow run block.
     * @param string $runId
     * @param string $blockId
     * @param int|null $limit Defaults to 20.
     * @return list<\Retab\Resource\StoredBlockExecution>
     * @throws \Retab\Exception\RetabException
     */
    public function list(
        string $runId,
        string $blockId,
        ?int $limit = null,
        ?\Retab\RequestOptions $options = null,
    ): array {
        $query = array_filter([
            'run_id' => $runId,
            'block_id' => $blockId,
            'limit' => $limit,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/workflows/blocks/executions',
            query: $query,
            options: $options,
        );
        return array_map(fn ($item) => StoredBlockExecution::fromArray($item), $response['data'] ?? []);
    }

    /**
     * Create Block Execution
     *
     * Create a block execution for ``block_id`` against the current draft.
     * @param string $runId Workflow run id that owns the step.
     * @param string $blockId Workflow block id to execute.
     * @param string|null $stepId Optional concrete step id whose inputs should be used. When omitted, the block id is used as the canonical step lookup key.
     * @param int|null $nConsensus Optional override for n_consensus on extract / split / classifier blocks. Must be 3, 5, or 7.
     * @param bool|null $checkEligibility Whether to verify the upstream subgraph hasn't drifted since the source run. Disable only for explicit force-rerun flows.
     * @return \Retab\Resource\StoredBlockExecution
     * @throws \Retab\Exception\RetabException
     */
    public function create(
        string $runId,
        string $blockId,
        ?string $stepId = null,
        ?int $nConsensus = null,
        ?bool $checkEligibility = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\StoredBlockExecution {
        $body = array_filter([
            'run_id' => $runId,
            'block_id' => $blockId,
            'step_id' => $stepId,
            'n_consensus' => $nConsensus,
            'check_eligibility' => $checkEligibility,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/workflows/blocks/executions',
            body: $body,
            options: $options,
        );
        return StoredBlockExecution::fromArray($response);
    }
}
