<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\Review;
use Retab\Resource\SubmitDecisionResponse;

class WorkflowReviews
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * List Reviews Route
     *
     * List reviews — the review queue, oldest first by ``created_at``.
     * @param string|null $workflowId
     * @param string|null $runId
     * @param string|null $blockId
     * @param string|null $stepId
     * @param string|null $iterationKey
     * @param \Retab\Resource\ReviewDecisionStatus $decisionStatus Filter by decision state: pending, approved, rejected, decided, or all. Defaults to "pending".
     * @param string|null $before Cursor: only return reviews that appear before this review id in the result order. Use list_metadata.before from the previous page.
     * @param string|null $after Cursor: only return reviews that appear after this review id in the result order. Use list_metadata.after from the previous page.
     * @param int|null $limit Defaults to 50.
     * @return \Retab\PaginatedResponse<\Retab\Resource\Review>
     * @throws \Retab\Exception\RetabException
     */
    public function list(
        ?string $workflowId = null,
        ?string $runId = null,
        ?string $blockId = null,
        ?string $stepId = null,
        ?string $iterationKey = null,
        \Retab\Resource\ReviewDecisionStatus $decisionStatus = \Retab\Resource\ReviewDecisionStatus::Pending,
        ?string $before = null,
        ?string $after = null,
        ?int $limit = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\PaginatedResponse {
        $query = array_filter([
            'workflow_id' => $workflowId,
            'run_id' => $runId,
            'block_id' => $blockId,
            'step_id' => $stepId,
            'iteration_key' => $iterationKey,
            'decision_status' => $decisionStatus->value,
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v1/workflows/reviews',
            query: $query,
            modelClass: Review::class,
            options: $options,
        );
    }

    /**
     * Get Review Route
     *
     * Read one review's metadata + decision. Versions are fetched separately.
     * @param string $reviewId
     * @return \Retab\Resource\Review
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $reviewId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\Review {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/workflows/reviews/' . rawurlencode($reviewId),
            options: $options,
        );
        return Review::fromArray($response);
    }

    /**
     * Approve Review Route
     *
     * Approve one exact review version and resume the Temporal run.
     *
     * Earns its action-verb shape per the four criteria in
     * ``meta-pattern-blueprint.md`` §2: precondition (``decision is None``),
     * side-effect dominates (Temporal resume signal), divergent request body vs
     * ``/reject``, divergent response (carries ``resume_status``).
     * @param string $reviewId
     * @param string $versionId Exact content-addressed key of the version to approve.
     * @return \Retab\Resource\SubmitDecisionResponse
     * @throws \Retab\Exception\RetabException
     */
    public function approve(
        string $reviewId,
        string $versionId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\SubmitDecisionResponse {
        $body = [
            'version_id' => $versionId,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/workflows/reviews/' . rawurlencode($reviewId) . '/approve',
            body: $body,
            options: $options,
        );
        return SubmitDecisionResponse::fromArray($response);
    }

    /**
     * Reject Review Route
     *
     * Reject one exact review version and resume the Temporal run.
     *
     * ``reason`` is required by the request shape — "rejected without reason"
     * is unrepresentable on the wire.
     * @param string $reviewId
     * @param string $versionId Exact content-addressed key of the version to reject.
     * @param string $reason Required, non-empty rejection reason.
     * @return \Retab\Resource\SubmitDecisionResponse
     * @throws \Retab\Exception\RetabException
     */
    public function reject(
        string $reviewId,
        string $versionId,
        string $reason,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\SubmitDecisionResponse {
        $body = [
            'version_id' => $versionId,
            'reason' => $reason,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/workflows/reviews/' . rawurlencode($reviewId) . '/reject',
            body: $body,
            options: $options,
        );
        return SubmitDecisionResponse::fromArray($response);
    }
}
