<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\DeclarativeApplyResponse;
use Retab\Resource\DeclarativeExportResponse;
use Retab\Resource\DeclarativePlanResponse;
use Retab\Resource\DeclarativeValidationResponse;

class WorkflowSpecs
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * Validate Workflow Spec
     *
     * Validate declarative YAML without mutating workflow state.
     *
     * Contract:
     * - validate, plan, and apply agree on whether a spec is acceptable: any
     *   severity=error diagnostic — whether emitted at parse time as a
     *   DeclarativeWorkflowError or bumped during compile/diagnose — raises
     *   HTTP 400 with the structured error issues
     * - warnings do not make the document invalid; warning-only specs return
     *   HTTP 200 with `is_valid=True` and the warning issues in `diagnostics`
     * - counts reflect the canonical compiled graph, not raw authored block count
     * @param string $yamlDefinition Workflow YAML definition
     * @return \Retab\Resource\DeclarativeValidationResponse
     * @throws \Retab\Exception\RetabException
     */
    public function validate(
        string $yamlDefinition,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\DeclarativeValidationResponse {
        $body = [
            'yaml_definition' => $yamlDefinition,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/workflows/spec/validate',
            body: $body,
            options: $options,
        );
        return DeclarativeValidationResponse::fromArray($response);
    }

    /**
     * Plan Workflow Spec
     *
     * Compute the declarative reconcile plan against the current draft workflow.
     *
     * Contract:
     * - plan compares authored YAML against current draft state
     * - canonical exported YAML should plan as `noop` against the same draft
     * @param string $yamlDefinition Workflow YAML definition
     * @return \Retab\Resource\DeclarativePlanResponse
     * @throws \Retab\Exception\RetabException
     */
    public function plan(
        string $yamlDefinition,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\DeclarativePlanResponse {
        $body = [
            'yaml_definition' => $yamlDefinition,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/workflows/spec/plan',
            body: $body,
            options: $options,
        );
        return DeclarativePlanResponse::fromArray($response);
    }

    /**
     * Apply Workflow Spec
     *
     * Apply declarative YAML to draft workflow state.
     *
     * Contract:
     * - apply writes canonical draft state, not authored formatting
     * - re-applying canonical exported YAML against unchanged draft state should
     *   return an empty resource_changes list
     * @param string $yamlDefinition Workflow YAML definition
     * @return \Retab\Resource\DeclarativeApplyResponse
     * @throws \Retab\Exception\RetabException
     */
    public function apply(
        string $yamlDefinition,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\DeclarativeApplyResponse {
        $body = [
            'yaml_definition' => $yamlDefinition,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/workflows/spec/apply',
            body: $body,
            options: $options,
        );
        return DeclarativeApplyResponse::fromArray($response);
    }

    /**
     * Export Workflow Spec
     *
     * Export draft workflow state as canonical declarative YAML.
     * @param string $workflowId
     * @return \Retab\Resource\DeclarativeExportResponse
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $workflowId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\DeclarativeExportResponse {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/workflows/' . rawurlencode($workflowId) . '/spec',
            options: $options,
        );
        return DeclarativeExportResponse::fromArray($response);
    }
}
