<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\WorkflowRunStep;

class WorkflowSteps
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {
    }

    /**
     * List Workflow Run Steps
     *
     * List steps with status and artifact summaries.
     *
     * Sorted by ``started_at`` ascending with ``step_id`` as the tiebreaker
     * (the same compound key the underlying index uses). Pass ``after`` for
     * the next page, ``before`` for the previous page — mutually exclusive.
     * ``run_id`` is optional; when omitted the list is scoped to the caller's
     * organization.
     * @param string|null $runId Optional workflow run ID filter.
     * @param string|null $blockId Optional logical block ID filter (deprecated; prefer ``block_ids`` for multi-value filtering).
     * @param array<string>|null $blockIds Optional logical block ID filter — multi-value. Repeat the query parameter (``?block_ids=a&block_ids=b``) to match any of several blocks. An empty list is treated as no filter. Preferred over the singular ``block_id``.
     * @param string|null $stepId Optional step ID filter.
     * @param array<string>|null $blockType Optional block type filter. Repeat the query parameter for multiple values.
     * @param array<string>|null $status Optional step lifecycle status filter. Repeat the query parameter for multiple values.
     * @param string|null $before Step id cursor: return the page before this id (mutually exclusive with ``after``).
     * @param string|null $after Step id cursor: return the page after this id (mutually exclusive with ``before``).
     * @param int|null $limit Maximum number of steps to return per page (1-1000). Defaults to 200; raise it for run-scoped queries on large DAGs and rely on cursor pagination for the rest. Defaults to 200.
     * @return \Retab\PaginatedResponse<\Retab\Resource\WorkflowRunStep>
     * @throws \Retab\Exception\RetabException
     */
    public function list(
        ?string $runId = null,
        ?string $blockId = null,
        ?array $blockIds = null,
        ?string $stepId = null,
        ?array $blockType = null,
        ?array $status = null,
        ?string $before = null,
        ?string $after = null,
        ?int $limit = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\PaginatedResponse {
        $query = array_filter([
            'run_id' => $runId,
            'block_id' => $blockId,
            'block_ids' => $blockIds,
            'step_id' => $stepId,
            'block_type' => $blockType,
            'status' => $status,
            'before' => $before,
            'after' => $after,
            'limit' => $limit,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v1/workflows/steps',
            query: $query,
            modelClass: WorkflowRunStep::class,
            options: $options,
        );
    }

    /**
     * Get Workflow Step
     *
     * Get one persisted step document by step id.
     *
     * This is the canonical step object shape used by ``GET /workflows/steps``.
     * It intentionally does not join fingerprint rows or return experiment query
     * projections.
     * @param string $stepId
     * @param string|null $runId Optional workflow run ID disambiguator.
     * @return \Retab\Resource\WorkflowRunStep
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $stepId,
        ?string $runId = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\WorkflowRunStep {
        $query = array_filter([
            'run_id' => $runId,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/workflows/steps/' . rawurlencode($stepId),
            query: $query,
            options: $options,
        );
        return WorkflowRunStep::fromArray($response);
    }
}
