<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab;

use Retab\Service\ClassificationService;
use Retab\Service\EditService;
use Retab\Service\EditTemplates;
use Retab\Service\ExperimentRunMetrics;
use Retab\Service\ExperimentRunResults;
use Retab\Service\ExperimentRuns;
use Retab\Service\ExtractionService;
use Retab\Service\FileService;
use Retab\Service\Jobs;
use Retab\Service\Pars;
use Retab\Service\PartitionService;
use Retab\Service\Schema;
use Retab\Service\SplitService;
use Retab\Service\WorkflowArtifacts;
use Retab\Service\WorkflowBlockExecutions;
use Retab\Service\WorkflowBlocks;
use Retab\Service\WorkflowEdges;
use Retab\Service\WorkflowExperiments;
use Retab\Service\WorkflowReviews;
use Retab\Service\WorkflowReviewVersions;
use Retab\Service\WorkflowRuns;
use Retab\Service\WorkflowService;
use Retab\Service\WorkflowSpecs;
use Retab\Service\WorkflowSteps;
use Retab\Service\WorkflowTestRunResults;
use Retab\Service\WorkflowTestRuns;
use Retab\Service\WorkflowTests;

class Client
{
    private static ?string $apiKey = null;
    private static ?string $clientId = null;
    private ?HttpClient $httpClient = null;

    public static function getApiKey(): ?string
    {
        return self::$apiKey;
    }

    public static function setApiKey(?string $key): void
    {
        self::$apiKey = $key;
    }

    public static function getClientId(): ?string
    {
        return self::$clientId;
    }

    public static function setClientId(?string $id): void
    {
        self::$clientId = $id;
    }
    private ?Service\Schema $schemas = null;
    private ?Service\ExtractionService $extractions = null;
    private ?Service\ClassificationService $classifications = null;
    private ?Service\Pars $parses = null;
    private ?Service\PartitionService $partitions = null;
    private ?Service\SplitService $splits = null;
    private ?Service\FileService $files = null;
    private ?Service\WorkflowRuns $workflowRuns = null;
    private ?Service\WorkflowSteps $workflowSteps = null;
    private ?Service\WorkflowReviews $workflowReviews = null;
    private ?Service\WorkflowReviewVersions $workflowReviewVersions = null;
    private ?Service\WorkflowArtifacts $workflowArtifacts = null;
    private ?Service\WorkflowTestRuns $workflowTestRuns = null;
    private ?Service\WorkflowTestRunResults $workflowTestRunResults = null;
    private ?Service\WorkflowBlocks $workflowBlocks = null;
    private ?Service\WorkflowEdges $workflowEdges = null;
    private ?Service\WorkflowTests $workflowTests = null;
    private ?Service\ExperimentRuns $experimentRuns = null;
    private ?Service\ExperimentRunResults $experimentRunResults = null;
    private ?Service\ExperimentRunMetrics $experimentRunMetrics = null;
    private ?Service\WorkflowExperiments $workflowExperiments = null;
    private ?Service\WorkflowBlockExecutions $workflowBlockExecutions = null;
    private ?Service\WorkflowService $workflows = null;
    private ?Service\WorkflowSpecs $workflowSpecs = null;
    private ?Service\EditTemplates $editTemplates = null;
    private ?Service\EditService $edits = null;
    private ?Service\Jobs $jobs = null;

    public function __construct(
        ?string $apiKey = null,
        ?string $clientId = null,
        string $baseUrl = 'https://api.retab.com',
        int $timeout = 60,
        int $maxRetries = 3,
        ?\GuzzleHttp\HandlerStack $handler = null,
        ?string $userAgent = null,
    ) {
        $apiKey ??= getenv('RETAB_API_KEY') ?: self::$apiKey ?? '';
        $clientId ??= getenv('RETAB_CLIENT_ID') ?: self::$clientId;
        $this->httpClient = new HttpClient($apiKey, $clientId, $baseUrl, $timeout, $maxRetries, $handler, $userAgent);
    }

    public function schemas(): Schema
    {
        return $this->schemas ??= new Service\Schema($this->httpClient);
    }

    public function extractions(): ExtractionService
    {
        return $this->extractions ??= new Service\ExtractionService($this->httpClient);
    }

    public function classifications(): ClassificationService
    {
        return $this->classifications ??= new Service\ClassificationService($this->httpClient);
    }

    public function parses(): Pars
    {
        return $this->parses ??= new Service\Pars($this->httpClient);
    }

    public function partitions(): PartitionService
    {
        return $this->partitions ??= new Service\PartitionService($this->httpClient);
    }

    public function splits(): SplitService
    {
        return $this->splits ??= new Service\SplitService($this->httpClient);
    }

    public function files(): FileService
    {
        return $this->files ??= new Service\FileService($this->httpClient);
    }

    public function workflowRuns(): WorkflowRuns
    {
        return $this->workflowRuns ??= new Service\WorkflowRuns($this->httpClient);
    }

    public function workflowSteps(): WorkflowSteps
    {
        return $this->workflowSteps ??= new Service\WorkflowSteps($this->httpClient);
    }

    public function workflowReviews(): WorkflowReviews
    {
        return $this->workflowReviews ??= new Service\WorkflowReviews($this->httpClient);
    }

    public function workflowReviewVersions(): WorkflowReviewVersions
    {
        return $this->workflowReviewVersions ??= new Service\WorkflowReviewVersions($this->httpClient);
    }

    public function workflowArtifacts(): WorkflowArtifacts
    {
        return $this->workflowArtifacts ??= new Service\WorkflowArtifacts($this->httpClient);
    }

    public function workflowTestRuns(): WorkflowTestRuns
    {
        return $this->workflowTestRuns ??= new Service\WorkflowTestRuns($this->httpClient);
    }

    public function workflowTestRunResults(): WorkflowTestRunResults
    {
        return $this->workflowTestRunResults ??= new Service\WorkflowTestRunResults($this->httpClient);
    }

    public function workflowBlocks(): WorkflowBlocks
    {
        return $this->workflowBlocks ??= new Service\WorkflowBlocks($this->httpClient);
    }

    public function workflowEdges(): WorkflowEdges
    {
        return $this->workflowEdges ??= new Service\WorkflowEdges($this->httpClient);
    }

    public function workflowTests(): WorkflowTests
    {
        return $this->workflowTests ??= new Service\WorkflowTests($this->httpClient);
    }

    public function experimentRuns(): ExperimentRuns
    {
        return $this->experimentRuns ??= new Service\ExperimentRuns($this->httpClient);
    }

    public function experimentRunResults(): ExperimentRunResults
    {
        return $this->experimentRunResults ??= new Service\ExperimentRunResults($this->httpClient);
    }

    public function experimentRunMetrics(): ExperimentRunMetrics
    {
        return $this->experimentRunMetrics ??= new Service\ExperimentRunMetrics($this->httpClient);
    }

    public function workflowExperiments(): WorkflowExperiments
    {
        return $this->workflowExperiments ??= new Service\WorkflowExperiments($this->httpClient);
    }

    public function workflowBlockExecutions(): WorkflowBlockExecutions
    {
        return $this->workflowBlockExecutions ??= new Service\WorkflowBlockExecutions($this->httpClient);
    }

    public function workflows(): WorkflowService
    {
        return $this->workflows ??= new Service\WorkflowService($this->httpClient);
    }

    public function workflowSpecs(): WorkflowSpecs
    {
        return $this->workflowSpecs ??= new Service\WorkflowSpecs($this->httpClient);
    }

    public function editTemplates(): EditTemplates
    {
        return $this->editTemplates ??= new Service\EditTemplates($this->httpClient);
    }

    public function edits(): EditService
    {
        return $this->edits ??= new Service\EditService($this->httpClient);
    }

    public function jobs(): Jobs
    {
        return $this->jobs ??= new Service\Jobs($this->httpClient);
    }
}
