<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab;

use Retab\Service\Classifications;
use Retab\Service\Edits;
use Retab\Service\EditTemplates;
use Retab\Service\ExperimentRunMetrics;
use Retab\Service\ExperimentRunResults;
use Retab\Service\ExperimentRuns;
use Retab\Service\Extractions;
use Retab\Service\Files;
use Retab\Service\Jobs;
use Retab\Service\Parses;
use Retab\Service\Partitions;
use Retab\Service\Schemas;
use Retab\Service\Splits;
use Retab\Service\WorkflowArtifacts;
use Retab\Service\WorkflowBlockExecutions;
use Retab\Service\WorkflowBlocks;
use Retab\Service\WorkflowEdges;
use Retab\Service\WorkflowExperiments;
use Retab\Service\WorkflowReviews;
use Retab\Service\WorkflowReviewVersions;
use Retab\Service\WorkflowRuns;
use Retab\Service\Workflows;
use Retab\Service\WorkflowSpecs;
use Retab\Service\WorkflowSteps;
use Retab\Service\WorkflowTestRunResults;
use Retab\Service\WorkflowTestRuns;
use Retab\Service\WorkflowTests;

class Client
{
    private static ?string $apiKey = null;
    private static ?string $clientId = null;
    private ?HttpClient $httpClient = null;

    public static function getApiKey(): ?string
    {
        return self::$apiKey;
    }

    public static function setApiKey(?string $key): void
    {
        self::$apiKey = $key;
    }

    public static function getClientId(): ?string
    {
        return self::$clientId;
    }

    public static function setClientId(?string $id): void
    {
        self::$clientId = $id;
    }
    private ?Service\Schemas $schemas = null;
    private ?Service\Extractions $extractions = null;
    private ?Service\Classifications $classifications = null;
    private ?Service\Parses $parses = null;
    private ?Service\Partitions $partitions = null;
    private ?Service\Splits $splits = null;
    private ?Service\Files $files = null;
    private ?Service\WorkflowRuns $workflowRuns = null;
    private ?Service\WorkflowSteps $workflowSteps = null;
    private ?Service\WorkflowReviews $workflowReviews = null;
    private ?Service\WorkflowReviewVersions $workflowReviewVersions = null;
    private ?Service\WorkflowArtifacts $workflowArtifacts = null;
    private ?Service\WorkflowTestRuns $workflowTestRuns = null;
    private ?Service\WorkflowTestRunResults $workflowTestRunResults = null;
    private ?Service\WorkflowBlocks $workflowBlocks = null;
    private ?Service\WorkflowEdges $workflowEdges = null;
    private ?Service\WorkflowTests $workflowTests = null;
    private ?Service\ExperimentRuns $experimentRuns = null;
    private ?Service\ExperimentRunResults $experimentRunResults = null;
    private ?Service\ExperimentRunMetrics $experimentRunMetrics = null;
    private ?Service\WorkflowExperiments $workflowExperiments = null;
    private ?Service\WorkflowBlockExecutions $workflowBlockExecutions = null;
    private ?Service\Workflows $workflows = null;
    private ?Service\WorkflowSpecs $workflowSpecs = null;
    private ?Service\EditTemplates $editTemplates = null;
    private ?Service\Edits $edits = null;
    private ?Service\Jobs $jobs = null;

    public function __construct(
        ?string $apiKey = null,
        ?string $clientId = null,
        string $baseUrl = 'https://api.retab.com',
        int $timeout = 60,
        int $maxRetries = 3,
        ?\GuzzleHttp\HandlerStack $handler = null,
        ?string $userAgent = null,
    ) {
        $apiKey ??= getenv('RETAB_API_KEY') ?: self::$apiKey ?? '';
        $clientId ??= getenv('RETAB_CLIENT_ID') ?: self::$clientId;
        $this->httpClient = new HttpClient($apiKey, $clientId, $baseUrl, $timeout, $maxRetries, $handler, $userAgent);
    }

    public function schemas(): Schemas
    {
        return $this->schemas ??= new Service\Schemas($this->httpClient);
    }

    public function extractions(): Extractions
    {
        return $this->extractions ??= new Service\Extractions($this->httpClient);
    }

    public function classifications(): Classifications
    {
        return $this->classifications ??= new Service\Classifications($this->httpClient);
    }

    public function parses(): Parses
    {
        return $this->parses ??= new Service\Parses($this->httpClient);
    }

    public function partitions(): Partitions
    {
        return $this->partitions ??= new Service\Partitions($this->httpClient);
    }

    public function splits(): Splits
    {
        return $this->splits ??= new Service\Splits($this->httpClient);
    }

    public function files(): Files
    {
        return $this->files ??= new Service\Files($this->httpClient);
    }

    public function workflowRuns(): WorkflowRuns
    {
        return $this->workflowRuns ??= new Service\WorkflowRuns($this->httpClient);
    }

    public function workflowSteps(): WorkflowSteps
    {
        return $this->workflowSteps ??= new Service\WorkflowSteps($this->httpClient);
    }

    public function workflowReviews(): WorkflowReviews
    {
        return $this->workflowReviews ??= new Service\WorkflowReviews($this->httpClient);
    }

    public function workflowReviewVersions(): WorkflowReviewVersions
    {
        return $this->workflowReviewVersions ??= new Service\WorkflowReviewVersions($this->httpClient);
    }

    public function workflowArtifacts(): WorkflowArtifacts
    {
        return $this->workflowArtifacts ??= new Service\WorkflowArtifacts($this->httpClient);
    }

    public function workflowTestRuns(): WorkflowTestRuns
    {
        return $this->workflowTestRuns ??= new Service\WorkflowTestRuns($this->httpClient);
    }

    public function workflowTestRunResults(): WorkflowTestRunResults
    {
        return $this->workflowTestRunResults ??= new Service\WorkflowTestRunResults($this->httpClient);
    }

    public function workflowBlocks(): WorkflowBlocks
    {
        return $this->workflowBlocks ??= new Service\WorkflowBlocks($this->httpClient);
    }

    public function workflowEdges(): WorkflowEdges
    {
        return $this->workflowEdges ??= new Service\WorkflowEdges($this->httpClient);
    }

    public function workflowTests(): WorkflowTests
    {
        return $this->workflowTests ??= new Service\WorkflowTests($this->httpClient);
    }

    public function experimentRuns(): ExperimentRuns
    {
        return $this->experimentRuns ??= new Service\ExperimentRuns($this->httpClient);
    }

    public function experimentRunResults(): ExperimentRunResults
    {
        return $this->experimentRunResults ??= new Service\ExperimentRunResults($this->httpClient);
    }

    public function experimentRunMetrics(): ExperimentRunMetrics
    {
        return $this->experimentRunMetrics ??= new Service\ExperimentRunMetrics($this->httpClient);
    }

    public function workflowExperiments(): WorkflowExperiments
    {
        return $this->workflowExperiments ??= new Service\WorkflowExperiments($this->httpClient);
    }

    public function workflowBlockExecutions(): WorkflowBlockExecutions
    {
        return $this->workflowBlockExecutions ??= new Service\WorkflowBlockExecutions($this->httpClient);
    }

    public function workflows(): Workflows
    {
        return $this->workflows ??= new Service\Workflows($this->httpClient);
    }

    public function workflowSpecs(): WorkflowSpecs
    {
        return $this->workflowSpecs ??= new Service\WorkflowSpecs($this->httpClient);
    }

    public function editTemplates(): EditTemplates
    {
        return $this->editTemplates ??= new Service\EditTemplates($this->httpClient);
    }

    public function edits(): Edits
    {
        return $this->edits ??= new Service\Edits($this->httpClient);
    }

    public function jobs(): Jobs
    {
        return $this->jobs ??= new Service\Jobs($this->httpClient);
    }
}
